import type { Metadata } from "next";
import { MultiLanguageCode } from "@/components/code/multi-language-code";
import { ClassificationChallenge } from "@/components/labs/design-labs";
import { LifecycleTimelineLab, MutabilityAuthorityLab, OwnershipCycleLab, OwnershipGraphLab, ReferenceSemanticsLab } from "@/components/labs/lifecycle-labs";
import { ChapterNav, CommonMistakes, ConceptPressure, InterviewCheckpoint, LanguageReality, LessonHero, LessonPager, RapidRevision, TradeoffPanel } from "@/components/lesson/primitives";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { lifecycleExamples } from "@/content/code-examples";
export const metadata:Metadata={title:"Object Lifecycle & Ownership",description:"Learn who creates, owns, shares, mutates, and cleans up objects and resources across C++, Go, Java, and TypeScript."};
const toc=[["01","Lifecycle","#start"],["02","Valid construction","#construction"],["03","Ownership","#ownership"],["04","Aliases","#mutation"],["05","Resources","#resources"],["06","Languages","#implementation"],["07","Challenge","#challenge"],["08","Interview","#interview"]] as const;
const questions=[
 {q:"What does object ownership mean?",a:"Ownership identifies who is responsible for an object&apos;s valid lifetime, mutation authority, and cleanup. It is a design responsibility, not merely a pointer type."},
 {q:"Does garbage collection remove the need for ownership design?",a:"No. GC reclaims unreachable memory. It does not decide who may mutate shared state, when a session expires, who cancels a goroutine, or who closes a socket."},
 {q:"unique_ptr vs shared_ptr?",a:"unique_ptr expresses one lifetime owner and transfers ownership explicitly. shared_ptr keeps an object alive while any strong owner remains. Prefer unique ownership unless the lifetime is genuinely shared."},
 {q:"When should shared_ptr be avoided?",a:"Avoid it as a default dependency handle or a substitute for deciding ownership. It adds atomic reference-count cost, obscures cleanup timing, and permits cycles."},
 {q:"What problem does weak_ptr solve?",a:"It observes a shared object without extending its lifetime. It commonly breaks strong reference cycles and requires checking whether the object still exists before use."},
 {q:"What is RAII?",a:"Resource Acquisition Is Initialization binds a resource to an object&apos;s lifetime so scope exit deterministically releases it—even during exceptions or early returns."},
 {q:"Can an object be logically dead while still in memory?",a:"Yes. A closed connection, expired session, cancelled reservation, or completed transaction may still be reachable but reject further operations."},
 {q:"Who should close a resource?",a:"The component that acquires or explicitly accepts ownership should close or return it, unless an API contract clearly transfers that responsibility."},
 {q:"Value vs reference semantics?",a:"A value is copied or replaced and equality comes from attributes. A reference aliases an identity; multiple holders can observe the same mutation and lifetime."},
 {q:"Why is shared mutable state dangerous?",a:"Callers can invalidate each other&apos;s assumptions, order becomes significant, and concurrency adds races. A single mutation authority or immutable snapshots narrow the problem."},
 {q:"Why should constructors establish invariants?",a:"A successfully constructed object should be immediately usable. Otherwise partially initialized objects can escape into callers that cannot tell which operations are safe."},
] as const;
const challenge=[{label:"EditorSession → Document",answer:"OWNS",hint:"The working document can be session-owned when it is created and disposed with that editing session; a persisted document identity could instead be referenced."},{label:"EditorSession → User",answer:"REFERENCES",hint:"The session identifies the user but should not control the user account&apos;s lifetime."},{label:"AutosaveWorker → EditorSession",answer:"BORROWS",hint:"The worker uses session state temporarily and must stop before the session ends."},{label:"EditorSession → StorageClient",answer:"REFERENCES",hint:"StorageClient is an injected, longer-lived dependency rather than a domain child."},{label:"Document → History entries",answer:"OWNS",hint:"History is commonly part of the document/session aggregate and follows its lifecycle."},{label:"Cursor position snapshot",answer:"VALUE",hint:"A small immutable position is easier to copy than share and mutate."}] ;
const failures=[["USE AFTER CLOSE","Calling charge() after PaymentSession reaches CLOSED."],["DANGLING REFERENCE","A borrower outlives the owner it points to."],["SHARED MUTATION","UI clears a Cart while checkout prices it."],["RESOURCE LEAK","A socket or response body is never closed."],["OWNERSHIP CYCLE","Strong references keep each other reachable forever."],["PARTIAL ESCAPE","A factory publishes an Order before currency is assigned."],["RUNAWAY WORK","Autosave or a goroutine continues after its request ends."],["STALE DOMAIN STATE","A reservation object remains reachable after expiry."]] as const;
export default function LifecyclePage(){return <article className="lesson-page"><div className="page-shell"><LessonHero chapter="04" group="Object Thinking" title="Objects live." accent="Design their lifetime." time="38 min lab" deck="A class diagram shows what exists. A reliable design also decides who creates each object, who may share or mutate it, when it stops being valid, and who cleans up." question="Who owns this object—and can every holder prove it is still valid?"/></div><ChapterNav chapter="04" items={toc}/>
<section className="lesson-section page-shell" id="start"><Reveal><SectionHeading eyebrow="01 · COLD OPEN" title="Checkout created four objects. Now who keeps them alive?" copy="Cart, Order, PaymentSession, and InventoryReservation begin together—but they do not necessarily share an owner or end together."/></Reveal><div className="lifecycle-questions">{["Can PaymentSession outlive Order?","Who cancels InventoryReservation?","May UI and checkout mutate one Cart?","What remains valid after payment succeeds?"].map((q,i)=><div key={q}><span>0{i+1}</span><p>{q}</p></div>)}</div><ConceptPressure><p>Modeling fields and methods is only half the design. Every object also has <b>creation, initialization, valid use, state transitions, cleanup, and an end of life.</b> Memory reachability cannot answer those domain questions.</p></ConceptPressure><LifecycleTimelineLab/></section>
<section className="lesson-section lesson-section--wide" id="construction"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · VALID CONSTRUCTION" title="A successful constructor should produce a usable object." copy="Setters after construction create a window where an Order has no customer, no currency, or an impossible status—and it may escape during that window."/></Reveal><div className="construction-compare"><div><span>PARTIAL OBJECT</span><code>{`const order = new Order();\norder.customerId = id;\norder.items = items;\norder.currency = currency;\norder.status = "DRAFT";`}</code><p>Every missing assignment is a new invalid state. Another function can observe the object between lines.</p></div><div><span>VALID AT BIRTH</span><code>{`const order = Order.draft({\n  customerId: id,\n  items,\n  currency\n});`}</code><p>A constructor or factory validates required data before returning. A builder is justified only when construction is genuinely complex.</p></div></div><div className="construction-rules">{[["CONSTRUCTOR","Required data is small and validation is immediate."],["FACTORY METHOD","Creation has a name, selects a subtype, or coordinates validation."],["BUILDER","Many optional steps need readable assembly before one final validation."],["NEVER","Publish this before invariants and dependencies are established."]].map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div></div></section>
<section className="lesson-section page-shell" id="ownership"><Reveal><SectionHeading eyebrow="03 · OWNERSHIP" title="A reference says where. Ownership says who is responsible." copy="Distinguish owning, referencing, borrowing, sharing, and copying. The arrow shape determines lifetime expectations as much as navigation."/></Reveal><OwnershipGraphLab/><div className="ownership-vocabulary">{[["OWNS","Creates or accepts lifetime responsibility; normally cleans up."],["REFERENCES","Uses a collaborator whose lifetime is managed elsewhere."],["BORROWS","Temporarily uses an object and must not retain it past the agreement."],["SHARES","Multiple parties deliberately extend one lifetime; mutation policy is still required."],["COPIES","Receives an independent value; later replacement does not mutate the source."]].map(([term,note])=><div key={term}><span>{term}</span><p>{note}</p></div>)}</div><ConceptPressure label="OWNERSHIP IS NOT REACHABILITY"><p>Ride references Driver and Rider participating in the trip; it does not own their account lifetimes. CheckoutService references PaymentGateway; the application composition root usually owns that dependency.</p></ConceptPressure></section>
<section className="lesson-section lesson-section--tint" id="mutation"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · VALUE, REFERENCE & MUTATION" title="Two names may point to one changing truth." copy="Aliasing is useful for identity, but surprising when every holder can write. Compare a shared Cart with an immutable value copy, then assign one mutation authority."/></Reveal><ReferenceSemanticsLab/><MutabilityAuthorityLab/><TradeoffPanel good={["Identity and coordinated change are required","One owner controls mutation","Read-only borrowers have bounded lifetimes"]} cost={["Copies can be expensive","Shared state requires ordering","Immutable updates allocate new values"]} avoid={["A small value can be copied safely","A borrower may outlive its owner","No component can explain cleanup"]}/></div></section>
<section className="lesson-section page-shell" id="resources"><Reveal><SectionHeading eyebrow="05 · RESOURCE OWNERSHIP" title="Memory can be reclaimed while the real resource leaks." copy="Files, sockets, locks, response bodies, threads, and transactions have external or logical lifetimes. Their owner needs deterministic cleanup or cancellation."/></Reveal><div className="resource-grid">{[["FILE","close / scope guard","Flush and release OS handle."],["MUTEX LOCK","unlock / RAII guard","Release even when control exits early."],["SOCKET","close / abort","Stop network I/O and free descriptors."],["TRANSACTION","commit or rollback","End database work explicitly."],["BACKGROUND WORK","cancel and join","Do not let work outlive its scope."],["SUBSCRIPTION","unsubscribe","Detach callbacks and producers."]].map(([name,cleanup,note])=><div key={name}><span>{name}</span><b>{cleanup}</b><p>{note}</p></div>)}</div><h2 className="subsection-title">C++ ownership cycle</h2><OwnershipCycleLab/><div className="scope-table"><div><span>LIFETIME</span><span>EXAMPLE</span><span>WHO USUALLY OWNS IT</span></div>{[["Application","Logger · gateway client","Composition root"],["Request","CheckoutService context","Request handler"],["Operation","PaymentSession · reservation","Checkout workflow"],["Borrowed","Database connection from pool","Pool retains; borrower returns"],["Object","Order-owned line items","Owning aggregate"]].map(row=><div key={row[0]}>{row.map(x=><span key={x}>{x}</span>)}</div>)}</div></section>
<section className="lesson-section lesson-section--wide" id="implementation"><div className="page-shell"><Reveal><SectionHeading eyebrow="06 · LANGUAGE REALITY" title="GC changes memory reclamation—not design responsibility." copy="The same PaymentSession contract uses different lifetime tools. Each version rejects invalid states and makes cleanup visible."/></Reveal><MultiLanguageCode examples={lifecycleExamples}/><div className="language-grid"><LanguageReality language="C++">Stack scope is deterministic. unique_ptr expresses single heap ownership; shared_ptr expresses shared lifetime; weak_ptr observes without extending lifetime. RAII ties cleanup to destruction.</LanguageReality><LanguageReality language="Java">GC reclaims unreachable memory, but files, connections, locks, and HTTP responses still need explicit cleanup. try-with-resources provides deterministic close().</LanguageReality><LanguageReality language="Go">GC manages memory, while defer, Close, context cancellation, and goroutine/channel ownership manage operation lifetimes. The goroutine starter should normally define how it stops.</LanguageReality><LanguageReality language="TypeScript / JavaScript">Timers, listeners, subscriptions, WebSockets, and fetch work can outlive their UI or request. AbortController and explicit unsubscribe/close prevent logical leaks.</LanguageReality></div><div className="test-panel"><span>TEST THE LIFETIME CONTRACT</span><code>{`session.close();\nexpect(() => session.process(order)).toThrow("session is not ready");\nexpect(gateway.chargeCount).toBe(0);\nexpect(abortSignal.aborted).toBe(true);`}</code><p>Test legal transitions, idempotent cleanup, cancellation, and rejection after terminal states—not only the happy result.</p></div></div></section>
<section className="lesson-section page-shell"><Reveal><SectionHeading eyebrow="FAILURE SCANNER" title="Lifecycle bugs leave distinct incident signatures." copy="These are different failures even when several look like ‘the object was wrong.’ Naming the failure points toward the right fix."/></Reveal><div className="incident-grid">{failures.map(([name,note],i)=><div key={name}><span>{String(i+1).padStart(2,"0")}</span><h3>{name}</h3><p>{note}</p></div>)}</div></section>
<section className="lesson-section lesson-section--tint" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="07 · WHO OWNS THIS?" title="Design a document editing session." copy="Classify default relationships, then read the nuance. Persistence boundaries can change an answer; the important part is making the lifetime contract explicit."/></Reveal><ClassificationChallenge title="DOCUMENT SESSION OWNERSHIP" items={challenge} categories={["OWNS","REFERENCES","BORROWS","SHARED","VALUE"]}/></div></section>
<section className="lesson-section page-shell" id="interview"><Reveal><SectionHeading eyebrow="08 · INTERVIEW CHECKPOINT" title="Trace creation to cleanup." copy="A strong answer separates memory, resource, and domain lifetimes and says who may mutate or outlive whom."/></Reveal><InterviewCheckpoint questions={questions}/><h2 className="subsection-title">Common mistakes</h2><CommonMistakes items={["GC means lifecycle does not matter.","shared_ptr everywhere is safe.","Every reference implies ownership.","Construct first and validate later.","Destructors or finalizers should perform all business cleanup.","Memory lifetime and domain validity are identical.","Long-lived services may retain request-scoped objects."]}/><div className="answer-card"><span>60-SECOND INTERVIEW ANSWER</span><blockquote>Object lifecycle covers creation, valid initialization, legal state transitions, cleanup, and logical end of life. Ownership states who controls that lifetime, mutation, and resource release; references and borrows only use the object under a lifetime contract. Garbage collection handles unreachable memory, not expired sessions, shared mutation, open resources, or runaway work. I prefer valid construction, explicit ownership transfer, bounded borrowing, and deterministic cleanup.</blockquote></div><RapidRevision items={[["Who creates it?","construction must establish invariants"],["Who owns it?","one place explains lifetime responsibility"],["Who mutates it?","prefer one controlled authority"],["Who observes it?","references and borrows need validity rules"],["How long is it valid?","logical life may end before memory life"],["Who cleans it up?","resource acquisition defines release responsibility"]]}/><LessonPager previous={{number:"03",title:"Inheritance & Polymorphism",href:"/learn/inheritance-polymorphism"}} next={{number:"05",title:"Single Responsibility Principle",href:"/learn/single-responsibility-principle",copy:"Find coherent change boundaries before a large class becomes a collision point."}}/></section></article>}
