import type { ReactNode } from "react";

export function InterviewPrompt({children}:{children:ReactNode}){return <aside className="interview-banner interview-banner--prompt"><span>INTERVIEW PROMPT</span><div>{children}</div></aside>}
export function YourTurn({question,children}:{question:string;children?:ReactNode}){return <details className="interview-banner interview-banner--turn"><summary><span>YOUR TURN</span>{question}</summary><div>{children}</div></details>}
export function InterviewerPressure({title,children}:{title:string;children:ReactNode}){return <aside className="interview-banner interview-banner--pressure"><span>INTERVIEWER PRESSURE</span><b>{title}</b><div>{children}</div></aside>}
export function ExtensionRound({children}:{children:ReactNode}){return <aside className="interview-banner interview-banner--extension"><span>EXTENSION ROUND</span><div>{children}</div></aside>}
export function ArchitectureReveal({title,nodes,sequence,states}:{title:string;nodes:readonly (readonly [string,string])[];sequence:readonly string[];states?:readonly string[]}){return <div className="architecture-reveal"><div className="design-review-label">DESIGN REVIEW · FINAL MODEL</div><h3>{title}</h3><div className="architecture-nodes" aria-label={`${title} domain class diagram`}>{nodes.map(([name,note])=><div key={name}><b>{name}</b><span>{note}</span></div>)}</div><div className="architecture-flow" aria-label={`${title} main sequence flow`}>{sequence.map((step,index)=><div key={step}><span>{String(index+1).padStart(2,"0")}</span><b>{step}</b></div>)}</div>{states&&<div className="architecture-states" aria-label={`${title} state diagram`}>{states.map((state,index)=><div key={state}><b>{state}</b>{index<states.length-1&&<span aria-hidden="true">→</span>}</div>)}</div>}</div>}
const dimensions=["Correctness","Domain clarity","Invariant protection","API quality","Change locality","Concurrency safety","Testability","Complexity discipline"];
export function DesignScorecard({notes}:{notes:readonly string[]}){return <div className="design-scorecard"><div className="design-review-label">DESIGN REVIEW · SCORECARD</div>{dimensions.map((dimension,index)=><div key={dimension}><b>{dimension}</b><span>{notes[index]??"Explain the trade-off and evidence."}</span></div>)}</div>}
export function RequirementTriage({inScope,outOfScope,invariants}:{inScope:readonly string[];outOfScope:readonly string[];invariants:readonly string[]}){return <div className="requirement-triage"><div><span>MUST SUPPORT</span>{inScope.map(x=><p key={x}>+ {x}</p>)}</div><div><span>DEFER DELIBERATELY</span>{outOfScope.map(x=><p key={x}>− {x}</p>)}</div><div><span>INVARIANTS</span>{invariants.map(x=><p key={x}>◆ {x}</p>)}</div></div>}
export function DecisionGrid({items}:{items:readonly (readonly [string,string,string])[]}){return <div className="domain-decision-grid">{items.map(([title,choice,reason])=><div key={title}><span>{title}</span><b>{choice}</b><p>{reason}</p></div>)}</div>}
