import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight } from "@/components/ui/icons";
const heroDefaults:Record<string,{object:string;code:string;labels:[string,string,string]}>={"01":{object:"Cart",code:"items\ntotal()\naddItem()",labels:["STATE","BEHAVIOR","BOUNDARY"]},"02":{object:"Order",code:"- status\n+ confirm()\n+ cancel()",labels:["ACCESS","INVARIANT","API"]},"03":{object:"PaymentMethod",code:"+ pay(order)",labels:["CONTRACT","DISPATCH","SUBSTITUTE"]},"04":{object:"PaymentSession",code:"CREATED → READY\nPROCESSING → CLOSED",labels:["CREATE","VALID LIFETIME","CLEANUP"]},"05":{object:"OrderService",code:"validate · price · pay\nsave · notify · invoice",labels:["ACTOR","CHANGE","RESPONSIBILITY"]},"06":{object:"PricingService",code:"core + extension point\nDiscountPolicy.apply()",labels:["VARIATION","CONTRACT","EXTEND"]},"07":{object:"Storage",code:"save · load · delete\nbehavior = promise",labels:["CONTRACT","SUBSTITUTE","TRUST"]},"08":{object:"CheckoutService",code:"OrderStore · PaymentPort\nNotificationPort",labels:["FOCUS","DIRECTION","POLICY"]},"09":{object:"OrderManager",code:"price · save · email\nreport · audit · export",labels:["COHESION","COUPLING","CHANGE"]},"10":{object:"Vehicle",code:"ElectricFlyingCar\nArmoredBoatCar",labels:["HIERARCHY","CAPABILITY","COMPOSE"]},"11":{object:"ReservationAPI",code:"reserve(request)\nResult<Reservation>",labels:["INTENT","VALIDITY","EVOLUTION"]},"12":{object:"checkout",code:"nesting · flags · magic\nside effects · mixed jobs",labels:["INTENT","FLOW","CLARITY"]},"13":{object:"FoodDeliveryService",code:"pricing · drivers · pay\nnotify · analytics",labels:["BOUNDARY","OWNERSHIP","CHANGE"]},"14":{object:"Checkout",code:"validate → inventory\npayment → persistence",labels:["CLASSIFY","HANDLE","PRESERVE"]}};
export function LessonHero({chapter,group,title,accent,deck,question,time="32 min lab",heroObject,heroCode,heroLabels}:{chapter:string;group:string;title:string;accent:string;deck:string;question:string;time?:string;heroObject?:string;heroCode?:string;heroLabels?:[string,string,string]}){const visual=heroDefaults[chapter]??heroDefaults["01"];const labels=heroLabels??visual.labels;return <section className="lesson-hero"><div className="lesson-breadcrumb"><Link href="/#learning-map">Learning map</Link><span>/</span><b>{group}</b><span>/</span><span>Chapter {chapter}</span></div><div className="lesson-hero-grid"><div><p className="eyebrow"><span/>FOUNDATION · {time}</p><h1>{title}<br/><em>{accent}</em></h1><p className="lesson-deck">{deck}</p><div className="lesson-principle"><b>THE QUESTION</b><p>{question}</p></div><a className="text-link" href="#start">Begin the experiment <ArrowRight/></a></div><div className="lesson-hero-diagram" aria-label={`${heroObject??visual.object} model under design pressure`}><div className="diagram-coordinates"><span>MODEL / {chapter}</span><span>PRESSURE / ACTIVE</span></div><div className="uml-class"><small>OBJECT</small><strong>{heroObject??visual.object}</strong><hr/><code>{heroCode??visual.code}</code></div><div className="diagram-pressure"><span>REQUIREMENT CHANGE</span><i/><b>?</b></div><div className="diagram-caption"><span>{labels[0]}</span><i/><span>{labels[1]}</span><i/><span>{labels[2]}</span></div></div></div></section>}
export function ChapterNav({chapter,items}:{chapter:string;items:readonly (readonly [string,string,string])[]}){return <nav className="chapter-nav" aria-label="Chapter sections"><div className="page-shell"><span>CHAPTER {chapter}</span><div>{items.map(([n,l,h])=><a href={h} key={n}><small>{n}</small>{l}</a>)}</div></div></nav>}
export function ConceptPressure({children,label="CHANGE PRESSURE"}:{children:ReactNode;label?:string}){return <div className="pressure-callout"><span>{label}</span><div>{children}</div></div>}
export function LanguageReality({language,children}:{language:string;children:ReactNode}){return <aside className="language-reality"><span>LANGUAGE REALITY · {language}</span><p>{children}</p></aside>}
export function TradeoffPanel({good,cost,avoid}:{good:string[];cost:string[];avoid:string[]}){return <div className="tradeoff-panel"><div><span>IT HELPS WHEN</span>{good.map(x=><p key={x}>+ {x}</p>)}</div><div><span>IT COSTS</span>{cost.map(x=><p key={x}>± {x}</p>)}</div><div><span>AVOID WHEN</span>{avoid.map(x=><p key={x}>− {x}</p>)}</div></div>}
export function InterviewCheckpoint({questions}:{questions:readonly {q:string;a:string}[]}){return <div className="interview-checkpoint"><div className="checkpoint-intro"><span>INTERVIEW MODE</span><h3>Answer before you reveal.</h3><p>Say your answer out loud. A strong answer names the pressure, the boundary, and the trade-off.</p></div><div>{questions.map((item,i)=><details key={item.q}><summary><span>{String(i+1).padStart(2,"0")}</span>{item.q}</summary><p>{item.a}</p></details>)}</div></div>}
export function CommonMistakes({items}:{items:readonly string[]}){return <div className="mistake-grid">{items.map((item,i)=><div key={item}><span>{String(i+1).padStart(2,"0")}</span><p>{item}</p></div>)}</div>}
export function RapidRevision({items}:{items:readonly [string,string][]}){return <div className="rapid-revision"><div className="terminal-bar"><span/><span/><span/><code>rapid-revision.txt</code><em>60 SEC</em></div>{items.map(([term,note])=><p key={term}><b>{term}</b><span>→</span>{note}</p>)}</div>}
export function LessonPager({previous,next}:{previous?:{number:string;title:string;href:string};next:{number:string;title:string;href?:string;copy:string}}){return <div className="lesson-pager">{previous?<Link href={previous.href} className="lesson-pager__previous"><ArrowRight/><span><small>PREVIOUS · {previous.number}</small><b>{previous.title}</b></span></Link>:<span/>}{next.href?<Link href={next.href} className="lesson-pager__next"><span><small>NEXT · {next.number}</small><b>{next.title}</b><em>{next.copy}</em></span><ArrowRight/></Link>:<div className="lesson-pager__next lesson-pager__next--locked"><span><small>NEXT · {next.number} · COMING SOON</small><b>{next.title}</b><em>{next.copy}</em></span><ArrowRight/></div>}</div>}
