import type { Metadata } from "next";
import { MultiLanguageCode } from "@/components/code/multi-language-code";
import { ClassificationChallenge } from "@/components/labs/design-labs";
import { BlastRadiusLab, ClassExplosionLab, ResponsibilityPressureLab, ResponsibilityRefactorLab } from "@/components/labs/srp-labs";
import { ChapterNav, CommonMistakes, ConceptPressure, InterviewCheckpoint, LanguageReality, LessonHero, LessonPager, RapidRevision, TradeoffPanel } from "@/components/lesson/primitives";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { srpExamples } from "@/content/code-examples";
export const metadata:Metadata={title:"Single Responsibility Principle",description:"Learn SRP as coherent reasons to change through an interactive OrderService refactor and blast-radius simulator."};
const toc=[["01","Change pressure","#start"],["02","Real SRP","#definition"],["03","Refactor","#refactor"],["04","Blast radius","#change"],["05","Testability","#testing"],["06","Languages","#implementation"],["07","Challenge","#challenge"],["08","Interview","#interview"]] as const;
const questions=[
 {q:"What does SRP actually mean?",a:"A module should own one coherent responsibility and therefore have one coherent reason to change. It is about change boundaries, not counting methods."},
 {q:"Why is ‘one class should do one thing’ incomplete?",a:"Thing is ambiguous. Checkout may validate, price, reserve, charge, and save while still owning one orchestration responsibility. The question is whether those decisions change together."},
 {q:"What is a reason to change?",a:"A source of policy or requirement pressure—often a business capability, actor, stakeholder, regulation, provider, or operational concern."},
 {q:"How do you identify responsibilities?",a:"Observe which methods and data change together, which actors request changes, which tests share setup, and whether a stable vocabulary describes the module&apos;s purpose."},
 {q:"Can a class have many methods and still follow SRP?",a:"Yes. Money add, subtract, multiply, compare, and format can remain one cohesive value responsibility."},
 {q:"Can a one-method class violate SRP?",a:"Yes. One giant process() can validate, persist, call providers, format output, and emit analytics for unrelated reasons."},
 {q:"What is the relationship between SRP and cohesion?",a:"SRP seeks a cohesive change boundary: members belong because they serve one meaningful responsibility. Cohesion is evidence, not a mechanical score."},
 {q:"Does SRP mean creating more classes?",a:"It may produce collaborators, but class count is not the goal. Splitting code that changes together can make the system harder to reason about."},
 {q:"How can over-applying SRP hurt?",a:"It creates file and interface explosions, wiring, navigation overhead, fragmented invariants, and premature abstractions whose change axes never materialize."},
 {q:"How does SRP improve testing?",a:"Focused policies need fewer dependencies and smaller fixtures. Orchestrators can use small fakes. Easier testing is a common outcome, not proof by itself."},
 {q:"Does CheckoutService orchestrating five services violate SRP?",a:"Not necessarily. If it owns one checkout workflow and delegates volatile policies, those coordination steps form one coherent reason to change."},
] as const;
const challenge=[{label:"validate user input",answer:"RegistrationPolicy",hint:"Product validation rules form one policy boundary."},{label:"hash password",answer:"PasswordHasher",hint:"Security algorithm and work-factor changes should be isolated."},{label:"save user",answer:"UserRepository",hint:"Persistence mapping and storage mechanics change independently."},{label:"send welcome email",answer:"WelcomeNotifier",hint:"Templates and delivery channels belong to notification."},{label:"assign free trial",answer:"RegistrationOrchestrator",hint:"This business step can remain part of the coherent registration workflow while a TrialPolicy calculates eligibility."},{label:"track signup analytics",answer:"AnalyticsTracker",hint:"Analytics schemas and destinations change for measurement reasons."}] ;
const smells=[["HUGE CLASS","A signal when size comes from unrelated policy clusters."],["DEPENDENCY FAN-OUT","Database, email, payments, inventory, analytics, invoices in one constructor."],["TEST MEGAFIXTURE","Every test configures systems irrelevant to the behavior under test."],["TEAM COLLISION","Unrelated teams repeatedly edit and merge the same module."],["GENERIC NAME","Manager, Utility, Helper, or Processor hides the real capability."],["METHOD CLUSTERS","Separate groups use different fields and rarely call each other."]] as const;
export default function SrpPage(){return <article className="lesson-page"><div className="page-shell"><LessonHero chapter="05" group="SOLID & Maintainability" title="One coherent" accent="reason to change." time="40 min lab" deck="SRP is not one method per class. It is the discipline of keeping independent policies, actors, and change pressures from colliding in one module." question="Who asks this code to change—and do those changes belong together?"/></div><ChapterNav chapter="05" items={toc}/>
<section className="lesson-section page-shell" id="start"><Reveal><SectionHeading eyebrow="01 · COLD OPEN" title="OrderService became the place where every team meets." copy="It validates, prices, reserves, saves, charges, emails, logs, analyzes, and invoices. Convenient at first—until independent requirements arrive."/></Reveal><pre className="naive-code"><code>{`class OrderService {\n  validateOrder()\n  calculateTax() · calculateDiscount()\n  reserveInventory() · saveOrder()\n  chargeCard() · sendConfirmationEmail()\n  generateInvoice() · trackAnalytics()\n}`}</code></pre><div className="actor-grid">{[["FINANCE","tax"],["MARKETING","discounts"],["PAYMENTS","provider"],["OPS","logging"],["PRODUCT","validation"],["NOTIFICATIONS","email channel"]].map(([a,b])=><div key={a}><span>{a}</span><p>changes {b}</p></div>)}</div><ConceptPressure><p>The class is not wrong merely because it is large. It is unstable because <b>unrelated sources of change converge on one implementation and one test fixture.</b></p></ConceptPressure><ResponsibilityPressureLab/></section>
<section className="lesson-section lesson-section--wide" id="definition"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · THE REAL PRINCIPLE" title="A module should have one coherent reason to change." copy="A reason often corresponds to a business capability, policy, stakeholder, or source of change. ‘One thing’ is too vague to guide a design."/></Reveal><div className="srp-definition"><blockquote>A responsibility is a coherent set of decisions that change together for the same source of pressure.</blockquote><div>{[["ACTOR","Who requests the change?"],["POLICY","Which business rule changed?"],["CAPABILITY","What stable outcome does this module own?"],["VOLATILITY","Which detail changes independently?"]].map(([a,b])=><p key={a}><b>{a}</b>{b}</p>)}</div></div><div className="cohesion-compare"><div><span>HIGH COHESION</span><h3>PricingPolicy</h3><code>calculateSubtotal()<br/>calculateTax()<br/>applyDiscount()</code><p>These decisions collaborate to produce a price and often share Finance/Marketing pressure.</p></div><div><span>LOWER COHESION</span><h3>OrderManager</h3><code>calculateTax()<br/>sendEmail()<br/>writeCSV()<br/>retryPayment()</code><p>The methods share a vague noun but respond to unrelated change sources.</p></div></div><ConceptPressure label="NUANCE"><p>CheckoutService may execute validate → price → reserve → pay → persist. If it contains only workflow decisions and delegates specialist policies, its responsibility is coherently <b>orchestrate checkout.</b></p></ConceptPressure></div></section>
<section className="lesson-section page-shell" id="refactor"><Reveal><SectionHeading eyebrow="03 · INTERACTIVE REFACTOR" title="Move policy, not every line." copy="Place each method beside the rules and change pressure it belongs to. Some methods stay together; the orchestrator remains responsible for ordering the workflow."/></Reveal><ResponsibilityRefactorLab/><div className="orchestrator-flow"><div><small>ORCHESTRATOR</small><b>CheckoutService</b></div>{["OrderValidator","PricingPolicy","InventoryService","PaymentProcessor","OrderRepository"].map(x=><span key={x}><i/> {x}</span>)}</div><h2 className="subsection-title">The opposite failure</h2><ClassExplosionLab/><div className="keep-together">{[["Money","add · subtract · multiply · compare","One value abstraction"],["Stack","push · pop · peek","One collection invariant"],["OrderValidator","identity · quantity · address rules","One product-validation policy"]].map(([name,methods,why])=><div key={name}><span>{name}</span><code>{methods}</code><p>{why}</p></div>)}</div></section>
<section className="lesson-section lesson-section--tint" id="change"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · CHANGE SIMULATOR" title="Measure where a requirement lands." copy="The same five requests repeatedly modify OrderService in the monolith. In the refactored model, each pressure has a focused landing zone."/></Reveal><BlastRadiusLab/><div className="signal-grid">{smells.map(([name,note])=><div key={name}><span>{name}</span><p>{note}</p></div>)}</div><p className="signal-note">These are diagnostic signals, not proof. A large generated parser may have one reason to change; a tiny process() function may contain five.</p></div></section>
<section className="lesson-section page-shell" id="testing"><Reveal><SectionHeading eyebrow="05 · TESTABILITY PRESSURE" title="A focused unit needs a focused fixture." copy="The monolith makes a tax test configure database, payment, email, inventory, analytics, and invoices. Separation lets each policy prove its rules without dragging in the workflow."/></Reveal><div className="testing-compare"><div><span>MONOLITH TEST</span><code>{`new OrderService(\n  fakeDb, fakePayment, fakeEmail,\n  fakeInventory, fakeAnalytics, fakeInvoice\n).place(order)`}</code><b>6 collaborators for a tax assertion</b></div><div><span>FOCUSED POLICY TEST</span><code>{`const price = new PricingPolicy(taxTable, discounts)\n  .price(order);\nexpect(price.tax).toEqual(money(18));`}</code><b>Only pricing rules are under test</b></div><div><span>ORCHESTRATOR TEST</span><code>{`const checkout = new CheckoutService(\n  validOrder, fixedPrice, reservedStock, paid, saved\n);\nexpect(checkout.place(draft)).toSucceed();`}</code><b>Small fakes verify sequence and failure handling</b></div></div><ConceptPressure label="TESTABILITY IS EVIDENCE"><p>Fewer dependencies often follow better responsibility boundaries. But code is not SRP-compliant merely because it is mockable; name the coherent reason to change.</p></ConceptPressure></section>
<section className="lesson-section lesson-section--wide" id="implementation"><div className="page-shell"><Reveal><SectionHeading eyebrow="06 · MULTI-LANGUAGE REFACTOR" title="Boundaries should fit the language." copy="Each example moves volatile policy behind focused collaborators while keeping CheckoutService as readable orchestration. None creates an interface for every class."/></Reveal><MultiLanguageCode examples={srpExamples}/><div className="language-grid"><LanguageReality language="Java">Interfaces are valuable at provider, persistence, and substitutable policy boundaries. Enterprise ceremony can over-abstract stable classes; constructor injection does not require an interface everywhere.</LanguageReality><LanguageReality language="Go">Prefer composition and small interfaces defined near the consumer. Free functions and concrete value policies can be clearer than recreating Java class layers.</LanguageReality><LanguageReality language="C++">Abstract interfaces help at runtime provider boundaries, but templates, values, function objects, and concrete references are valid when substitution is static or unnecessary.</LanguageReality><LanguageReality language="TypeScript">Structural interfaces make lightweight injected contracts possible. Keep runtime validation at trust boundaries because compile-time types do not validate external input.</LanguageReality></div><TradeoffPanel good={["Independent policies change at different rates","Tests require unrelated collaborators","A stable orchestration coordinates volatile workers"]} cost={["More files and dependency wiring","Local tracing crosses boundaries","Names and contracts require care"]} avoid={["No independent pressure has appeared","The split fragments one invariant","A plain cohesive type remains easy to change"]}/><div className="srp-scope"><span>SRP SCALES BEYOND CLASSES</span><p><b>Function:</b> one coherent transformation or effect.</p><p><b>Module/package:</b> related policy and vocabulary.</p><p><b>UI component:</b> one coherent presentation or interaction responsibility.</p><p><b>Service:</b> one business capability—without turning this lesson into distributed architecture.</p></div></div></section>
<section className="lesson-section lesson-section--tint" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="07 · REGISTRATION CHALLENGE" title="Separate policy while preserving the workflow." copy="UserRegistrationService validates, hashes, saves, welcomes, audits, assigns a trial, and tracks signup. Choose coherent boundaries rather than one class per line."/></Reveal><ClassificationChallenge title="USER REGISTRATION RESPONSIBILITIES" items={challenge} categories={["RegistrationOrchestrator","RegistrationPolicy","PasswordHasher","UserRepository","WelcomeNotifier","AnalyticsTracker"]}/><div className="challenge-pressure"><span>NEW REQUIREMENTS</span><p>Security raises the hash cost. Growth changes trial eligibility. Marketing adds WhatsApp. Compliance changes the audit schema.</p><b>Which module should each change touch—and which should remain untouched?</b></div></div></section>
<section className="lesson-section page-shell" id="interview"><Reveal><SectionHeading eyebrow="08 · INTERVIEW CHECKPOINT" title="Explain the change boundary." copy="Do not count methods. Name the actor or policy, show why its changes cohere, and acknowledge the cost of another abstraction."/></Reveal><InterviewCheckpoint questions={questions}/><h2 className="subsection-title">Common misconceptions</h2><CommonMistakes items={["One method per class.","One class per requirement.","A smaller class automatically follows SRP.","SRP forbids orchestration.","Every dependency needs an abstract interface.","SRP always reduces code.","Apply SRP before any change pressure exists."]}/><div className="answer-card"><span>60-SECOND INTERVIEW ANSWER</span><blockquote>The Single Responsibility Principle says a module should have one coherent reason to change. I identify that reason by looking at the business capability, actor, policy, and methods that change together. A CheckoutService can coordinate several steps without violating SRP if it owns only workflow while pricing, payment, persistence, and notification policies live behind focused boundaries. I avoid both god classes and class explosions; the split must reduce unrelated change and reasoning cost.</blockquote></div><RapidRevision items={[["Who changes this code?","identify actors and stakeholders"],["Why does it change?","name policy or capability pressure"],["Do changes belong together?","look for one coherent purpose"],["Can unrelated requirements modify it?","measure collision and blast radius"],["Is the responsibility cohesive?","methods and data should support one vocabulary"],["Would splitting help?","compare isolation benefit with navigation cost"]]}/><LessonPager previous={{number:"04",title:"Object Lifecycle & Ownership",href:"/learn/object-lifecycle-ownership"}} next={{number:"06",title:"Open/Closed Principle",copy:"Extend behavior without reopening stable code for every new case."}}/></section></article>}
