import type { Metadata } from "next";
import { MultiLanguageCode } from "@/components/code/multi-language-code";
import { ClassificationChallenge, GodObjectDemo, IdentityValueLab, ObjectBuilderLab, StateBehaviorLab } from "@/components/labs/design-labs";
import { ChapterNav, CommonMistakes, ConceptPressure, InterviewCheckpoint, LanguageReality, LessonHero, LessonPager, RapidRevision, TradeoffPanel } from "@/components/lesson/primitives";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { oopExamples } from "@/content/code-examples";
export const metadata:Metadata={title:"OOP Fundamentals",description:"Learn objects, identity, state, behavior, responsibilities, value objects, collaboration, and invariants from first principles."};
const toc=[["01","The scattered model","#start"],["02","Objects","#objects"],["03","State & behavior","#state"],["04","Identity & value","#identity"],["05","Invariants","#invariants"],["06","Implementation","#implementation"],["07","Challenge","#challenge"],["08","Interview","#interview"]] as const;
const questions=[
 {q:"What is the difference between a class and an object?",a:"A class is a definition of structure and behavior; an object is a runtime instance with its own state and, often, identity. Languages such as Go can model objects without classes."},
 {q:"Should every noun become a class?",a:"No. Nouns are discovery clues, not a design algorithm. Keep a type only when it owns meaningful rules, identity, a useful value, or a boundary."},
 {q:"What makes something an entity?",a:"Its continuity matters even while attributes change. Order 42 remains the same order after its status changes; identity, not attribute equality, determines sameness."},
 {q:"Why are value objects useful?",a:"They make invalid values harder to represent, put related rules beside the value, and compare by meaning. Money can carry amount, currency, rounding, and arithmetic rules together."},
 {q:"Where should business rules live?",a:"Near the state and responsibility they protect, unless a rule genuinely coordinates multiple objects or external capabilities. Domain services can own cross-object operations."},
 {q:"What is an invariant?",a:"A condition that must remain true for the model to be valid, such as quantity > 0 or a cancelled order never becoming delivered."},
 {q:"Why can an anemic domain model hurt?",a:"When objects only expose data, every caller must remember the rules. Logic spreads, mutation paths multiply, and invalid states become easier to create."},
 {q:"Can too many tiny objects hurt?",a:"Yes. Types with no meaningful rule or vocabulary increase navigation and indirection. An abstraction should pay rent by protecting a concept or isolating change."},
] as const;
const mistakes=["OOP means everything must be a class.","More classes automatically mean better design.","Data and behavior must always live together, regardless of context.","Inheritance is required for object-oriented design.","Objects should mirror database tables.","Every noun in a requirement becomes an object.","Getters and setters automatically create encapsulation."] as const;
const challenge=[{label:"Seat availability for a specific show",answer:"Show",hint:"Availability belongs to the show occurrence, not the movie title."},{label:"A booking identifier and its lifecycle",answer:"Booking",hint:"Booking has identity and owns its state transitions."},{label:"Amount plus currency",answer:"Money",hint:"Money is a value that should protect currency-aware arithmetic."},{label:"Reserve selected seats",answer:"Booking service",hint:"This operation coordinates Show, Seat, Customer, and Booking; a service boundary is reasonable."}] ;
export default function OopPage(){return <article className="lesson-page"><div className="page-shell"><LessonHero chapter="01" group="Object Thinking" title="Give behavior" accent="a place to live." deck="Start with scattered data and functions. Discover objects only when responsibility, identity, and invariants make them necessary." question="Where should each rule live so the model stays valid when requirements change?"/></div><ChapterNav chapter="01" items={toc}/>
<section className="lesson-section page-shell" id="start"><Reveal><SectionHeading eyebrow="01 · COLD OPEN" title="A food order begins as loose data." copy="A customer chooses items, a cart stores selections and calculates a total, and an order moves through a lifecycle. The first implementation uses maps, arrays, and functions operating on everything."/></Reveal><div className="scenario-grid"><div className="requirements-card"><span>INITIAL REQUIREMENTS</span>{["Customer chooses menu items","Cart stores selections","Cart calculates total","Customer places order","Order has status"].map(x=><p key={x}>✓ {x}</p>)}</div><pre className="naive-code"><code>{`customer = { id, name }\ncart = { customerId, items: [] }\norder = { status: "DRAFT" }\n\naddItem(cart, item, quantity)\ncalculateTotal(cart)\nplaceOrder(customer, cart)\nchangeOrderStatus(order, next)`}</code></pre></div><ConceptPressure><p><b>Who owns the cart rules?</b> Who prevents an invalid quantity? Who controls order state? When every function can mutate every map, the rule belongs to everyone—and therefore no one.</p></ConceptPressure></section>
<section className="lesson-section lesson-section--wide" id="objects"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · OBJECT THINKING" title="An object owns a meaningful responsibility." copy="An object is a runtime participant with state, behavior, and a reason to exist in the domain. A class can define objects, but object-oriented design begins with responsibilities—not syntax."/></Reveal><div className="definition-grid"><div><span>OBJECT</span><h3>A responsible participant</h3><p>Combines what it knows with operations that preserve its rules.</p></div><div><span>INSTANCE</span><h3>One runtime occurrence</h3><p>cartA and cartB follow the same definition but hold different state.</p></div><div><span>COLLABORATION</span><h3>Objects doing work together</h3><p>Cart supplies lines; Order captures a purchase; Payment executes a capability.</p></div><div><span>RESPONSIBILITY</span><h3>A focused reason to change</h3><p>“Calculate this cart&apos;s total” is clearer than “do food app things.”</p></div></div><Reveal delay={.08}><ObjectBuilderLab/></Reveal></div></section>
<section className="lesson-section page-shell" id="state"><Reveal><SectionHeading eyebrow="03 · STATE & BEHAVIOR" title="Behavior exists to protect meaning." copy="State is what an object knows. Behavior is what it can do. Useful behavior does more than move data: it prevents the object from entering a state the domain considers impossible."/></Reveal><StateBehaviorLab/><div className="mental-model"><div><small>STATE</small><b>quantity = 2</b><p>A fact at this moment.</p></div><span>protected by</span><div><small>BEHAVIOR</small><b>changeQuantity(3)</b><p>An operation that can reject zero or negative values.</p></div></div></section>
<section className="lesson-section lesson-section--tint" id="identity"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · IDENTITY VS VALUE" title="Sameness depends on what the domain cares about." copy="Entities continue through time and change. Value objects are defined by their attributes and are often immutable. The same noun can be modeled differently in a different domain."/></Reveal><IdentityValueLab/><div className="entity-value-grid"><div><span>ENTITY</span><h3>Customer · Order · Cart</h3><p>Identity answers “is this the same one?” Attribute changes do not create a new entity.</p></div><div><span>VALUE OBJECT</span><h3>Money · Coordinates · DateRange</h3><p>Equality answers “do these mean the same thing?” Replacement is usually safer than mutation.</p></div></div></div></section>
<section className="lesson-section page-shell" id="invariants"><Reveal><SectionHeading eyebrow="05 · INVARIANTS" title="Make invalid states difficult to represent." copy="An invariant is a condition that must remain true before and after every public operation. Constructors and named methods form the boundary where the model can defend itself."/></Reveal><div className="invariant-grid">{[["CartItem","quantity > 0","Reject creation or quantity changes that violate it."],["Money","amount ≥ 0 for a menu price","Validate once instead of trusting every calculation."],["Order","CANCELLED ↛ DELIVERED","Expose legal transitions, not an arbitrary status setter."],["Cart","no invalid product quantity","Keep the item collection behind meaningful operations."]].map(([name,rule,guard])=><div key={name}><span>{name}</span><code>{rule}</code><p>{guard}</p></div>)}</div><ConceptPressure label="WHY NOW?"><p>Rules repeated across callers drift. One new import script or controller can bypass them. The object becomes useful when it centralizes the valid transitions.</p></ConceptPressure></section>
<section className="lesson-section lesson-section--wide"><div className="page-shell"><Reveal><SectionHeading eyebrow="GOD OBJECT DEMO" title="One owner can own far too much." copy="Putting behavior with data does not justify putting all behavior in one class. Watch responsibility, mutation, dependency, and test surfaces change."/></Reveal><GodObjectDemo/></div></section>
<section className="lesson-section page-shell" id="implementation"><Reveal><SectionHeading eyebrow="06 · MULTI-LANGUAGE MODEL" title="The idea survives different object systems." copy="Each implementation models Money, CartItem, and Cart with the language&apos;s natural tools. The common idea is protected invariants and cohesive behavior—not identical syntax."/></Reveal><MultiLanguageCode examples={oopExamples}/><div className="language-grid"><LanguageReality language="C++">Ownership and value/reference semantics are part of the design. RAII and smart pointers become central in Chapter 34.</LanguageReality><LanguageReality language="Go">Go has structs, methods, interfaces, and composition—but no classes or class inheritance. Object thinking does not require class syntax.</LanguageReality><LanguageReality language="Java">Records suit compact values; classes with private state and domain methods suit entities and aggregates.</LanguageReality><LanguageReality language="TypeScript">Runtime JavaScript is prototype-based. TypeScript adds static structure, but validation must still happen at runtime.</LanguageReality></div><TradeoffPanel good={["Rules belong near the state they protect","A concept has identity or value semantics","Callers need a stable domain vocabulary"]} cost={["More types and navigation","Object boundaries require judgment","Persistence mapping may differ from domain shape"]} avoid={["Pure transformations are clearer as functions","A type carries no rule or meaning","Indirection exceeds the change pressure"]}/></section>
<section className="lesson-section lesson-section--tint" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="07 · MINI CHALLENGE" title="Model a movie ticket booking domain." copy="Classify each responsibility. More than one design can work; use the feedback to identify the domain fact that should drive your decision."/></Reveal><ClassificationChallenge title="MOVIE BOOKING MODEL" items={challenge} categories={["Movie","Show","Seat","Booking","Customer","Money","Booking service"]}/></div></section>
<section className="lesson-section page-shell" id="interview"><Reveal><SectionHeading eyebrow="08 · INTERVIEW CHECKPOINT" title="Defend the model, not the vocabulary." copy="Reveal only after committing to an answer. Interviewers test whether you can qualify principles instead of reciting them."/></Reveal><InterviewCheckpoint questions={questions}/><h2 className="subsection-title">Common misconceptions</h2><CommonMistakes items={mistakes}/><div className="answer-card"><span>60-SECOND INTERVIEW ANSWER</span><blockquote>Object-oriented design organizes software around collaborating participants that own state, behavior, and rules. I use objects when identity, lifecycle, or invariants matter, and value objects when meaning comes from attributes. The goal is not more classes—it is to put responsibility behind APIs that make valid change easy and invalid change difficult. I still use functions and data-oriented designs where they are clearer.</blockquote></div><RapidRevision items={[["Object","runtime participant with responsibility"],["Class","one way to define object structure and behavior"],["Entity","continuity through identity"],["Value object","meaning through attributes"],["Invariant","condition that must remain true"],["Collaboration","focused objects accomplishing work together"]]}/><LessonPager next={{number:"02",title:"Encapsulation & Abstraction",href:"/learn/encapsulation-abstraction",copy:"Control mutation, hide irrelevant detail, and design meaningful public APIs."}}/></section></article>}
