"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const storage=[
  ["ImageGallery","read","—","—","—"],
  ["BackupJob","read","write","delete","—"],
  ["AuditViewer","read","—","—","list"],
] as const;
export function FatInterfaceLab(){const[split,setSplit]=useState(false);return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={split?"live-dot":"alert-dot"}/> FAT INTERFACE LAB</div><span>{split?"CLIENT-OWNED CAPABILITIES":"STORAGE EVERYTHING"}</span></div><div className="interface-matrix"><div><b>CLIENT</b><b>READ</b><b>WRITE</b><b>DELETE</b><b>LIST</b></div>{storage.map(row=><div key={row[0]}>{row.map((cell,i)=><span className={i>0&&cell==="—"?"unused":""} key={i}>{cell}</span>)}</div>)}</div><div className={`lab-feedback ${split?"success":"error"}`} aria-live="polite"><b>{split?"FOCUSED PORTS: Reader · Writer · Deleter · Lister":"EVERY CLIENT DEPENDS ON FOUR REASONS TO CHANGE"}</b><p>{split?"Each workflow requests only what it uses. A read-only adapter can now tell the truth without throwing unsupported errors.":"Adding multipart upload recompiles and retests clients that only read. The interface belongs to its consumers, not to a provider catalogue."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setSplit(v=>!v)}>{split?<Rotate/>:<ArrowRight/>}{split?"RESTORE FAT INTERFACE":"SEGREGATE BY CLIENT"}</button></div>}

export function DependencyDirectionGraph(){const[inverted,setInverted]=useState(false);return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={inverted?"live-dot":"alert-dot"}/> DEPENDENCY DIRECTION</div><span>{inverted?"POLICY OWNS PORT":"DETAIL OWNS POLICY"}</span></div><div className={`dependency-direction ${inverted?"inverted":""}`}><div><small>HIGH-LEVEL POLICY</small><b>CheckoutService</b></div><i>→</i><div><small>{inverted?"APPLICATION PORT":"CONCRETE SDK"}</small><b>{inverted?"PaymentProcessor":"StripeClient"}</b></div><i>←</i><div><small>LOW-LEVEL DETAIL</small><b>StripeAdapter</b></div></div><div className={`lab-feedback ${inverted?"success":"error"}`} aria-live="polite"><b>{inverted?"SOURCE DEPENDENCIES POINT INWARD":"BUSINESS FLOW IMPORTS A VOLATILE DETAIL"}</b><p>{inverted?"Checkout defines the capability it needs. Stripe implements that port and composition supplies the adapter.":"Provider method names, exceptions, and lifecycle now leak through the use case."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setInverted(v=>!v)}>{inverted?<Rotate/>:<ArrowRight/>}{inverted?"SHOW CONCRETE COUPLING":"INVERT THE DEPENDENCY"}</button></div>}

const responsibilities=["validate order","calculate price","reserve stock","charge payment","save order","send email","export CSV"];
export function CohesionResponsibilityLab(){const[split,setSplit]=useState(false);return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={split?"live-dot":"alert-dot"}/> COHESION RESPONSIBILITY LAB</div><span>{split?"COHERENT CLUSTERS":"ORDER MANAGER"}</span></div><div className={`responsibility-clusters ${split?"split":""}`}>{responsibilities.map((x,i)=><div key={x}><small>{split?["ORDER","PRICING","INVENTORY","PAYMENT","ORDER","NOTIFY","REPORTING"][i]:"ORDER MANAGER"}</small><b>{x}</b></div>)}</div><div className={`lab-feedback ${split?"success":"error"}`} aria-live="polite"><b>{split?"RELATED DATA AND BEHAVIOR CHANGE TOGETHER":"SEVEN VOCABULARIES COLLIDE"}</b><p>{split?"The checkout use case may still orchestrate them; cohesion does not forbid coordination.":"Payment, reporting, inventory, and messaging teams all reopen the same type."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setSplit(v=>!v)}>{split?<Rotate/>:<ArrowRight/>}{split?"MERGE RESPONSIBILITIES":"GROUP BY PURPOSE"}</button></div>}

const changes=[
  ["Add tax jurisdiction",[3,2,0,0,0,0]],
  ["Change email provider",[0,0,0,0,3,1]],
  ["Add CSV column",[0,0,0,0,0,3]],
  ["Retry payment",[0,0,0,3,0,0]],
] as const;
export function ChangePropagationHeatmap(){const[selected,setSelected]=useState(0);const modules=["Order","Pricing","Stock","Payment","Notify","Report"];return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> CHANGE PROPAGATION HEATMAP</div><span>SELECT A CHANGE</span></div><div className="heatmap-layout"><div className="heatmap-changes">{changes.map(([name],i)=><button type="button" aria-pressed={selected===i} onClick={()=>setSelected(i)} key={name}>{name}</button>)}</div><div className="heatmap-grid" aria-live="polite">{modules.map((m,i)=><div className={`heat-${changes[selected][1][i]}`} key={m}><small>{m}</small><b>{changes[selected][1][i]===3?"DIRECT":changes[selected][1][i]===2?"RIPPLE":changes[selected][1][i]===1?"TEST":"—"}</b></div>)}</div></div><p className="lab-caption">High cohesion localizes the hot cell. Low coupling keeps the rest of the map cool; zero coupling is neither possible nor desirable.</p></div>}
