"use client";
import { useState } from "react";
const Metric=({label,value}:{label:string;value:string|number})=><div><span>{label}</span><b>{value}</b></div>;

export function RaiiScopeLab(){const[raii,setRaii]=useState(true);const[exit,setExit]=useState<"NORMAL"|"EARLY RETURN"|"EXCEPTION">("NORMAL");const timeline=raii?["ENTER SCOPE","ACQUIRE FILE","ACQUIRE LOCK","WORK",exit,"DESTROY LOCK","DESTROY FILE"]:["ENTER","OPEN FILE","LOCK","WORK",exit,...(exit==="NORMAL"?["UNLOCK","CLOSE"]:[])];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={raii?"live-dot":"alert-dot"}/> RAII SCOPE CLEANUP</div><button type="button" className="mode-button" aria-pressed={raii} onClick={()=>setRaii(!raii)}>{raii?"RAII OWNERS":"MANUAL CLEANUP"}</button></div><div className="runtime-actions">{(["NORMAL","EARLY RETURN","EXCEPTION"] as const).map(x=><button type="button" aria-pressed={exit===x} onClick={()=>setExit(x)} key={x}>{x}</button>)}</div><div className="lifetime-track">{timeline.map((x,i)=><span className={x.startsWith("DESTROY")||x==="UNLOCK"||x==="CLOSE"?"release":""} key={`${x}${i}`}>{i+1}. {x}</span>)}</div><div className="metric-strip"><Metric label="LEAK RISK" value={!raii&&exit!=="NORMAL"?"HIGH":"LOW"}/><Metric label="MANUAL CLEANUP PATHS" value={raii?0:3}/><Metric label="UNWIND SAFE" value={raii?"YES":"NO"}/><Metric label="RELEASE ORDER" value="REVERSE"/></div></div>}

type Edge="unique"|"shared"|"borrowed"|"weak";const ownershipTargets:Record<string,Edge>={"Application → Repository":"unique","Repository → Cache":"unique","Request → Session":"borrowed","Cache → User":"shared","User → Session":"weak"};
export function OwnershipGraphLab(){const[answers,setAnswers]=useState<Record<string,Edge>>({});const[focus,setFocus]=useState(Object.keys(ownershipTargets)[0]);const score=Object.entries(ownershipTargets).filter(([k,v])=>answers[k]===v).length;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={score===5?"live-dot":"alert-dot"}/> OWNERSHIP / SMART POINTER GRAPH</div><span>{score}/5 REASONED</span></div><div className="ownership-graph">{Object.keys(ownershipTargets).map(x=><button type="button" aria-pressed={focus===x} onClick={()=>setFocus(x)} key={x}><b>{x}</b><small>{answers[x]??"UNASSIGNED"}</small></button>)}</div><div className="runtime-actions">{(["unique","shared","borrowed","weak"] as Edge[]).map(x=><button type="button" aria-pressed={answers[focus]===x} onClick={()=>setAnswers({...answers,[focus]:x})} key={x}>{x.toUpperCase()}</button>)}</div><p className="lab-caption">Prefer the narrowest ownership semantics. A raw pointer/reference can express borrowing; it does not extend lifetime.</p></div>}

export function SharedCycleLab(){const[weak,setWeak]=useState(false);const[parent,setParent]=useState(true);const[child,setChild]=useState(true);const external=(parent?1:0)+(child?1:0);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={weak?"live-dot":"alert-dot"}/> shared_ptr CYCLE + weak_ptr</div><button type="button" className="mode-button" aria-pressed={weak} onClick={()=>setWeak(!weak)}>{weak?"CHILD weak_ptr PARENT":"BOTH shared_ptr"}</button></div><div className="pointer-cycle"><div><b>PARENT</b><span>{parent?"EXTERNAL OWNER":"EXTERNAL DROPPED"}</span></div><i>shared → CHILD<br/>{weak?"weak":"shared"} ←</i><div><b>CHILD</b><span>{child?"EXTERNAL OWNER":"EXTERNAL DROPPED"}</span></div></div><div className="runtime-actions"><button type="button" onClick={()=>setParent(false)}>DROP EXTERNAL PARENT</button><button type="button" onClick={()=>setChild(false)}>DROP EXTERNAL CHILD</button><button type="button" onClick={()=>{setParent(true);setChild(true)}}>RESET</button></div><div className="metric-strip"><Metric label="EXTERNAL OWNERS" value={external}/><Metric label="BACK EDGE" value={weak?"WEAK":"STRONG"}/><Metric label="CYCLE OWNERS" value={!weak?2:0}/><Metric label="AFTER FINAL DROP" value={!external?weak?"DESTROY":"RETAINED":"ALIVE"}/></div><div className={`lab-feedback ${!parent&&!child&&!weak?"error":"success"}`}><b>{!parent&&!child?weak?"CYCLE BROKEN · OBJECTS DESTROY":"STRONG CYCLE · COUNTS NEVER REACH ZERO":"OWNERS ACTIVE"}</b><p>weak_ptr observes a shared lifetime without increasing the strong count; lock() attempts to obtain a valid owner.</p></div></div>}

export function CopyMoveLab(){const[mode,setMode]=useState<"COPY"|"MOVE">("COPY");return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={mode==="MOVE"?"live-dot":"alert-dot"}/> COPY VS MOVE</div><button type="button" className="mode-button" aria-pressed={mode==="MOVE"} onClick={()=>setMode(mode==="COPY"?"MOVE":"COPY")}>{mode}</button></div><div className="move-canvas"><div><b>SOURCE BUFFER</b><span>{mode==="COPY"?"owns buffer A":"valid, unspecified"}</span></div><i>{mode==="COPY"?"allocate + copy 1M elements":"transfer pointer / size / capacity"}</i><div><b>DESTINATION</b><span>{mode==="COPY"?"owns buffer B":"owns buffer A"}</span></div></div><div className="metric-strip"><Metric label="ALLOCATIONS" value={mode==="COPY"?1:0}/><Metric label="ELEMENT COPIES" value={mode==="COPY"?"1,000,000":0}/><Metric label="OWNERSHIP TRANSFERS" value={mode==="MOVE"?1:0}/><Metric label="SOURCE" value={mode==="COPY"?"UNCHANGED":"VALID / UNSPECIFIED"}/></div></div>}

export function OwnershipTransferLab(){const[owner,setOwner]=useState<"A"|"B">("A");const[message,setMessage]=useState("A exclusively owns Order");return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> unique_ptr OWNERSHIP TRANSFER</div><span>OWNER {owner}</span></div><div className="pointer-cycle"><div><b>A</b><span>{owner==="A"?"unique_ptr<Order>":"empty"}</span></div><i>ONE OWNERSHIP ARROW</i><div><b>B</b><span>{owner==="B"?"unique_ptr<Order>":"empty"}</span></div></div><div className="runtime-actions"><button type="button" onClick={()=>setMessage("COPY REJECTED: unique_ptr is move-only")}>TRY COPY TO B</button><button type="button" onClick={()=>{setOwner("B");setMessage("std::move enables B's move operation; A no longer owns")}}>MOVE TO B</button><button type="button" onClick={()=>{setOwner("A");setMessage("A exclusively owns Order")}}>RESET</button></div><div className="lab-feedback success" aria-live="polite"><b>{message}</b><p>std::move itself moves no bytes; it permits a move constructor or assignment to transfer the resource.</p></div></div>}

export function CopyElisionLab(){const[mode,setMode]=useState<"COPY"|"MOVE"|"ELISION">("COPY");const items={COPY:["construct local","allocate destination","copy","destroy local"],MOVE:["construct local","move resource","destroy source"],ELISION:["construct directly in destination"]}[mode];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={mode==="ELISION"?"live-dot":"alert-dot"}/> RETURN-BY-VALUE TIMELINE</div><span>{mode}</span></div><div className="runtime-actions">{(["COPY","MOVE","ELISION"] as const).map(x=><button type="button" aria-pressed={mode===x} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><div className="lifetime-track">{items.map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div><div className="metric-strip"><Metric label="COPIES" value={mode==="COPY"?1:0}/><Metric label="MOVES" value={mode==="MOVE"?1:0}/><Metric label="OBJECT CONSTRUCTIONS" value={mode==="COPY"?2:1}/><Metric label="NOTE" value={mode==="ELISION"?"DIRECT":"MODEL"}/></div></div>}

export function VirtualDispatchLab(){const[type,setType]=useState<"Stripe"|"UPI"|"Fake">("Stripe");const[virtual,setVirtual]=useState(true);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> VIRTUAL DISPATCH · COMMON MODEL</div><button type="button" className="mode-button" aria-pressed={virtual} onClick={()=>setVirtual(!virtual)}>{virtual?"VIRTUAL CALL":"STATIC CALL"}</button></div><div className="runtime-actions">{(["Stripe","UPI","Fake"] as const).map(x=><button type="button" aria-pressed={type===x} onClick={()=>setType(x)} key={x}>{x}Processor</button>)}</div><div className="dispatch-view"><b>PaymentProcessor*</b><i>{virtual?"object → vptr → conceptual table":"compile-time target"}</i><div><span>~PaymentProcessor</span><strong>pay → {virtual?type:"PaymentProcessor"}::pay</strong><span>refund → {type}::refund</span></div></div><p className="lab-caption">vptr/vtable is a common implementation technique, not a standard-mandated exact layout. Optimization may devirtualize an apparently virtual call.</p></div>}

export function VirtualDestructorLab(){const[virtual,setVirtual]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={virtual?"live-dot":"alert-dot"}/> POLYMORPHIC DESTRUCTION</div><button type="button" className="mode-button" aria-pressed={virtual} onClick={()=>setVirtual(!virtual)}>{virtual?"VIRTUAL BASE DESTRUCTOR":"NON-VIRTUAL BASE DESTRUCTOR"}</button></div><div className="lifetime-track"><span>unique_ptr&lt;Base&gt;</span><span>owns Derived</span><span>owner leaves scope</span>{virtual?<><span className="release">~Derived()</span><span className="release">~Base()</span></>:<span>deletion through base is undefined behavior</span>}</div><div className={`lab-feedback ${virtual?"success":"error"}`}><b>{virtual?"COMPLETE DESTRUCTION CHAIN":"POLYMORPHIC DELETE CONTRACT BROKEN"}</b><p>A base intended for deletion through a base pointer needs a suitable virtual destructor.</p></div></div>}

export function ObjectSlicingLab(){const[reference,setReference]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={reference?"live-dot":"alert-dot"}/> OBJECT SLICING</div><button type="button" className="mode-button" aria-pressed={reference} onClick={()=>setReference(!reference)}>{reference?"const Base&":"Base BY VALUE"}</button></div><div className="object-layout"><div><b>Derived</b><span>Base subobject</span><strong>radius · Circle::draw</strong></div><i>{reference?"borrow identity":"copy Base subobject only"}</i><div><b>{reference?"Base reference":"new Base object"}</b><span>Base fields</span><strong>{reference?"dynamic type remains Circle":"derived state sliced"}</strong></div></div><div className={`lab-feedback ${reference?"success":"error"}`}><b>{reference?"POLYMORPHISM PRESERVED":"OBJECT SLICED"}</b><p>Passing or storing a polymorphic base by value creates a base object. Use references or owning pointers when dynamic identity must remain.</p></div></div>}

export function PolymorphismChoiceLab(){const[need,setNeed]=useState<"PLUGIN"|"CLOSED"|"PIPELINE">("PLUGIN");const answer={PLUGIN:"VIRTUAL INTERFACE",CLOSED:"std::variant + visit",PIPELINE:"TEMPLATE / STATIC"}[need];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> POLYMORPHISM CHOICE</div><span>Shape · Circle · Rectangle</span></div><div className="runtime-actions">{(["PLUGIN","CLOSED","PIPELINE"] as const).map(x=><button type="button" aria-pressed={need===x} onClick={()=>setNeed(x)} key={x}>{x}</button>)}</div><div className="lab-feedback success"><b>{answer}</b><p>{need==="PLUGIN"?"Open runtime extension favors a stable virtual contract.":need==="CLOSED"?"A finite known family can make alternatives exhaustive.":"Compile-time composition can expose targets to optimization when runtime extension is unnecessary."}</p></div></div>}

export function ThreadSafeClassLab(){const[mode,setMode]=useState<"NONE"|"METHOD LOCKS"|"ATOMIC API">("NONE");const safe=mode==="ATOMIC API";return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={safe?"live-dot":"alert-dot"}/> THREAD-SAFE INVENTORY CONTRACT</div><span>{mode}</span></div><div className="runtime-actions">{(["NONE","METHOD LOCKS","ATOMIC API"] as const).map(x=><button type="button" aria-pressed={mode===x} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><div className="thread-contract"><div><b>THREAD A</b><span>{mode==="ATOMIC API"?"tryReserve(1)":"available(); reserve()"}</span></div><div><b>SHARED INVARIANT</b><span>inventory ≥ 0</span></div><div><b>THREAD B</b><span>{mode==="ATOMIC API"?"tryReserve(1)":"available(); reserve()"}</span></div></div><div className={`lab-feedback ${safe?"success":"error"}`}><b>{safe?"ONE DOMAIN OPERATION / ONE LINEARIZATION POINT":mode==="METHOD LOCKS"?"METHODS SAFE · WORKFLOW STILL RACES":"C++ DATA RACE"}</b><p>Lock the invariant, not every method blindly. A thread-safe API makes the complete check-and-act operation indivisible.</p></div></div>}

export function CheckThenActLab(){const[step,setStep]=useState(0);const steps=["A checks available = 1","B checks available = 1","A reserves","B reserves → invariant broken"];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={step===4?"alert-dot":"live-dot"}/> CHECK-THEN-ACT RACE</div><button type="button" className="mode-button" onClick={()=>setStep(0)}>RESET</button></div><div className="lifetime-track">{steps.map((x,i)=><span className={i<step?"release":""} key={x}>{i+1}. {x}</span>)}</div><div className="runtime-actions"><button type="button" disabled={step===4} onClick={()=>setStep(v=>v+1)}>RUN NEXT INTERLEAVING</button></div><p className="lab-caption">Individually locked available() and reserve() calls leave an unlocked gap. Replace the sequence with tryReserve(quantity).</p></div>}

export function AtomicInvariantLab(){const[mutex,setMutex]=useState(false);const[x,setX]=useState(50);const[y,setY]=useState(50);const transfer=()=>mutex?(setX(v=>v-10),setY(v=>v+10)):(setX(v=>v-10));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={x+y===100?"live-dot":"alert-dot"}/> ATOMIC FIELDS VS ONE INVARIANT</div><button type="button" className="mode-button" aria-pressed={mutex} onClick={()=>{setMutex(!mutex);setX(50);setY(50)}}>{mutex?"MUTEX SNAPSHOT":"TWO ATOMICS"}</button></div><div className="runtime-actions"><button type="button" onClick={transfer}>TRANSFER 10 FROM X TO Y</button><button type="button" onClick={()=>{setX(50);setY(50)}}>RESET</button></div><div className="metric-strip"><Metric label="X" value={x}/><Metric label="Y" value={y}/><Metric label="X + Y" value={x+y}/><Metric label="INVARIANT" value={x+y===100?"HOLDS":"TORN VIEW"}/></div></div>}

export function ThreadSafeObserverLab(){const[snapshot,setSnapshot]=useState(false);const[count,setCount]=useState(3);const[publishing,setPublishing]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={snapshot?"live-dot":"alert-dot"}/> THREAD-SAFE OBSERVER</div><button type="button" className="mode-button" aria-pressed={snapshot} onClick={()=>setSnapshot(!snapshot)}>{snapshot?"COPY-OUT CALLBACKS":"CALL UNDER LOCK"}</button></div><div className="runtime-actions"><button type="button" onClick={()=>setCount(v=>v+1)}>SUBSCRIBE</button><button type="button" disabled={count===0} onClick={()=>setCount(v=>v-1)}>UNSUBSCRIBE</button><button type="button" onClick={()=>setPublishing(!publishing)}>PUBLISH</button></div><div className="thread-contract"><div><b>LOCK</b><span>{snapshot?"copy subscriber list":"held during callbacks"}</span></div><div><b>{count} OBSERVERS</b><span>{publishing?"notifying":"idle"}</span></div><div><b>RISK</b><span>{snapshot?"stale snapshot policy":"re-entry / deadlock"}</span></div></div></div>}

const phases=["REQUIREMENTS","MODEL","API","IMPLEMENTATION","EDGE CASES","EXTENSIONS"] as const;
export function MachineCodingWorkbench(){const[phase,setPhase]=useState(0);const[choices,setChoices]=useState<Record<string,string>>({});const prompts:Record<string,string[]>={REQUIREMENTS:["park + exit","payment too","reservation too"],MODEL:["Vehicle / Spot / Ticket","ParkingManager only","database tables"],API:["park(vehicle), exit(ticket)","getters + setters","one execute()"],IMPLEMENTATION:["walking skeleton","all patterns first","database first"],"EDGE CASES":["no spot / bad ticket","later","exceptions everywhere"],EXTENSIONS:["pricing + selection policies","abstract everything","rewrite core"]};const name=phases[phase];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> MACHINE CODING PLANNING WORKBENCH</div><span>{phase+1}/6 · {name}</span></div><div className="interview-phases">{phases.map((x,i)=><button type="button" aria-pressed={i===phase} onClick={()=>setPhase(i)} key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><small>{choices[x]??"PENDING"}</small></button>)}</div><div className="runtime-actions">{prompts[name].map(x=><button type="button" aria-pressed={choices[name]===x} onClick={()=>setChoices({...choices,[name]:x})} key={x}>{x}</button>)}<button type="button" disabled={phase===5} onClick={()=>setPhase(v=>v+1)}>NEXT PHASE</button></div><div className="metric-strip"><Metric label="DECISIONS" value={Object.keys(choices).length}/><Metric label="SIMULATED MIN" value={[10,20,30,55,70,80][phase]}/><Metric label="SCOPE" value={choices.REQUIREMENTS??"CLARIFY"}/><Metric label="RUNNABLE PATH" value={choices.IMPLEMENTATION==="walking skeleton"?"YES":"NOT YET"}/></div></div>}

export function RequirementPressureLab(){const[requirements,setRequirements]=useState<string[]>([]);const all=["new vehicle type","new pricing rule","new allocation rule","multiple floors","concurrent entry"];const toggle=(x:string)=>setRequirements(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);const modules=new Set(requirements.map(x=>x.includes("pricing")?"PricingPolicy":x.includes("allocation")||x.includes("vehicle")?"SpotSelectionPolicy":x.includes("concurrent")?"Reservation boundary":"ParkingLot/Floor"));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> REQUIREMENT PRESSURE SIMULATOR</div><span>{requirements.length} CHANGES</span></div><div className="runtime-actions">{all.map(x=><button type="button" aria-pressed={requirements.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><div className="change-locality"><div><b>PRESSURE</b>{requirements.map(x=><span key={x}>{x}</span>)}</div><i>changes →</i><div><b>LOCAL MODULES</b>{[...modules].map(x=><span key={x}>{x}</span>)}</div></div><p className="lab-caption">Add an abstraction only when a requirement creates a real axis of change. Sequential scope does not need synchronization; one pricing rule does not need a strategy family.</p></div>}

export function InterviewSimulationLab(){const[phase,setPhase]=useState(0);const[elapsed,setElapsed]=useState(0);const advance=()=>{if(phase<5){setPhase(v=>v+1);setElapsed(v=>v+[10,10,35,15,10,10][phase])}};return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={phase===5?"live-dot":"alert-dot"}/> 90-MINUTE PARKING LOT SIMULATION</div><span>{elapsed}/90 MIN</span></div><div className="interview-phases">{phases.map((x,i)=><div className={i<phase?"done":i===phase?"active":""} key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><small>{i<phase?"COMPLETE":i===phase?"ACTIVE":"WAITING"}</small></div>)}</div><div className="runtime-actions"><button type="button" disabled={phase===5} onClick={advance}>COMPLETE PHASE + ADVANCE</button><button type="button" onClick={()=>{setPhase(0);setElapsed(0)}}>RESET</button></div><div className="lab-feedback success"><b>{phase===5?"DEMO, THEN DEFEND TRADE-OFFS":`CURRENT: ${phases[phase]}`}</b><p>The clock is illustrative, not universal. Protect time for a runnable happy path, edge cases, tests, and an explicit demo.</p></div></div>}
