"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

export function HierarchyExplosionLab(){const[composed,setComposed]=useState(false);const variants=composed?["Drive","Fly","Float","Armor"]:["Car","BoatCar","FlyingCar","ArmoredCar","FlyingBoatCar","ArmoredFlyingCar","ArmoredFlyingBoatCar"];return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={composed?"live-dot":"alert-dot"}/> HIERARCHY EXPLOSION</div><span>{composed?"4 CAPABILITIES":"7 SUBCLASSES"}</span></div><div className={`hierarchy-cloud ${composed?"composed":""}`}>{variants.map((x,i)=><span key={x} style={{opacity:1-i*.06}}>{x}</span>)}</div><div className={`lab-feedback ${composed?"success":"error"}`} aria-live="polite"><b>{composed?"SELECT CAPABILITIES AT COMPOSITION TIME":"COMBINATIONS BECOME TYPES"}</b><p>{composed?"Vehicle delegates to movement and equipment objects; each axis can vary independently.":"The eighth capability doubles the conceptual combinations and forces awkward intermediate parents."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setComposed(v=>!v)}>{composed?<Rotate/>:<ArrowRight/>}{composed?"RESTORE HIERARCHY":"COMPOSE CAPABILITIES"}</button></div>}

export function CompositionComparison(){const[mode,setMode]=useState<"inheritance"|"composition">("inheritance");const composition=mode==="composition";return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={composition?"live-dot":"alert-dot"}/> DESIGN COMPARISON</div><div className="lab-switch"><button type="button" aria-pressed={!composition} onClick={()=>setMode("inheritance")}>INHERITANCE</button><button type="button" aria-pressed={composition} onClick={()=>setMode("composition")}>COMPOSITION</button></div></div><div className="comparison-score" aria-live="polite">{[["Runtime swap",composition],["Protected-state risk",composition],["True is-a semantics",!composition],["Framework hook",!composition]].map(([label,win])=><div key={String(label)}><span>{label}</span><b className={win?"good":"muted"}>{win?"STRONG":"WEAK"}</b></div>)}</div><p className="lab-caption">Prefer composition for independent, replaceable behavior. Prefer inheritance when the taxonomy is stable, substitution is honest, and shared lifecycle semantics matter.</p></div>}

const apiIssues=[
  ["process(user, true, false, null)","Mystery booleans and nullable positionals hide intent."],
  ["reserve(seatId): boolean","A false result cannot explain conflict, expiry, or authorization."],
  ["setStatus(\"PAID\")","A generic setter bypasses the transition and payment evidence."],
  ["getUsers(): User[]","The caller may mutate internal collection state."],
] as const;
export function ApiReviewLab(){const[index,setIndex]=useState(0);const[reviewed,setReviewed]=useState(false);return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={reviewed?"live-dot":"alert-dot"}/> API REVIEW LAB</div><span>{index+1} / {apiIssues.length}</span></div><div className="api-review"><code>{apiIssues[index][0]}</code><p aria-live="polite">{reviewed?apiIssues[index][1]:"Inspect naming, parameters, return value, errors, ownership, and legal state transitions."}</p></div><div className="lab-actions"><button className="lab-button" type="button" onClick={()=>setReviewed(true)}>REVEAL REVIEW</button><button className="lab-button" type="button" onClick={()=>{setIndex((index+1)%apiIssues.length);setReviewed(false)}}>NEXT API <ArrowRight/></button></div></div>}

const invalid=["end before start","seat count = 0","currency missing","confirmed without payment"];
export function InvalidStateSimulator(){const[builder,setBuilder]=useState(false);const[attempt,setAttempt]=useState(0);return <div className="boundary-lab lab-panel"><div className="lab-toolbar"><div><span className={builder?"live-dot":"alert-dot"}/> INVALID-STATE SIMULATOR</div><span>{builder?"VALIDATED REQUEST":"FIELD BAG"}</span></div><div className="invalid-simulator">{invalid.map((x,i)=><button type="button" key={x} aria-pressed={attempt===i} onClick={()=>setAttempt(i)}>{x}</button>)}</div><div className={`lab-feedback ${builder?"success":"error"}`} aria-live="polite"><b>{builder?"INVALID VALUE REJECTED AT THE BOUNDARY":"INVALID OBJECT CREATED"}</b><p>{builder?`ReservationRequest.create(...) returns a typed validation error: ${invalid[attempt]}. No service can receive this state.`:`Public setters and optional fields allow “${invalid[attempt]}” to travel until a distant failure.`}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setBuilder(v=>!v)}>{builder?<Rotate/>:<ArrowRight/>}{builder?"ALLOW FIELD BAG":"MAKE INVALID STATE UNREPRESENTABLE"}</button></div>}
