"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const sessionStates=[
  ["CREATED","Memory exists, but required collaborators may not yet be attached."],
  ["READY","Construction and validation succeeded; process() is legal."],
  ["PROCESSING","One payment attempt owns the in-flight provider operation."],
  ["SUCCEEDED","Payment completed. Reprocessing would duplicate a side effect."],
  ["CLOSED","Resources are released and every mutating operation is illegal."],
] as const;
export function LifecycleTimelineLab(){const[index,setIndex]=useState(0);const[attempt,setAttempt]=useState(false);const terminal=index>=3;function advance(){setAttempt(false);setIndex(value=>Math.min(value+1,sessionStates.length-1))}return <div className="lifecycle-lab lab-panel"><div className="lab-toolbar"><div><span className={terminal?"alert-dot":"live-dot"}/> PAYMENT SESSION</div><span>LOGICAL LIFETIME</span></div><div className="lifecycle-timeline" role="tablist" aria-label="Payment session states">{sessionStates.map(([state],i)=><button type="button" role="tab" aria-selected={index===i} onClick={()=>{setIndex(i);setAttempt(false)}} key={state}><span>{String(i+1).padStart(2,"0")}</span><b>{state}</b>{i<sessionStates.length-1?<i/>:null}</button>)}</div><div className="lifecycle-focus"><small>CURRENT STATE</small><h3>{sessionStates[index][0]}</h3><p>{sessionStates[index][1]}</p><div><button className="lab-button" type="button" onClick={advance} disabled={index===sessionStates.length-1}>ADVANCE STATE <ArrowRight/></button><button className="quiet-lab-button" type="button" onClick={()=>setAttempt(true)}>CALL process()</button></div>{attempt?<div className={index===1?"operation-result success":"operation-result error"}><b>{index===1?"CALL ACCEPTED":"CALL REJECTED"}</b><span>{index===0?"The object is not fully initialized.":terminal?"The object still occupies memory, but its domain lifetime has ended.":index===2?"A second concurrent call would violate the session contract.":"The session is ready."}</span></div>:null}</div></div>}

const edges={draft:["CheckoutSession","OWNS","OrderDraft","The draft exists for this checkout and is disposed with the session."],gateway:["CheckoutService","REFERENCES","PaymentGateway","The service uses an app-lived dependency; it does not control the gateway lifetime."],connection:["PaymentSession","BORROWS","DB connection","The operation temporarily uses a pooled resource and must return it."],money:["Order","COPIES VALUE","Money","Immutable value semantics avoid accidental shared price mutation."]} as const;
export function OwnershipGraphLab(){const[selected,setSelected]=useState<keyof typeof edges>("draft");const edge=edges[selected];return <div className="ownership-graph lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> OWNERSHIP GRAPH</div><span>SELECT AN EDGE</span></div><div className="ownership-layout"><div className="ownership-list">{Object.keys(edges).map(key=><button type="button" aria-pressed={selected===key} onClick={()=>setSelected(key as keyof typeof edges)} key={key}>{edges[key as keyof typeof edges][0]} → {edges[key as keyof typeof edges][2]}</button>)}</div><div className="ownership-stage"><div className="class-node class-node--core"><small>OWNER / USER</small><b>{edge[0]}</b></div><div className={`ownership-edge ownership-edge--${edge[1].toLowerCase().replaceAll(" ","-")}`}><span>{edge[1]}</span><i/><ArrowRight/></div><div className="class-node interface"><small>OBJECT / RESOURCE</small><b>{edge[2]}</b></div></div><div className="lab-feedback"><b>{edge[1]}</b><p>{edge[3]}</p></div></div></div>}

export function ReferenceSemanticsLab(){const[shared,setShared]=useState(true);const[mutated,setMutated]=useState(false);const quantity=mutated?0:2;return <div className="reference-lab lab-panel"><div className="lab-toolbar"><div><span className={shared&&mutated?"alert-dot":"live-dot"}/> ALIAS VISUALIZER</div><div className="mode-toggle"><button type="button" aria-pressed={shared} onClick={()=>{setShared(true);setMutated(false)}}>SHARED REFERENCE</button><button type="button" aria-pressed={!shared} onClick={()=>{setShared(false);setMutated(false)}}>VALUE COPY</button></div></div><div className="alias-stage"><div><small>A · CHECKOUT</small><b>{shared?"Cart #42":"Money $10"}</b><code>{shared?`quantity = ${quantity}`:"value = $10"}</code></div><span>{shared?"↘ same object ↙":"copy → two values"}</span><div><small>B · UI</small><b>{shared?"Cart #42":"Money $10"}</b><code>{shared?`quantity = ${quantity}`:`value = ${mutated?"$12":"$10"}`}</code></div></div><div className="alias-actions"><button className="lab-button" type="button" onClick={()=>setMutated(true)}>{shared?"UI SETS QUANTITY TO 0":"B REPLACES VALUE WITH $12"}<ArrowRight/></button><button className="quiet-lab-button" type="button" onClick={()=>setMutated(false)}><Rotate/>RESET</button></div>{mutated?<div className={`lab-feedback ${shared?"error":"success"}`}><b>{shared?"UNEXPECTED SHARED MUTATION":"VALUES REMAIN INDEPENDENT"}</b><p>{shared?"Both callers observe the invalid Cart because A and B alias the same mutable object.":"B received a value and replaced its own copy. A still observes $10."}</p></div>:null}</div>}

type Actor="UI"|"DiscountService"|"CheckoutService";
export function MutabilityAuthorityLab(){const[controlled,setControlled]=useState(false);const[events,setEvents]=useState<string[]>([]);const[total,setTotal]=useState(100);function mutate(actor:Actor){if(controlled&&actor!=="CheckoutService"){setEvents(value=>[`${actor}: write rejected — read-only view`,...value]);return}const next=actor==="UI"?0:actor==="DiscountService"?total-30:total+15;setTotal(next);setEvents(value=>[`${actor}: total → $${next}`,...value])}return <div className="authority-lab lab-panel"><div className="lab-toolbar"><div><span className={!controlled&&events.length?"alert-dot":"live-dot"}/> CART MUTATION AUTHORITY</div><div className="mode-toggle"><button type="button" aria-pressed={!controlled} onClick={()=>{setControlled(false);setEvents([]);setTotal(100)}}>EVERYONE MUTATES</button><button type="button" aria-pressed={controlled} onClick={()=>{setControlled(true);setEvents([]);setTotal(100)}}>SINGLE AUTHORITY</button></div></div><div className="authority-stage"><div className="shared-cart"><small>SHARED CART</small><b>${total}</b><span>{controlled?"Checkout owns mutation":"3 write authorities"}</span></div><div className="authority-actors">{(["UI","DiscountService","CheckoutService"] as Actor[]).map(actor=><button type="button" onClick={()=>mutate(actor)} key={actor}><b>{actor}</b><small>{actor==="UI"?"clear cart":actor==="DiscountService"?"apply $30 discount":"add $15 fee"}</small></button>)}</div><div className="event-log"><span>EVENT LOG</span>{events.length?events.map((event,i)=><code key={`${event}-${i}`}>{event}</code>):<code>{"// trigger a mutation"}</code>}</div></div><p className="lab-caveat">Read-only access and immutable values reduce accidental writes. They do not replace a clear owner for valid state transitions.</p></div>}

export function OwnershipCycleLab(){const[weak,setWeak]=useState(false);return <div className="cycle-lab lab-panel"><div className="lab-toolbar"><div><span className={weak?"live-dot":"alert-dot"}/> C++ REFERENCE COUNTS</div><span>{weak?"CYCLE BROKEN":"LEAK RISK"}</span></div><div className="cycle-stage"><div><small>shared_ptr</small><b>Parent</b><code>count = {weak?"1":"2"}</code></div><span>owns →</span><div><small>shared_ptr</small><b>Child</b><code>count = {weak?"1":"2"}</code></div><span>{weak?"observes with weak_ptr ↗":"← owns with shared_ptr"}</span></div><div className="lab-feedback"><b>{weak?"PARENT OWNS; CHILD OBSERVES":"STRONG CYCLE"}</b><p>{weak?"When external owners disappear, Parent releases Child; Child's weak reference does not keep Parent alive.":"Parent and Child keep each other alive after external owners disappear. Reference counts never reach zero."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setWeak(!weak)}>{weak?<Rotate/>:<ArrowRight/>}{weak?"RESTORE SHARED CYCLE":"CHANGE CHILD TO weak_ptr"}</button></div>}
