"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const processors=[
 {name:"CardProcessor",checks:[true,true,true,true,true,true]},
 {name:"UPIProcessor",checks:[true,true,true,true,true,true]},
 {name:"BrokenProcessor",checks:[true,false,false,false,false,false]},
] as const;
const checks=["accepts valid request","returns PaymentResult","needs no undocumented setup","does not mutate unrelated state","preserves idempotency","uses promised failure semantics"];
export function ContractTestLab(){const[selected,setSelected]=useState(0);const[ran,setRan]=useState(false);const processor=processors[selected];const passed=processor.checks.filter(Boolean).length;return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={ran&&passed<6?"alert-dot":"live-dot"}/> SHARED CONTRACT SUITE</div><span>{ran?`${passed} / 6 PASS`:"READY"}</span></div><div className="contract-layout"><div className="implementation-list" role="tablist" aria-label="Payment processor implementation">{processors.map((item,i)=><button type="button" role="tab" aria-selected={selected===i} onClick={()=>{setSelected(i);setRan(false)}} key={item.name}>{item.name}</button>)}</div><div className="contract-results" aria-live="polite"><h3>{processor.name}</h3>{checks.map((check,i)=><p className={!ran?"pending":processor.checks[i]?"pass":"fail"} key={check}><b>{!ran?"·":processor.checks[i]?"✓":"×"}</b><span>{check}</span>{ran&&!processor.checks[i]?<small>{i===1?"throws instead of returning a result":i===2?"requires setApiKey() before a valid call":i===3?"clears the cart during payment":i===4?"charges twice for the same request":"throws for normal declines"}</small>:null}</p>)}</div></div><button className="lab-button cycle-button" type="button" onClick={()=>setRan(true)} disabled={ran}>RUN SAME CONTRACT TESTS <ArrowRight/></button></div>}

export function PreconditionsLab(){const[strict,setStrict]=useState(false);return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={strict?"alert-dot":"live-dot"}/> VALID INPUT RANGE</div><span>withdraw(amount)</span></div><div className="range-stage"><div><span>CALLER / BASE CONTRACT</span><b>amount &gt; 0</b><i style={{width:"100%"}}/></div><div><span>{strict?"VIP ACCOUNT SUBTYPE":"HONEST SUBTYPE"}</span><b>{strict?"amount ≥ 1000":"amount > 0"}</b><i className={strict?"narrow":""} style={{width:strict?"35%":"100%"}}/></div></div><div className={`lab-feedback ${strict?"error":"success"}`} aria-live="polite"><b>{strict?"STRONGER HIDDEN PRECONDITION":"CALLER INPUT REMAINS VALID"}</b><p>{strict?"The base allows withdraw(100), but this subtype rejects it. A caller written to the abstraction is now broken.":"The implementation accepts every input promised by the abstraction and may safely accept more."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setStrict(v=>!v)}>{strict?<Rotate/>:<ArrowRight/>}{strict?"RESTORE CONTRACT":"TIGHTEN SUBTYPE"}</button></div>}

const storageCapabilities=[
 ["S3Storage",true,true,true],["LocalStorage",true,true,true],["ReadOnlyArchiveStorage",true,false,false],["TemporaryMemoryStorage",true,true,true],
] as const;
export function CapabilityLab(){const[split,setSplit]=useState(false);return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={split?"live-dot":"alert-dot"}/> STORAGE CAPABILITIES</div><span>{split?"HONEST CONTRACTS":"BROAD CONTRACT"}</span></div><div className="capability-table"><div><span>IMPLEMENTATION</span><span>READ</span><span>WRITE</span><span>DELETE</span><span>ASSIGNED CONTRACT</span></div>{storageCapabilities.map(([name,read,write,remove])=><div key={name}><b>{name}</b>{[read,write,remove].map((value,i)=><span className={value?"yes":"no"} key={i}>{value?"✓":"—"}</span>)}<em>{split?(write?"Readable + Writable + Deletable":"ReadableStorage"):"CloudStorage"}</em></div>)}</div><div className={`lab-feedback ${split?"success":"error"}`}><b>{split?"CAPABILITIES TELL THE TRUTH":"METHODS MAKE NO SEMANTIC SENSE"}</b><p>{split?"ReadOnlyArchiveStorage no longer pretends it can save or delete. Callers request only the capability they need.":"ReadOnlyArchiveStorage must throw or silently ignore save() and delete(). The subtype may be honest; the broad interface is the problem."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setSplit(v=>!v)}>{split?<Rotate/>:<ArrowRight/>}{split?"RESTORE BROAD INTERFACE":"SPLIT BY CAPABILITY"}</button></div>}

export function BehaviorContractVisual(){const[dimension,setDimension]=useState(0);const dimensions=[["PRECONDITIONS","Do not demand stricter inputs."],["POSTCONDITIONS","Do not weaken promised results."],["INVARIANTS","Preserve truths callers rely on."],["ERROR SEMANTICS","Fail in the promised form."],["SIDE EFFECTS","Do not surprise unrelated state."],["STATE HISTORY","Preserve legal transitions."]] as const;return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> OBSERVABLE CONTRACT</div><span>MORE THAN A SIGNATURE</span></div><div className="contract-wheel"><div className="contract-core"><small>CALLER TRUSTS</small><b>Storage</b><code>save · load · delete</code></div><div className="contract-dimensions">{dimensions.map(([name],i)=><button type="button" aria-pressed={dimension===i} onClick={()=>setDimension(i)} key={name}>{name}</button>)}</div></div><div className="lab-feedback success" aria-live="polite"><b>{dimensions[dimension][0]}</b><p>{dimensions[dimension][1]}</p></div></div>}
