"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const variants=["regular","premium","employee","festival","coupon","loyalty","corporate","partner"] as const;
export function BranchGrowthLab(){const[count,setCount]=useState(3);const risk=count<5?"LOW":count<7?"RISING":"HIGH";return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={count>5?"alert-dot":"live-dot"}/> BRANCH GROWTH</div><span>{count} PRICING VARIANTS</span></div><div className="branch-stage"><div className="branch-code"><small>PricingService.calculate()</small>{variants.slice(0,count).map((name,i)=><code key={name}><b>{i===0?"if":"else if"}</b> type == &quot;{name}&quot; <i>→ apply {name}</i></code>)}</div><div className="change-pulses" aria-hidden="true">{variants.slice(3,count).map(name=><span key={name}>{name.toUpperCase()} EDITS CORE</span>)}</div></div><div className="object-metrics" aria-live="polite">{[["VARIANTS",String(count)],["BRANCHES",String(count)],["CENTRAL FILE EDITS",String(Math.max(1,count-2))],["TEST SURFACE",count<5?"LOW":"HIGH"],["REGRESSION RISK",risk]].map(([k,v])=><span key={k}><small>{k}</small><b className={v==="HIGH"?"bad":""}>{v}</b></span>)}</div><div className="lab-actions"><button className="quiet-lab-button" type="button" disabled={count===variants.length} onClick={()=>setCount(v=>Math.min(variants.length,v+1))}>ADD REQUIREMENT</button><button className="lab-button" type="button" onClick={()=>setCount(3)}><Rotate/>RESET</button></div></div>}

const registryEntries=["festival","coupon","corporate","partner"] as const;
export function RegistryLab(){const[count,setCount]=useState(3);const hasPartner=count===4;return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> EXTENSION REGISTRY</div><span>CONFIGURED BOUNDARY</span></div><div className="registry-stage"><div className="stable-core"><small>STABLE CORE</small><b>PricingService</b><code>policy = registry.resolve(type)<br/>return policy.apply(total)</code></div><div className="extension-line" aria-hidden="true"><span>EXTENSION CONTRACT</span><i/></div><div className="registry-items">{registryEntries.slice(0,count).map(name=><div key={name}><small>{name}</small><b>{name[0].toUpperCase()+name.slice(1)}Discount</b></div>)}</div></div><div className="object-metrics" aria-live="polite">{[["STABLE CORE MODIFIED?","NO"],["NEW EXTENSION ADDED?",hasPartner?"YES":"READY"],["REGISTRY EDITS",String(count)],["POLICY TEST","ISOLATED"]].map(([k,v])=><span key={k}><small>{k}</small><b>{v}</b></span>)}</div><button className="lab-button cycle-button" type="button" onClick={()=>setCount(hasPartner?3:4)}>{hasPartner?<Rotate/>:<ArrowRight/>}{hasPartner?"REMOVE PARTNER":"ADD PARTNER"}</button></div>}

const changes=[
 ["Festival pricing","2","core branch + integration","many","HIGH"],
 ["Corporate pricing","2","core branch + customer logic","many","HIGH"],
 ["Region-specific pricing","3","branch + region + pricing","many","HIGH"],
 ["Coupon stacking","3","branch ordering + pricing","many","HIGH"],
 ["Disable one policy","1","shared switch","broad","MEDIUM"],
 ["Experimental policy","2","core branch + flag","many","HIGH"],
] as const;
export function ExtensionChangeLab(){const[index,setIndex]=useState(0);const[extended,setExtended]=useState(false);const change=changes[index];return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={extended?"live-dot":"alert-dot"}/> CHANGE SIMULATOR</div><div className="mode-toggle"><button type="button" aria-pressed={!extended} onClick={()=>setExtended(false)}>BRANCH-HEAVY</button><button type="button" aria-pressed={extended} onClick={()=>setExtended(true)}>EXTENSION-ORIENTED</button></div></div><div className="change-sim-layout"><div className="change-list">{changes.map((item,i)=><button type="button" aria-pressed={index===i} onClick={()=>setIndex(i)} key={item[0]}>{item[0]}</button>)}</div><div className="change-report" aria-live="polite"><small>REQUIREMENT</small><h3>{change[0]}</h3><div className={extended?"extension-report good":"extension-report bad"}>{(extended?[["FILES TOUCHED","1 new policy"],["EXISTING LOGIC MODIFIED","NO"],["TESTS IMPACTED","policy + contract"],["BLAST RADIUS","LOW"]]:[["FILES TOUCHED",change[1]],["EXISTING LOGIC MODIFIED",change[2]],["TESTS IMPACTED",change[3]],["BLAST RADIUS",change[4]]]).map(([k,v])=><p key={k}><span>{k}</span><b>{v}</b></p>)}</div></div></div></div>}

export function PrematureAbstractionLab(){const[abstracted,setAbstracted]=useState(false);return <div className="principle-lab lab-panel"><div className="lab-toolbar"><div><span className={abstracted?"alert-dot":"live-dot"}/> ABSTRACTION COST</div><span>ONE FIXED RULE</span></div><div className="premature-stage">{abstracted?<><span>IPricePolicyProviderFactoryResolver</span><i>→</i><span>PricePolicyProviderFactory</span><i>→</i><span>FixedDiscount</span></>:<span className="simple-policy">applyFixedDiscount(total)</span>}</div><div className={`lab-feedback ${abstracted?"error":"success"}`}><b>{abstracted?"WHAT FUTURE CHANGE ARE WE PROTECTING AGAINST?":"THE SIMPLE CHANGE IS CHEAPER"}</b><p>{abstracted?"There is no observed axis of variation. Indirection, naming, wiring, and tests now cost more than editing the fixed rule.":"Keep the code direct. Introduce an extension point when real variants begin reopening the same stable decision."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setAbstracted(v=>!v)}>{abstracted?<Rotate/>:<ArrowRight/>}{abstracted?"RETURN TO SIMPLE":"OVERENGINEER IT"}</button></div>}
