"use client";

import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const creationSteps=[
  {label:"DIRECT NEW",types:3,branches:3,config:"LOW",deps:"LOW",caller:"3 concrete strategies"},
  {label:"GROWTH",types:6,branches:6,config:"HIGH",deps:"HIGH",caller:"providers · clock · tax · config"},
  {label:"FACTORY",types:0,branches:1,config:"HIDDEN",deps:"CENTRAL",caller:"PricingStrategy contract"},
] as const;
export function CreationPressureLab(){const[step,setStep]=useState(0);const x=creationSteps[step];return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={step===2?"live-dot":"alert-dot"}/> CREATION PRESSURE LAB</div><span>{x.label}</span></div><div className="creation-flow"><b>PricingService</b><i>→</i><div><span>{step<2?"constructs":"asks"}</span><strong>{x.caller}</strong></div><i>→</i><b>{step<2?"Strategies":"PricingStrategyFactory"}</b></div><div className="metric-strip">{[["CONCRETE TYPES",x.types],["BRANCHES",x.branches],["CONFIG",x.config],["DEPENDENCIES",x.deps]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className={`lab-feedback ${step===2?"success":"error"}`} aria-live="polite"><b>{x.label}</b><p>{step===0?"The caller uses and constructs behavior; the branch is merely relocated from Chapter 17.":step===1?"Construction now exposes volatile dependencies and configuration to the pricing caller.":"Use and creation are separate. The factory centralizes construction—it does not magically remove every switch."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setStep((step+1)%3)}>{step===2?<Rotate/>:<ArrowRight/>}{step===2?"RESTORE DIRECT NEW":"ADD PRESSURE"}</button></div>}

const families={AWS:["S3Storage","SQSQueue","CloudWatchMetrics"],GCP:["GCSStorage","PubSubQueue","CloudMonitoring"]} as const;
export function FactoryFamilyRegistryLab(){const[provider,setProvider]=useState<keyof typeof families>("AWS");const[creators,setCreators]=useState(["standard","surge","corporate"]);const add=()=>{if(!creators.includes("airport"))setCreators([...creators,"airport"])};return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> FACTORY FAMILY / REGISTRY LAB</div><span>{provider} FAMILY</span></div><div className="family-toggle" role="group" aria-label="Cloud family">{Object.keys(families).map(x=><button type="button" aria-pressed={provider===x} onClick={()=>setProvider(x as keyof typeof families)} key={x}>{x}</button>)}</div><div className="family-tree" aria-live="polite"><b>{provider}Factory</b>{families[provider].map(x=><span key={x}>{x}</span>)}</div><div className="registry-row"><div>{creators.map(x=><code key={x}>{x} → creator</code>)}</div><button className="lab-button" type="button" disabled={creators.includes("airport")} onClick={add}>REGISTER AIRPORT</button></div><p className="lab-caption">A coherent family swaps together. A creator registry extends selection without editing it, at the cost of runtime registration, discoverability, and ordering concerns.</p></div>}

const notificationFields=["subject","schedule","metadata","attachment","tracking"] as const;
export function TelescopingConstructorLab(){const[builder,setBuilder]=useState(false);const[enabled,setEnabled]=useState<string[]>(["tracking"]);const toggle=(x:string)=>setEnabled(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x]);return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={builder?"live-dot":"alert-dot"}/> TELESCOPING CONSTRUCTOR LAB</div><button type="button" className="mode-button" aria-pressed={builder} onClick={()=>setBuilder(!builder)}>{builder?"BUILDER MODE":"POSITIONAL MODE"}</button></div><div className="field-toggles">{notificationFields.map(x=><button type="button" aria-pressed={enabled.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><div className="constructor-preview" aria-live="polite"><code>{builder?`Notification.builder()\n  .recipient(user)\n  .body(body)${enabled.map(x=>`\n  .${x}(${x}Value)`).join("")}\n  .build()`:`new Notification(user, ${enabled.includes("subject")?"subject":"null"}, body, 2, "en-IN", ${enabled.includes("schedule")?"schedule":"null"}, 3, ${enabled.includes("metadata")?"metadata":"null"}, ${enabled.includes("attachment")?"attachment":"null"}, ${enabled.includes("tracking")?"true":"false"}, "")`}</code></div><div className="metric-strip">{[["POSITIONAL",builder?0:11],["NULLS",builder?0:notificationFields.filter(x=>!enabled.includes(x)).length],["FLAGS",builder?0:1],["CLARITY",builder?"HIGH":"LOW"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}

const builderStates=["EMPTY","HAS_RECIPIENT","READY_TO_BUILD","BUILT"] as const;
export function BuilderStateMachine(){const[state,setState]=useState(0);const[message,setMessage]=useState("Add required fields, then build.");const addRecipient=()=>{if(state===0){setState(1);setMessage("Recipient captured; body is still required.")}};const addBody=()=>{if(state===1){setState(2);setMessage("Required fields complete; optional configuration remains available.")}};const build=()=>{if(state===2){setState(3);setMessage("Immutable Notification built with defensive copies.")}else if(state<2)setMessage("MISSING REQUIRED FIELD — build rejected.")};return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={state===3?"live-dot":"alert-dot"}/> BUILDER STATE MACHINE</div><span>{builderStates[state]}</span></div><div className="builder-states">{builderStates.map((x,n)=><span className={n===state?"active":n<state?"done":""} key={x}>{x}</span>)}</div><div className="builder-actions"><button type="button" onClick={addRecipient} disabled={state!==0}>ADD RECIPIENT</button><button type="button" onClick={addBody} disabled={state!==1}>ADD BODY</button><button type="button" onClick={build} disabled={state===3}>BUILD</button><button type="button" onClick={()=>{setState(0);setMessage("Add required fields, then build.")}}>RESET</button></div><div className={`lab-feedback ${state===3?"success":"error"}`} aria-live="polite"><b>{builderStates[state]}</b><p>{message}</p></div></div>}

const hiddenServices=["PaymentRepository","PaymentGateway","Logger","Metrics"] as const;
export function HiddenDependencyLab(){const[explicit,setExplicit]=useState(false);const[failed,setFailed]=useState(false);return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={explicit?"live-dot":"alert-dot"}/> HIDDEN DEPENDENCY LAB</div><span>{explicit?"COMPOSITION ROOT":"GLOBAL ACCESS"}</span></div><div className={`dependency-web ${explicit?"explicit":""}`}><b>PaymentService</b>{hiddenServices.map(x=><span key={x}>{explicit?"constructor → ":"Global.get → "}{x}</span>)}</div><div className="lab-actions"><button className="lab-button" type="button" onClick={()=>setFailed(!failed)}>{failed?"RESTORE TEST":"RUN ISOLATED TEST"}</button><button className="lab-button" type="button" onClick={()=>{setExplicit(!explicit);setFailed(false)}}>{explicit?"USE GLOBALS":"INJECT DEPENDENCIES"}</button></div><div className={`lab-feedback ${explicit?"success":"error"}`} aria-live="polite"><b>{explicit?"DEPENDENCIES VISIBLE":"TEST ORDER DEPENDENCE"}</b><p>{explicit?"Application ownership can still create one instance while callers depend explicitly on contracts.":failed?"A previous test changed global state. Reset order now controls the result.":"The constructor lies: business code reaches mutable process-wide services invisibly."}</p></div></div>}

const lifetimeCases=[
  {name:"Configuration",answer:"application",note:"Usually one immutable application-owned snapshot; global access is optional."},
  {name:"CurrentUser",answer:"request",note:"Identity is request/session scoped. A process singleton leaks users across concurrent work."},
  {name:"ConnectionPool",answer:"application",note:"Often one or a few application-owned pools, explicitly injected; not necessarily global."},
  {name:"ShoppingCart",answer:"session",note:"Cart state belongs to a user session, never the whole process."},
  {name:"RequestContext",answer:"request",note:"Correlation and cancellation live for one request."},
] as const;
export function SingletonLifetimeLab(){const[i,setI]=useState(0);const[choice,setChoice]=useState("global");const x=lifetimeCases[i];const correct=choice===x.answer;return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={correct?"live-dot":"alert-dot"}/> SINGLETON LIFETIME DECISION LAB</div><span>{x.name}</span></div><div className="candidate-list">{lifetimeCases.map((x,n)=><button type="button" aria-pressed={i===n} onClick={()=>{setI(n);setChoice("global")}} key={x.name}>{x.name}</button>)}</div><div className="lifetime-options" role="group" aria-label="Choose lifetime">{["global","application","request","session"].map(x=><button type="button" aria-pressed={choice===x} onClick={()=>setChoice(x)} key={x}>{x}</button>)}</div><div className={`lab-feedback ${correct?"success":"error"}`} aria-live="polite"><b>{correct?"LIFETIME FITS":"ONE INSTANCE IS NOT THE WHOLE QUESTION"}</b><p>{x.note}</p></div></div>}

const reactions=["Email","Analytics","Loyalty","Inventory","Push","Fraud"] as const;
export function ObserverRefactorLab(){const[observer,setObserver]=useState(false);const[count,setCount]=useState(3);return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={observer?"live-dot":"alert-dot"}/> HARD COUPLING → OBSERVER</div><span>{count} REACTIONS</span></div><div className={`observer-graph ${observer?"decoupled":""}`}><b>OrderService</b><i>{observer?"OrderConfirmed":"calls"}</i><div>{reactions.slice(0,count).map(x=><span key={x}>{x}</span>)}</div></div><div className="metric-strip">{[["PRODUCER DEPENDENCIES",observer?1:count],["BLAST RADIUS",observer?1:count],["SUBSCRIBERS",count],["EXTENSION",observer?"SUBSCRIBE":"EDIT SERVICE"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="lab-actions"><button className="lab-button" type="button" onClick={()=>setCount(count===6?3:count+1)}>ADD REACTION</button><button className="lab-button" type="button" onClick={()=>setObserver(!observer)}>{observer?"RESTORE CALLS":"PUBLISH EVENT"}</button></div></div>}

export function ObserverLifecycleDispatchLab(){const[listeners,setListeners]=useState(["Email","Analytics","Loyalty"]);const[stale,setStale]=useState(false);const[asyncMode,setAsyncMode]=useState(false);const[emitted,setEmitted]=useState(false);const remove=()=>{setListeners(stale?listeners:[...listeners.slice(0,-1)]);setStale(!stale)};const duration=asyncMode?12:listeners.reduce((n,x)=>n+(x==="Analytics"?900:20),0);return <div className="pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={!stale?"live-dot":"alert-dot"}/> OBSERVER LIFECYCLE / DISPATCH</div><span>{listeners.length} LISTENERS</span></div><div className="dispatch-controls"><button type="button" aria-pressed={stale} onClick={remove}>{stale?"CLEAN STALE LISTENER":"UNMOUNT WITHOUT CLEANUP"}</button><button type="button" aria-pressed={asyncMode} onClick={()=>setAsyncMode(!asyncMode)}>{asyncMode?"ASYNC DELIVERY":"SYNC DELIVERY"}</button><button type="button" onClick={()=>setEmitted(true)}>EMIT ORDER CONFIRMED</button></div><div className="fanout" aria-live="polite"><b>OrderConfirmed</b>{listeners.map(x=><span className={x==="Analytics"?"slow":""} key={x}>{x}{x==="Analytics"?" · 900ms":" · 20ms"}</span>)}</div><div className={`lab-feedback ${!stale?"success":"error"}`}><b>{stale?"STALE LISTENER · LEAK RISK":emitted?`DISPATCH RETURNED IN ${duration}ms`:"SUBSCRIPTIONS OWNED"}</b><p>{asyncMode?"Asynchronous delivery frees the producer but changes ordering, failure, retry, and completion guarantees.":"Synchronous listeners run on the producer path; one slow or failed observer affects completion."}</p></div></div>}
