"use client";

import { useState } from "react";

const Metric=({label,value}:{label:string;value:string|number})=><div><span>{label}</span><b>{value}</b></div>;

export function RelationshipClassificationLab(){
  const edges={"Order → OrderItem":"COMPOSITION","Order → Customer":"ASSOCIATION","Order → PaymentProcessor":"DEPENDENCY","PricingPolicy → DiscountPolicy":"IMPLEMENTATION"} as const;
  const[answers,setAnswers]=useState<Record<string,string>>({});const[focus,setFocus]=useState<keyof typeof edges>("Order → OrderItem");
  const score=Object.entries(edges).filter(([k,v])=>answers[k]===v).length;
  return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={score===4?"live-dot":"alert-dot"}/> RELATIONSHIP CLASSIFIER</div><span>{score}/4 DEFENSIBLE</span></div><div className="runtime-grid">{Object.keys(edges).map(x=><button type="button" aria-pressed={focus===x} onClick={()=>setFocus(x as keyof typeof edges)} key={x}><b>{x}</b><small>{answers[x]??"UNCLASSIFIED"}</small></button>)}</div><div className="runtime-actions">{["ASSOCIATION","AGGREGATION","COMPOSITION","INHERITANCE","IMPLEMENTATION","DEPENDENCY"].map(x=><button type="button" aria-pressed={answers[focus]===x} onClick={()=>setAnswers({...answers,[focus]:x})} key={x}>{x}</button>)}</div><div className="lab-feedback success" aria-live="polite"><b>{focus}</b><p>{edges[focus]==="COMPOSITION"?"The whole controls this part’s lifecycle.":edges[focus]==="DEPENDENCY"?"A temporary use is weaker than stored ownership.":"Name the semantic promise, not merely the arrow shape."}</p></div></div>;
}

export function ClassDiagramBuilderLab(){
  const nodes=["ParkingLot","Floor","Spot","Vehicle","Ticket","PricingPolicy","Payment"];
  const[added,setAdded]=useState<string[]>(["ParkingLot"]);const[precise,setPrecise]=useState(false);
  const toggle=(x:string)=>setAdded(v=>v.includes(x)?v.filter(n=>n!==x):[...v,x]);
  return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={added.length===7&&precise?"live-dot":"alert-dot"}/> CLASS DIAGRAM BUILDER</div><button type="button" className="mode-button" aria-pressed={precise} onClick={()=>setPrecise(!precise)}>{precise?"SEMANTIC EDGES":"PLAIN ARROWS"}</button></div><div className="runtime-actions">{nodes.map(x=><button type="button" aria-pressed={added.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><div className="diagram-canvas">{added.map((x,i)=><div key={x}><small>{x.includes("Policy")?"«interface»":i<3?"owner / part":"class"}</small><b>{x}</b><span>{precise?(x==="Floor"?"1..* composed":x==="Spot"?"1..* composed":x==="PricingPolicy"?"implemented":"0..1 associated"):"→ connected"}</span></div>)}</div><div className="metric-strip"><Metric label="CLASSES" value={added.length}/><Metric label="OWNERSHIP VISIBLE" value={precise?"YES":"NO"}/><Metric label="MULTIPLICITY" value={precise?"EXPLICIT":"MISSING"}/><Metric label="DB TABLES" value="0"/></div></div>;
}

export function SequenceFlowLab(){
  const initial=["validate","reserve","pay","confirm","notify"];const[steps,setSteps]=useState(initial);const[failed,setFailed]=useState(false);
  const move=(i:number,d:number)=>{const n=[...steps],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];setSteps(n)};
  return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={!failed&&steps.join()===initial.join()?"live-dot":"alert-dot"}/> SEQUENCE FLOW</div><button type="button" className="mode-button" aria-pressed={failed} onClick={()=>setFailed(!failed)}>PAYMENT {failed?"FAILS":"SUCCEEDS"}</button></div><div className="sequence-track">{steps.map((x,i)=><div key={x}><b>{x.toUpperCase()}</b><span><button aria-label={`Move ${x} earlier`} type="button" disabled={!i} onClick={()=>move(i,-1)}>←</button><button aria-label={`Move ${x} later`} type="button" disabled={i===steps.length-1} onClick={()=>move(i,1)}>→</button></span></div>)}</div>{failed&&<div className="lab-feedback error"><b>ALTERNATE: RELEASE RESERVATION</b><p>Failure changes the interaction: confirmation and notification are skipped, while compensation releases the held spot.</p></div>}</div>;
}

export function DiagramRefactorLab(){const[clean,setClean]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={clean?"live-dot":"alert-dot"}/> DIAGRAM REFACTOR</div><button type="button" className="mode-button" aria-pressed={clean} onClick={()=>setClean(!clean)}>{clean?"PURPOSEFUL VIEW":"EVERYTHING VIEW"}</button></div><div className={`noise-diagram ${clean?"clean":""}`}>{(clean?["Booking","SeatReservation","PaymentPort","PricingPolicy"]:["Booking","Seat","User","Movie","Screen","Theater","DB","booking_table","seat_table","Controller","PaymentSDK","Logger"]).map(x=><span key={x}>{x}</span>)}</div><div className="metric-strip"><Metric label="BOXES" value={clean?4:12}/><Metric label="CROSSING EDGES" value={clean?1:17}/><Metric label="IMPLEMENTATION NOISE" value={clean?0:5}/><Metric label="QUESTION ANSWERED" value={clean?"YES":"NO"}/></div></div>}

type RaceState={balance:number;a?:number;b?:number;log:string[]};
export function InterleavingRaceLab(){const[state,setState]=useState<RaceState>({balance:100,log:[]});const act=(thread:"A"|"B",kind:"READ"|"WRITE")=>setState(s=>{if(kind==="READ")return {...s,[thread.toLowerCase()]:s.balance,log:[...s.log,`${thread} reads ${s.balance}`]};const read=thread==="A"?s.a:s.b;if(read===undefined)return {...s,log:[...s.log,`${thread} cannot write before reading`]};return {...s,balance:read-80,log:[...s.log,`${thread} writes ${read-80}`]}});return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={state.balance<0?"live-dot":"alert-dot"}/> MANUAL INTERLEAVING</div><button className="mode-button" type="button" onClick={()=>setState({balance:100,log:[]})}>RESET</button></div><div className="race-console"><strong>BALANCE {state.balance}</strong>{(["A","B"] as const).map(t=><div key={t}><b>THREAD {t} · LOCAL {state[t.toLowerCase() as "a"|"b"]??"—"}</b><button type="button" onClick={()=>act(t,"READ")}>READ</button><button type="button" onClick={()=>act(t,"WRITE")}>COMPUTE −80 + WRITE</button></div>)}</div><div className="trace-log" aria-live="polite">{state.log.length?state.log.map((x,i)=><span key={`${x}${i}`}>{i+1}. {x}</span>):<span>Try A read → B read → A write → B write.</span>}</div><p className="lab-caption">If both withdrawals succeed, the invariant requires −60. A final balance of 20 reveals a lost update: interleaving made two individually plausible steps incorrect together.</p></div>}

export function AtomicSchedulerLab(){const[atomic,setAtomic]=useState(false);const[status,setStatus]=useState(["READY","READY","BLOCKED"]);const[turn,setTurn]=useState(0);const step=()=>{setStatus(s=>s.map((_,i)=>i===turn?"RUNNING":i===(turn+2)%3?"BLOCKED":"READY"));setTurn((turn+1)%3)};return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={atomic?"live-dot":"alert-dot"}/> ATOMICITY / SCHEDULER</div><button type="button" className="mode-button" aria-pressed={atomic} onClick={()=>setAtomic(!atomic)}>{atomic?"ATOMIC FETCH-ADD":"READ + WRITE"}</button></div><div className="scheduler-lanes">{status.map((x,i)=><div className={x.toLowerCase()} key={i}><b>WORKER {String.fromCharCode(65+i)}</b><span>{x}</span></div>)}</div><div className="runtime-actions"><button type="button" onClick={step}>SCHEDULER STEP</button></div><div className="metric-strip"><Metric label="COUNTER AFTER 3 INCREMENTS" value={atomic?3:"1–3"}/><Metric label="OPERATION" value={atomic?"INDIVISIBLE":"COMPOSITE"}/><Metric label="ORDER" value="NON-DETERMINISTIC"/><Metric label="SAFETY" value={atomic?"COUNTER ONLY":"RACE"}/></div></div>}

export function MutexContentionLab(){const[mutex,setMutex]=useState(true);const[owner,setOwner]=useState<string>();const[inventory,setInventory]=useState(2);const acquire=(w:string)=>{if(!mutex||!owner)setOwner(w)};const sell=(w:string)=>{if((!mutex||owner===w)&&inventory>0)setInventory(v=>v-1)};return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={mutex?"live-dot":"alert-dot"}/> MUTEX CONTENTION</div><button type="button" className="mode-button" aria-pressed={mutex} onClick={()=>{setMutex(!mutex);setOwner(undefined)}}>{mutex?"MUTEX ON":"MUTEX OFF"}</button></div><div className="runtime-grid">{["T1","T2","T3"].map(w=><div key={w}><b>{w}</b><small>{owner===w?"OWNER":owner&&mutex?"BLOCKED":"READY"}</small><button type="button" onClick={()=>acquire(w)}>ACQUIRE</button><button type="button" onClick={()=>sell(w)}>SELL</button><button type="button" onClick={()=>owner===w&&setOwner(undefined)}>RELEASE</button></div>)}</div><div className="metric-strip"><Metric label="INVENTORY" value={inventory}/><Metric label="LOCK OWNER" value={owner??"NONE"}/><Metric label="BLOCKED" value={owner&&mutex?2:0}/><Metric label="INVARIANT" value={inventory>=0?"HOLDS":"BROKEN"}/></div></div>}

function QueueLab({capacity,title}:{capacity:number;title:string}){const[items,setItems]=useState<string[]>([]);const[waiting,setWaiting]=useState<"PRODUCER"|"CONSUMER"|"NONE">("NONE");const produce=()=>items.length===capacity?setWaiting("PRODUCER"):(setItems(v=>[...v,`job-${v.length+1}`]),setWaiting("NONE"));const consume=()=>!items.length?setWaiting("CONSUMER"):(setItems(v=>v.slice(1)),setWaiting("NONE"));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> {title}</div><span>CAPACITY {capacity}</span></div><div className="queue-visual">{Array.from({length:capacity},(_,i)=><span className={items[i]?"filled":""} key={i}>{items[i]??"EMPTY"}</span>)}</div><div className="runtime-actions"><button type="button" onClick={produce}>PRODUCE</button><button type="button" onClick={consume}>CONSUME</button></div><div className="metric-strip"><Metric label="PREDICATE" value={`${items.length} > 0 / < ${capacity}`}/><Metric label="WAITING" value={waiting}/><Metric label="WAIT RELEASES LOCK" value="YES"/><Metric label="WAKE THEN" value="RECHECK"/></div></div>}
export function ProducerConsumerLab(){return <QueueLab capacity={3} title="PRODUCER / CONSUMER CONDITION"/>}
export function BlockingQueueLab(){return <QueueLab capacity={2} title="BOUNDED BLOCKING QUEUE"/>}

export function DeadlockGraphLab(){const[step,setStep]=useState(0);const[toggles,setToggles]=useState([true,true,true,true]);const actions=["T1 locks A","T2 locks B","T1 waits for B","T2 waits for A"];const cycle=step===4&&toggles.every(Boolean);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={cycle?"alert-dot":"live-dot"}/> WAIT-FOR GRAPH</div><button className="mode-button" type="button" onClick={()=>setStep(0)}>RESET</button></div><div className="wait-graph"><b>T1</b><span>{step>=3?"WAITS FOR B":"RUNNABLE"}</span><b>T2</b><span>{step>=4?"WAITS FOR A":"RUNNABLE"}</span></div><div className="runtime-actions"><button type="button" disabled={step===4} onClick={()=>setStep(v=>v+1)}>STEP: {actions[step]??"CYCLE FORMED"}</button></div><div className="condition-toggles">{["MUTUAL EXCLUSION","HOLD + WAIT","NO PREEMPTION","CIRCULAR WAIT"].map((x,i)=><button type="button" aria-pressed={toggles[i]} onClick={()=>setToggles(v=>v.map((n,j)=>j===i?!n:n))} key={x}>{x}</button>)}</div><div className={`lab-feedback ${cycle?"error":"success"}`}><b>{cycle?"DEADLOCK: T1 → T2 → T1":"NO COMPLETE CYCLE"}</b><p>Deadlock requires all four Coffman conditions. Remove one structurally; a timeout only detects waiting after correctness is already lost.</p></div></div>}

export function LockOrderingLab(){const[ordered,setOrdered]=useState(false);const[request,setRequest]=useState("A → B");return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={ordered?"live-dot":"alert-dot"}/> LOCK ORDERING</div><button type="button" className="mode-button" aria-pressed={ordered} onClick={()=>setOrdered(!ordered)}>{ordered?"GLOBAL A < B < C":"CALLER ORDER"}</button></div><div className="runtime-actions">{["A → B","B → A","C → A","B → C"].map(x=><button type="button" aria-pressed={request===x} onClick={()=>setRequest(x)} key={x}>{x}</button>)}</div><div className="ordering-path">{(ordered?[...request.split(" → ")].sort():request.split(" → ")).map((x,i)=><span key={`${x}${i}`}>{i+1}. LOCK {x}</span>)}</div><div className="metric-strip"><Metric label="REQUESTED" value={request}/><Metric label="ACQUIRED" value={ordered?[...request.split(" → ")].sort().join(" → "):request}/><Metric label="CIRCULAR WAIT" value={ordered?"PREVENTED":"POSSIBLE"}/></div></div>}

export function LockGranularityLab(){const[mode,setMode]=useState<"GLOBAL"|"SHARDED"|"PER-KEY">("GLOBAL");const data={GLOBAL:[1,7,"LOW"],SHARDED:[4,4,"MEDIUM"],"PER-KEY":[8,1,"HIGH"]}[mode];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> LOCK GRANULARITY</div><span>8 WORKERS · 4 KEYS</span></div><div className="runtime-actions">{(["GLOBAL","SHARDED","PER-KEY"] as const).map(x=><button type="button" aria-pressed={mode===x} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><div className="metric-strip"><Metric label="PARALLEL HOLDERS" value={data[0]}/><Metric label="AVG WAIT STEPS" value={data[1]}/><Metric label="BOOKKEEPING" value={data[2]}/><Metric label="CORRECTNESS" value="SAME TARGET"/></div><p className="lab-caption">Finer locks can reduce unrelated contention, but add lock objects, ordering rules, lifecycle management, and harder debugging.</p></div>}

export function AllocationPressureLab(){const[mode,setMode]=useState<"REUSE"|"ALLOCATE">("ALLOCATE");const[count,setCount]=useState(0);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={mode==="REUSE"?"live-dot":"alert-dot"}/> ALLOCATION PRESSURE</div><button type="button" className="mode-button" aria-pressed={mode==="REUSE"} onClick={()=>setMode(mode==="REUSE"?"ALLOCATE":"REUSE")}>{mode}</button></div><div className="runtime-actions"><button type="button" onClick={()=>setCount(v=>v+1000)}>PROCESS 1,000 MESSAGES</button><button type="button" onClick={()=>setCount(0)}>RESET</button></div><div className="metric-strip"><Metric label="MESSAGES" value={count}/><Metric label="CONCEPTUAL ALLOCS" value={mode==="REUSE"?Math.ceil(count/100):count*3}/><Metric label="GC / FREE PRESSURE" value={mode==="REUSE"?"LOWER":"HIGHER"}/><Metric label="PROOF" value="PROFILE FIRST"/></div></div>}

export function MemoryRetentionLab(){const[edges,setEdges]=useState(["cache → session","session → listener","listener → page"]);const remove=()=>setEdges(v=>v.slice(0,-1));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={edges.length<3?"live-dot":"alert-dot"}/> MEMORY RETENTION GRAPH</div><button type="button" className="mode-button" disabled={!edges.length} onClick={remove}>REMOVE LAST EDGE</button></div><div className="retention-graph"><b>GC ROOT</b>{edges.map(x=><span key={x}>→ {x}</span>)}<strong>{edges.length===3?"PAGE RETAINED":"PAGE RECLAIMABLE"}</strong></div><p className="lab-caption">Reachability—not usefulness—keeps managed objects alive. Native code expresses the same lifetime pressure through owners and references.</p></div>}

export function LocalityLab(){const[array,setArray]=useState(true);const[visits,setVisits]=useState(0);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={array?"live-dot":"alert-dot"}/> LOCALITY / POINTER CHASING</div><button type="button" className="mode-button" aria-pressed={array} onClick={()=>{setArray(!array);setVisits(0)}}>{array?"CONTIGUOUS ARRAY":"LINKED NODES"}</button></div><div className={`memory-cells ${array?"contiguous":"scattered"}`}>{Array.from({length:8},(_,i)=><span className={i<visits?"visited":""} key={i}>{i}</span>)}</div><div className="runtime-actions"><button type="button" disabled={visits===8} onClick={()=>setVisits(v=>v+1)}>VISIT NEXT</button><button type="button" onClick={()=>setVisits(0)}>RESET</button></div><div className="metric-strip"><Metric label="BIG-O" value="O(n)"/><Metric label="CACHE LINES (MODEL)" value={array?2:Math.max(1,visits)}/><Metric label="POINTER LOADS" value={array?0:visits}/><Metric label="PREFETCH" value={array?"FRIENDLY":"HARD"}/></div></div>}

export function FalseSharingLab(){const[separate,setSeparate]=useState(false);const[steps,setSteps]=useState(0);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={separate?"live-dot":"alert-dot"}/> FALSE SHARING</div><button type="button" className="mode-button" aria-pressed={separate} onClick={()=>{setSeparate(!separate);setSteps(0)}}>{separate?"SEPARATE LINES":"SAME CACHE LINE"}</button></div><div className="cache-lines"><div><b>CORE A</b><span>counterA</span></div><i>{separate?"independent":"↔ invalidations ↔"}</i><div><b>CORE B</b><span>counterB</span></div></div><div className="runtime-actions"><button type="button" onClick={()=>setSteps(v=>v+1)}>WRITE BOTH COUNTERS</button></div><div className="metric-strip"><Metric label="LOGICAL CONTENTION" value="NONE"/><Metric label="MODELED INVALIDATIONS" value={separate?0:steps*2}/><Metric label="CACHE LINE SIZE" value="ARCH-DEPENDENT"/><Metric label="VERIFY WITH" value="PROFILER"/></div></div>}
