"use client";
import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const changes=[
  ["Finance","Change tax rules","PricingPolicy"],["Marketing","Change discount rules","PricingPolicy"],["Payments","Switch payment provider","PaymentProcessor"],["Operations","Change log format","Operational logging"],["Product","Change order validation","OrderValidator"],["Notifications","Add WhatsApp confirmation","NotificationService"],["Fulfillment","Retry inventory reservation","InventoryService"],
] as const;
export function ResponsibilityPressureLab(){const[step,setStep]=useState(0);const[refactored,setRefactored]=useState(false);const active=changes.slice(0,step+1);return <div className="srp-pressure lab-panel"><div className="lab-toolbar"><div><span className={!refactored&&step>2?"alert-dot":"live-dot"}/> CHANGE PRESSURE</div><span>{refactored?"FOCUSED MODULES":"MONOLITH"}</span></div><div className={`srp-radar ${refactored?"refactored":""}`}><div className="change-sources">{active.map(([actor,request],i)=><button type="button" key={actor} style={{"--source-index":i} as React.CSSProperties}><small>{actor}</small><b>{request}</b><i/></button>)}</div><div className="srp-core"><small>{refactored?"ORCHESTRATOR":"ALL RESPONSIBILITIES"}</small><b>{refactored?"CheckoutService":"OrderService"}</b><code>{refactored?"coordinate checkout":"validate · price · reserve · save\ncharge · notify · analyze · invoice"}</code></div>{refactored?<div className="focused-modules">{Array.from(new Set(active.map(item=>item[2]))).map(name=><span key={name}>{name}</span>)}</div>:null}</div><div className="object-metrics">{(refactored?[["RESPONSIBILITIES","1 coherent"],["REASONS TO CHANGE","1"],["DEPENDENCIES","delegated"],["TEST SETUP","focused"],["BLAST RADIUS","LOW"]]:[["RESPONSIBILITIES",String(8)],["REASONS TO CHANGE",String(step+1)],["DEPENDENCIES","9"],["TEST SETUP","HEAVY"],["BLAST RADIUS",step>2?"HIGH":"RISING"]]).map(([k,v])=><span key={k}><small>{k}</small><b className={v==="HIGH"||v==="HEAVY"?"bad":""}>{v}</b></span>)}</div><div className="srp-actions"><button className="quiet-lab-button" type="button" onClick={()=>{setRefactored(false);setStep(value=>Math.min(value+1,changes.length-1))}} disabled={step===changes.length-1}>ADD CHANGE PRESSURE</button><button className="lab-button" type="button" onClick={()=>setRefactored(!refactored)}>{refactored?<Rotate/>:<ArrowRight/>}{refactored?"RESTORE MONOLITH":"REFACTOR BOUNDARIES"}</button></div></div>}

const methods=[
  ["validateOrder()","OrderValidator","Rules about whether an order may enter checkout change together."],
  ["calculateTax()","PricingPolicy","Tax and discount are pricing policies driven by Finance and Marketing."],
  ["calculateDiscount()","PricingPolicy","Keeping related pricing decisions together preserves cohesion."],
  ["reserveInventory()","InventoryService","Reservation and retry policy belong to the inventory capability."],
  ["saveOrder()","OrderRepository","Persistence mapping changes for storage reasons."],
  ["chargeCard()","PaymentProcessor","The caller needs charge semantics, not one provider."],
  ["sendConfirmationEmail()","NotificationService","Channel and template changes should not edit checkout."],
  ["generateInvoice()","InvoiceService","Invoice formatting is a finance/document responsibility."],
  ["trackAnalytics()","AnalyticsTracker","Event schemas and destinations change independently."],
] as const;
const modules=["CheckoutService","OrderValidator","PricingPolicy","InventoryService","OrderRepository","PaymentProcessor","NotificationService","InvoiceService","AnalyticsTracker"];
export function ResponsibilityRefactorLab(){const[index,setIndex]=useState(0);const[pick,setPick]=useState<string|null>(null);const item=methods[index];const correct=pick===item[1];function next(){setIndex(value=>(value+1)%methods.length);setPick(null)}return <div className="responsibility-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> MOVE THE METHOD</div><span>{index+1} / {methods.length}</span></div><div className="responsibility-layout"><div className="method-card"><small>FROM OrderService</small><h3>{item[0]}</h3><p>Choose the module with the most coherent source of change.</p></div><div className="module-grid">{modules.map(module=><button type="button" aria-pressed={pick===module} onClick={()=>setPick(module)} key={module}>{module}</button>)}</div></div>{pick?<div className={`lab-feedback ${correct?"success":"error"}`}><b>{correct?"COHESIVE BOUNDARY":"RECHECK THE CHANGE SOURCE"}</b><p>{correct?item[2]:`${item[1]} is the stronger default here. ${item[2]}`}</p><button className="lab-button" type="button" onClick={correct?next:()=>setPick(null)}>{correct?"NEXT METHOD":"TRY AGAIN"}<ArrowRight/></button></div>:null}</div>}

export function BlastRadiusLab(){const[refactored,setRefactored]=useState(false);const[change,setChange]=useState(0);const active=changes[change];return <div className="blast-lab lab-panel"><div className="lab-toolbar"><div><span className={refactored?"live-dot":"alert-dot"}/> CHANGE SIMULATOR</div><div className="mode-toggle"><button type="button" aria-pressed={!refactored} onClick={()=>setRefactored(false)}>MONOLITH</button><button type="button" aria-pressed={refactored} onClick={()=>setRefactored(true)}>REFACTORED</button></div></div><div className="blast-layout"><div className="blast-changes">{changes.slice(0,5).map(([actor,request],i)=><button type="button" aria-pressed={change===i} onClick={()=>setChange(i)} key={request}><small>{actor}</small>{request}</button>)}</div><div className="blast-stage"><span>REQUIREMENT</span><h3>{active[1]}</h3><div className={refactored?"blast-target focused":"blast-target monolith"}><small>FILES TOUCHED</small><b>{refactored?active[2]:"OrderService"}</b>{!refactored?<><i>pricing paths</i><i>checkout tests</i><i>unrelated integrations</i></>:<i>focused tests only</i>}</div><div className="blast-meter"><span>CHANGE BLAST RADIUS</span><b>{refactored?"1 focused module":"1 central module + full integration suite"}</b><em style={{width:refactored?"22%":"90%"}}/></div></div></div></div>}

export function ClassExplosionLab(){const[extreme,setExtreme]=useState(false);return <div className="explosion-lab lab-panel"><div className="lab-toolbar"><div><span className={extreme?"alert-dot":"live-dot"}/> SRP EXTREME CHECK</div><span>{extreme?"NAVIGATION COST HIGH":"COHESIVE BOUNDARY"}</span></div><div className="explosion-classes">{(extreme?["OrderIdValidator","OrderQuantityValidator","OrderAddressValidator","OrderCurrencyValidator","OrderTimestampValidator"]:["OrderValidator"]).map(name=><div key={name}><small>CLASS</small><b>{name}</b><code>validate()</code></div>)}</div><div className="lab-feedback"><b>{extreme?"CLASS COUNT ≠ RESPONSIBILITY QUALITY":"KEEP RELATED RULES TOGETHER"}</b><p>{extreme?"These trivial rules change for the same product-validation reason. Splitting them increases wiring and navigation without isolating independent pressure.":"OrderValidator may contain several validation methods while retaining one coherent reason to change."}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setExtreme(!extreme)}>{extreme?<Rotate/>:<ArrowRight/>}{extreme?"RESTORE COHESION":"OVER-APPLY SRP"}</button></div>}
