"use client";

import { useState } from "react";

const features=["Logging","Retry","Metrics","Auth","Cache"] as const;
export function SubclassExplosionLab(){const[mode,setMode]=useState<"inheritance"|"composition">("inheritance");const[selected,setSelected]=useState<string[]>(["Logging","Retry"]);const toggle=(x:string)=>setSelected(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x]);const combinations=2**selected.length;return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={mode==="composition"?"live-dot":"alert-dot"}/> SUBCLASS EXPLOSION LAB</div><button className="mode-button" type="button" aria-pressed={mode==="composition"} onClick={()=>setMode(mode==="inheritance"?"composition":"inheritance")}>{mode.toUpperCase()}</button></div><div className="feature-toggles">{features.map(x=><button type="button" aria-pressed={selected.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><div className={`wrapper-visual ${mode}`}>{mode==="inheritance"?<>{Array.from({length:Math.min(8,combinations)},(_,n)=><span key={n}>{selected.filter((_,i)=>(n&(1<<i))!==0).join("")||"Base"}Client</span>)}</>:<><b>RealHttpClient</b>{selected.map(x=><span key={x}>{x}(inner)</span>)}</>}</div><div className="metric-strip">{[["FEATURES",selected.length],["COMBINATIONS",combinations],["SUBCLASSES",mode==="inheritance"?combinations:0],["CORE MODIFICATIONS",0]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="lab-caption">Independent optional features create 2ⁿ inheritance combinations. Decorator composition needs one wrapper per feature and assembles only the chosen stack.</p></div>}

const wrapperOrders={"Retry → Logging":{attempts:3,logs:3,scope:"each attempt"},"Logging → Retry":{attempts:3,logs:1,scope:"whole operation"},"Cache → Metrics":{attempts:0,logs:0,scope:"cache + client"},"Metrics → Cache":{attempts:0,logs:0,scope:"cache hit included"}} as const;
export function DecoratorOrderingLab(){const[key,setKey]=useState<keyof typeof wrapperOrders>("Retry → Logging");const x=wrapperOrders[key];return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> DECORATOR ORDERING LAB</div><span>REQUEST ↓ / RESPONSE ↑</span></div><div className="order-options">{Object.keys(wrapperOrders).map(x=><button type="button" aria-pressed={key===x} onClick={()=>setKey(x as keyof typeof wrapperOrders)} key={x}>{x}</button>)}</div><div className="decorator-stack" aria-live="polite"><b>REQUEST</b>{key.split(" → ").map(x=><span key={x}>{x}Client</span>)}<strong>RealClient</strong><i>RESPONSE UNWINDS ↑</i></div><div className="metric-strip">{[["ATTEMPTS",x.attempts],["LOG EVENTS",x.logs],["TIMING SCOPE",x.scope],["CACHE",key.includes("Cache")?"ACTIVE":"NONE"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}

const mappings=[{domain:"Money.minorUnits",vendor:"amount_in_cents"},{domain:"PaymentToken.value",vendor:"source_token"},{domain:"Currency.code",vendor:"currency_code"},{domain:"PaymentDeclined",vendor:"STRIPE_CARD_DECLINED"}] as const;
export function AdapterTranslationLab(){const[mapped,setMapped]=useState<number[]>([]);const toggle=(n:number)=>setMapped(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={mapped.length===4?"live-dot":"alert-dot"}/> ADAPTER TRANSLATION LAB</div><span>{mapped.length}/4 MAPPED</span></div><div className="mapping-view"><div><b>DOMAIN</b>{mappings.map((x,n)=><button type="button" aria-pressed={mapped.includes(n)} onClick={()=>toggle(n)} key={x.domain}>{x.domain}</button>)}</div><i>StripeAdapter</i><div><b>VENDOR SDK</b>{mappings.map((x,n)=><span className={mapped.includes(n)?"mapped":""} key={x.vendor}>{x.vendor}</span>)}</div></div><div className={`lab-feedback ${mapped.length===4?"success":"error"}`} aria-live="polite"><b>{mapped.length===4?"BOUNDARY COMPLETE":"VENDOR DETAIL STILL LEAKS"}</b><p>Translate request shape, units, response semantics, and provider errors. The domain keeps PaymentRequest, Money, PaymentResult, and PaymentDeclined.</p></div></div>}

export function FacadeSimplificationLab(){const[facade,setFacade]=useState(false);const services=["Inventory","Pricing","Payment","Repository","Notification","Analytics"];return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={facade?"live-dot":"alert-dot"}/> FACADE DEPENDENCY SIMPLIFICATION</div><button className="mode-button" type="button" aria-pressed={facade} onClick={()=>setFacade(!facade)}>{facade?"FACADE":"DIRECT COORDINATION"}</button></div><div className={`facade-graph ${facade?"simplified":""}`}><b>Controller</b>{facade?<><i>placeOrder()</i><strong>CheckoutFacade</strong></>:<i>6 dependencies / 9 calls</i>}<div>{services.map(x=><span key={x}>{x}</span>)}</div></div><div className="metric-strip">{[["CALLER DEPENDENCIES",facade?1:6],["SEQUENCE KNOWLEDGE",facade?"NONE":"HIGH"],["PUBLIC OPERATIONS",facade?1:9],["SUBSYSTEMS",6]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="lab-caption">The Facade simplifies entry; it should not absorb every subsystem’s business logic, state, and responsibility into a god object.</p></div>}

type Job={id:number;name:string;status:"QUEUED"|"RUNNING"|"SUCCEEDED"|"FAILED"};
export function CommandQueueLab(){const[jobs,setJobs]=useState<Job[]>([]);const[nextId,setNextId]=useState(1);const enqueue=()=>{const names=["ReserveSeat","CapturePayment","SendEmail"];setJobs([...jobs,{id:nextId,name:names[(nextId-1)%3],status:"QUEUED"}]);setNextId(nextId+1)};const execute=()=>{const index=jobs.findIndex(x=>x.status==="QUEUED");if(index<0)return;setJobs(jobs.map((x,n)=>n===index?{...x,status:x.name==="CapturePayment"&&x.id%2===0?"FAILED":"SUCCEEDED"}:x))};const retry=()=>{const index=jobs.findIndex(x=>x.status==="FAILED");if(index<0)return;setJobs(jobs.map((x,n)=>n===index?{...x,status:"QUEUED"}:x))};const cancel=()=>{const index=jobs.map(x=>x.status).lastIndexOf("QUEUED");if(index>=0)setJobs(jobs.filter((_,n)=>n!==index))};return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> COMMAND QUEUE / LIFECYCLE</div><span>{jobs.length} COMMANDS</span></div><div className="command-controls"><button type="button" onClick={enqueue}>ENQUEUE</button><button type="button" onClick={execute} disabled={!jobs.some(x=>x.status==="QUEUED")}>EXECUTE NEXT</button><button type="button" onClick={retry} disabled={!jobs.some(x=>x.status==="FAILED")}>RETRY FAILED</button><button type="button" onClick={cancel} disabled={!jobs.some(x=>x.status==="QUEUED")}>CANCEL QUEUED</button></div><div className="command-queue" aria-live="polite">{jobs.length?jobs.map(x=><div key={x.id}><span>#{x.id}</span><b>{x.name}Command</b><em className={x.status.toLowerCase()}>{x.status}</em></div>):<p>Queue empty. A command is an action represented beyond the call that created it.</p>}</div></div>}

type Edit={before:string;after:string;name:string};
export function UndoRedoLab(){const[text,setText]=useState("LLD");const[history,setHistory]=useState<Edit[]>([]);const[cursor,setCursor]=useState(0);const apply=(name:string,after:string)=>{const edit={before:text,after,name};setHistory([...history.slice(0,cursor),edit]);setCursor(cursor+1);setText(after)};const undo=()=>{if(!cursor)return;const edit=history[cursor-1];setText(edit.before);setCursor(cursor-1)};const redo=()=>{if(cursor>=history.length)return;const edit=history[cursor];setText(edit.after);setCursor(cursor+1)};return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> UNDO / REDO HISTORY</div><span>{cursor}/{history.length}</span></div><div className="document-state"><span>DOCUMENT</span><b>{text || "∅"}</b></div><div className="command-controls"><button type="button" onClick={()=>apply("InsertText",text+"!")}>INSERT !</button><button type="button" onClick={()=>apply("DeleteText",text.slice(0,-1))} disabled={!text}>DELETE</button><button type="button" onClick={()=>apply("ReplaceText","DESIGN")}>REPLACE</button><button type="button" onClick={undo} disabled={!cursor}>UNDO</button><button type="button" onClick={redo} disabled={cursor>=history.length}>REDO</button></div><div className="history-track">{history.map((x,n)=><span className={n<cursor?"applied":"future"} key={`${x.name}-${n}`}>{x.name}</span>)}</div><p className="lab-caption">History owns executed commands. Snapshot undo is accurate but uses memory; inverse operations can be smaller but harder to make correct for side effects.</p></div>}

const flags=["Paid","Cancelled","Shipped","Delivered","Refunded"] as const;
function validFlags(values:string[]){if(values.includes("Cancelled")&&values.some(x=>["Shipped","Delivered"].includes(x)))return false;if(values.includes("Delivered")&&!values.includes("Shipped"))return false;if(values.includes("Shipped")&&!values.includes("Paid"))return false;if(values.includes("Refunded")&&!values.includes("Paid"))return false;return true}
export function BooleanExplosionLab(){const[values,setValues]=useState<string[]>([]);const[stateMode,setStateMode]=useState(false);const toggle=(x:string)=>setValues(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x]);const valid=validFlags(values);return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className={stateMode||valid?"live-dot":"alert-dot"}/> BOOLEAN EXPLOSION LAB</div><button className="mode-button" type="button" aria-pressed={stateMode} onClick={()=>setStateMode(!stateMode)}>{stateMode?"ONE ORDER STATE":"FIVE BOOLEANS"}</button></div>{stateMode?<div className="single-state"><span>OrderState</span><b>{values.includes("Delivered")?"DELIVERED":values.includes("Cancelled")?"CANCELLED":values.includes("Shipped")?"SHIPPED":values.includes("Paid")?"PAID":"PENDING"}</b></div>:<div className="feature-toggles">{flags.map(x=><button type="button" aria-pressed={values.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div>}<div className="metric-strip">{[["BOOLEAN COMBINATIONS",32],["CURRENT FLAGS",values.length],["CURRENT VALID",stateMode||valid?"YES":"NO"],["MODEL",stateMode?"EXCLUSIVE STATE":"INDEPENDENT FLAGS"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className={`lab-feedback ${stateMode||valid?"success":"error"}`}><b>{stateMode?"INVALID COMBINATIONS REMOVED":valid?"CURRENT COMBINATION VALID":"IMPOSSIBLE ORDER"}</b><p>Cancelled + Delivered and Refunded without Paid reveal that independent booleans do not model mutually constrained lifecycle states.</p></div></div>}

const transitions:Record<string,Record<string,string>>={PENDING:{PAY:"PAID",CANCEL:"CANCELLED"},PAID:{SHIP:"SHIPPED",REFUND:"REFUNDED"},SHIPPED:{DELIVER:"DELIVERED"},DELIVERED:{},CANCELLED:{},REFUNDED:{}};
export function StateTransitionLab(){const[state,setState]=useState("PENDING");const[mode,setMode]=useState<"enum"|"objects">("enum");const[message,setMessage]=useState("Choose a valid action.");const act=(action:string)=>{const next=transitions[state]?.[action];if(next){setState(next);setMessage(`${state} → ${action} → ${next}`)}else setMessage(`InvalidTransition: ${action} is not allowed from ${state}`)};const reset=()=>{setState("PENDING");setMessage("Choose a valid action.")};return <div className="advanced-pattern-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> STATE TRANSITION / ENUM VS STATE</div><button className="mode-button" type="button" aria-pressed={mode==="objects"} onClick={()=>setMode(mode==="enum"?"objects":"enum")}>{mode==="enum"?"ENUM + SWITCH":"STATE OBJECTS"}</button></div><div className="state-path">{["PENDING","PAID","SHIPPED","DELIVERED"].map(x=><span className={state===x?"active":""} key={x}>{x}</span>)}</div><div className="state-actions">{["PAY","SHIP","DELIVER","CANCEL","REFUND"].map(x=><button type="button" onClick={()=>act(x)} aria-disabled={!transitions[state]?.[x]} key={x}>{x}</button>)}<button type="button" onClick={reset}>RESET</button></div><div className="lab-feedback success" aria-live="polite"><b>{state}</b><p>{message}</p></div><div className="metric-strip">{[["MODEL",mode==="enum"?"CENTRAL SWITCH":"DELEGATED STATE"],["ADD RETURN_REQUESTED",mode==="enum"?"5 SWITCHES":"1 STATE + TRANSITIONS"],["STATE DATA",state==="SHIPPED"?"trackingNumber":"none"],["CONCURRENCY","NOT SOLVED"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}
