"use client";
import {useMemo,useState} from "react";

const Button=({active=false,children,onClick,disabled=false}:{active?:boolean;children:React.ReactNode;onClick:()=>void;disabled?:boolean})=><button type="button" aria-pressed={active} disabled={disabled} onClick={onClick}>{children}</button>;
const Feedback=({ok,title,children}:{ok:boolean;title:string;children:React.ReactNode})=><div className={`lab-feedback ${ok?"success":"error"}`} aria-live="polite"><b>{title}</b><p>{children}</p></div>;

export function ParkingClarificationLab(){const[selected,setSelected]=useState<string[]>([]);const questions:readonly [string,"CORE"|"USEFUL"|"OUT OF V1"][]=[["Multiple floors?","CORE"],["Vehicle and spot types?","CORE"],["Pricing and payment?","CORE"],["Concurrent arrivals?","USEFUL"],["Display availability?","USEFUL"],["Lost ticket?","USEFUL"],["Advance reservations?","OUT OF V1"],["Valet / subscriptions?","OUT OF V1"],["EV charging?","OUT OF V1"]];const toggle=(q:string)=>setSelected(v=>v.includes(q)?v.filter(x=>x!==q):[...v,q]);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>CLARIFYING QUESTIONS LAB</div><span>{selected.length}/{questions.length} ASKED</span></div><div className="clarification-grid">{questions.map(([q,kind])=><button type="button" aria-pressed={selected.includes(q)} onClick={()=>toggle(q)} key={q}><b>{q}</b><span>{selected.includes(q)?kind:"ASK INTERVIEWER"}</span></button>)}</div><Feedback ok={selected.length>=3} title={selected.length>=3?"SCOPE SIGNALS DISCOVERED":"ASK BEFORE MODELING"}>Core questions define v1; useful questions expose pressure; out-of-scope answers protect the interview clock.</Feedback></div>}

export function ParkingInvariantOwnerLab(){const[owner,setOwner]=useState<Record<string,string>>({});const rules:readonly [string,string][]=[["one vehicle per spot","ParkingSpot"],["one spot per vehicle","ParkingLot"],["ticket binds vehicle + spot","ParkingTicket"],["release exactly once","ParkingLot.exit"]];const assign=(rule:string,expected:string)=>setOwner(v=>({...v,[rule]:expected}));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>INVARIANT OWNER LAB</div><span>{Object.keys(owner).length}/4 OWNED</span></div><div className="invariant-owner-grid">{rules.map(([rule,expected])=><div key={rule}><b>{rule}</b><span>{owner[rule]??"UNASSIGNED"}</span><button type="button" onClick={()=>assign(rule,expected)}>ASSIGN {expected}</button></div>)}</div><p className="lab-caption">An owner is the smallest cohesive boundary able to enforce the rule on every mutation—not merely the object named in the sentence.</p></div>}

export function SpotAllocationLab(){const[vehicle,setVehicle]=useState<"BIKE"|"CAR"|"TRUCK">("CAR");const[policy,setPolicy]=useState<"FIRST"|"NEAREST"|"LOWEST">("FIRST");const spots=[{id:"B02",type:"BIKE",floor:1,distance:8},{id:"C12",type:"COMPACT",floor:2,distance:2},{id:"C03",type:"COMPACT",floor:1,distance:6},{id:"L01",type:"LARGE",floor:1,distance:12}];const compatible=spots.filter(s=>vehicle==="BIKE"||vehicle==="CAR"?s.type!=="BIKE"||vehicle==="BIKE":s.type==="LARGE");const sorted=[...compatible].sort((a,b)=>policy==="NEAREST"?a.distance-b.distance:policy==="LOWEST"?a.floor-b.floor:a.id.localeCompare(b.id));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>SPOT ALLOCATION LAB</div><span>{policy} AVAILABLE</span></div><div className="runtime-actions">{(["BIKE","CAR","TRUCK"] as const).map(x=><Button key={x} active={vehicle===x} onClick={()=>setVehicle(x)}>{x}</Button>)}{(["FIRST","NEAREST","LOWEST"] as const).map(x=><Button key={x} active={policy===x} onClick={()=>setPolicy(x)}>{x}</Button>)}</div><div className="spot-grid">{spots.map(s=><div key={s.id} className={sorted[0]?.id===s.id?"selected":""}><b>{s.id}</b><span>{s.type} · F{s.floor}</span><small>{s.distance}m from gate</small></div>)}</div><Feedback ok={!!sorted[0]} title={sorted[0]?`SELECT ${sorted[0].id}`:"NO COMPATIBLE SPOT"}>Compatibility is an invariant; ordering is a replaceable policy only after allocation behavior varies.</Feedback></div>}

export function ConcurrentLastSpotRaceLab(){const[safe,setSafe]=useState(false);const[step,setStep]=useState(0);const unsafe=["Gate A reads C12 = AVAILABLE","Gate B reads C12 = AVAILABLE","Gate A writes OCCUPIED(A)","Gate B writes OCCUPIED(B) — A lost"];const guarded=["Gate A enters atomic tryOccupy(C12)","Gate A changes AVAILABLE → OCCUPIED","Gate B enters after A","Gate B receives ALREADY_OCCUPIED"];const rows=safe?guarded:unsafe;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={safe?"live-dot":"alert-dot"}/>CONCURRENT LAST-SPOT RACE LAB</div><Button active={safe} onClick={()=>{setSafe(!safe);setStep(0)}}>{safe?"SYNCHRONIZED":"UNSAFE"}</Button></div><div className="lifetime-track">{rows.map((x,i)=><span className={i<step?"release":""} key={x}>{i+1}. {x}</span>)}</div><div className="runtime-actions"><Button disabled={step===4} onClick={()=>setStep(v=>v+1)}>NEXT INTERLEAVING</Button><Button onClick={()=>setStep(0)}>RESET</Button></div><Feedback ok={safe||step<4} title={safe?"ONE LINEARIZATION POINT":step===4?"DOUBLE ASSIGNMENT":"RACE NOT YET OBSERVED"}>Both compatibility check and occupancy transition belong inside one atomic domain operation.</Feedback></div>}

export function ParkingFlowSimulator(){const[step,setStep]=useState(0);const[paymentOk,setPaymentOk]=useState(true);const stages=["VEHICLE VALIDATED","C12 SELECTED","SPOT OCCUPIED","TICKET ACTIVE","PAYMENT RECORDED","TICKET CLOSED · C12 RELEASED"];const blocked=step===4&&!paymentOk;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={blocked?"alert-dot":"live-dot"}/>PARKING FLOW SIMULATOR</div><span>{step}/6</span></div><div className="architecture-flow">{stages.map((x,i)=><div className={i<step?"done":i===step?"active":""} key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><div className="runtime-actions"><Button active={paymentOk} onClick={()=>setPaymentOk(!paymentOk)}>{paymentOk?"PAYMENT SUCCEEDS":"PAYMENT FAILS"}</Button><Button disabled={step===6||blocked} onClick={()=>setStep(v=>v+1)}>ADVANCE</Button><Button onClick={()=>setStep(0)}>RESET</Button></div><Feedback ok={!blocked} title={blocked?"EXIT BLOCKED · TICKET REMAINS ACTIVE":step===6?"RELEASED EXACTLY ONCE":"INVARIANTS HOLD"}>A failed payment cannot close the ticket or release the occupied spot.</Feedback></div>}

type SplitMode="EQUAL"|"EXACT"|"PERCENT";
export function SplitCalculatorLab(){const[mode,setMode]=useState<SplitMode>("EQUAL");const values=mode==="EQUAL"?[40000,40000,40000]:mode==="EXACT"?[50000,40000,30000]:[60000,36000,24000];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>SPLIT CALCULATOR LAB</div><span>₹1,200.00 · PAYER A</span></div><div className="runtime-actions">{(["EQUAL","EXACT","PERCENT"] as const).map(x=><Button key={x} active={mode===x} onClick={()=>setMode(x)}>{x}</Button>)}</div><div className="balance-bars">{["A","B","C"].map((u,i)=><div key={u}><b>{u}</b><span style={{width:`${values[i]/600}%`}}/><strong>₹{(values[i]/100).toFixed(2)}{mode==="PERCENT"&&` · ${[50,30,20][i]}%`}</strong></div>)}</div><Feedback ok={values.reduce((a,b)=>a+b,0)===120000} title="ALLOCATION SUM = EXPENSE">Money uses integer paise. Percentage remainder is assigned deterministically after floor rounding.</Feedback></div>}

export function BalanceLedgerLab(){const[count,setCount]=useState(0);const expenses=["A paid ₹1,200 for A/B/C","B paid ₹600 for B/C","C settled ₹200 to A"];const ledger=count===0?[]:count===1?["B → A ₹400","C → A ₹400"]:count===2?["B → A ₹400","C → A ₹400","C → B ₹300"]:["B → A ₹400","C → A ₹200","C → B ₹300"];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>BALANCE GRAPH / LEDGER LAB</div><span>{count} EVENTS</span></div><div className="runtime-actions"><Button disabled={count===3} onClick={()=>setCount(v=>v+1)}>POST NEXT EXPENSE</Button><Button onClick={()=>setCount(0)}>RESET</Button></div><div className="ledger-view"><div>{expenses.map((x,i)=><span className={i<count?"posted":""} key={x}>{i+1}. {x}</span>)}</div><i>immutable events → pairwise balances</i><div>{ledger.map(x=><b key={x}>{x}</b>)}</div></div><p className="lab-caption">Editing can reverse the old immutable expense and append a corrected one, preserving auditability at added complexity.</p></div>}

export function DebtSimplificationLab(){const[mode,setMode]=useState<"RAW"|"NETTED"|"SIMPLIFIED">("RAW");const lines={RAW:["B → A ₹400","C → A ₹200","C → B ₹300"],NETTED:["B → A ₹100","C → A ₹500"],SIMPLIFIED:["C → A ₹500","B → A ₹100"]}[mode];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>DEBT SIMPLIFICATION LAB</div><span>{mode}</span></div><div className="runtime-actions">{(["RAW","NETTED","SIMPLIFIED"] as const).map(x=><Button key={x} active={mode===x} onClick={()=>setMode(x)}>{x}</Button>)}</div><div className="debt-graph">{lines.map(x=><span key={x}>{x}</span>)}</div><Feedback ok title={`${lines.length} TRANSFERS`}>Simplification preserves each user&apos;s net balance; the resulting graph is not unique and must not rewrite expense history.</Feedback></div>}

type SeatState="AVAILABLE"|"HELD"|"BOOKED";
export function ShowSeatStateGrid(){const[seats,setSeats]=useState<Record<string,SeatState>>({A1:"AVAILABLE",A2:"AVAILABLE",A3:"BOOKED",B1:"AVAILABLE",B2:"HELD",B3:"AVAILABLE"});const[selected,setSelected]=useState("A1");const transition=(to:SeatState)=>setSeats({...seats,[selected]:to});return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>SHOW SEAT-STATE GRID</div><span>SHOW 19:30 · SCREEN 2</span></div><div className="seat-grid">{Object.entries(seats).map(([id,state])=><button type="button" aria-pressed={selected===id} aria-label={`${id}: ${state}`} data-state={state} onClick={()=>setSelected(id)} key={id}><b>{id}</b><span>{state}</span></button>)}</div><div className="runtime-actions"><Button disabled={seats[selected]!=="AVAILABLE"} onClick={()=>transition("HELD")}>HOLD</Button><Button disabled={seats[selected]!=="HELD"} onClick={()=>transition("BOOKED")}>CONFIRM</Button><Button disabled={seats[selected]!=="HELD"} onClick={()=>transition("AVAILABLE")}>EXPIRE HOLD</Button></div><p className="lab-caption">Physical Seat describes row/type. ShowSeat owns availability for one show—never Seat.isBooked.</p></div>}

export function DoubleBookingRaceLab(){const[atomic,setAtomic]=useState(false);const[step,setStep]=useState(0);const rows=atomic?["A atomically holds A1","A1 becomes HELD by A","B attempts atomic hold","B receives UNAVAILABLE"]:["A reads A1 AVAILABLE","B reads A1 AVAILABLE","A writes HELD(A)","B writes HELD(B) — A overwritten"];return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={atomic?"live-dot":"alert-dot"}/>DOUBLE-BOOKING RACE LAB</div><Button active={atomic} onClick={()=>{setAtomic(!atomic);setStep(0)}}>{atomic?"ATOMIC tryHoldSeat":"CHECK THEN ACT"}</Button></div><div className="lifetime-track">{rows.map((x,i)=><span className={i<step?"release":""} key={x}>{i+1}. {x}</span>)}</div><div className="runtime-actions"><Button disabled={step===4} onClick={()=>setStep(v=>v+1)}>NEXT</Button><Button onClick={()=>setStep(0)}>RESET</Button></div><Feedback ok={atomic||step<4} title={atomic?"ONE WINNER":step===4?"DOUBLE BOOKED":"RUN THE INTERLEAVING"}>The repository boundary must compare and transition show-seat state atomically.</Feedback></div>}

export function MultiSeatAtomicHoldLab(){const[atomic,setAtomic]=useState(true);const[result,setResult]=useState("READY");const run=()=>setResult(atomic?"REJECTED · A1/A2 unchanged":"PARTIAL · A1/A2 held, A3 unavailable");return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={atomic?"live-dot":"alert-dot"}/>MULTI-SEAT ATOMIC HOLD LAB</div><Button active={atomic} onClick={()=>{setAtomic(!atomic);setResult("READY")}}>{atomic?"ALL OR NOTHING":"LOOP PER SEAT"}</Button></div><div className="seat-grid">{["A1 AVAILABLE","A2 AVAILABLE","A3 BOOKED"].map(x=><div key={x}><b>{x.split(" ")[0]}</b><span>{x.split(" ")[1]}</span></div>)}</div><div className="runtime-actions"><Button onClick={run}>HOLD A1 + A2 + A3</Button></div><Feedback ok={atomic} title={result}>Validate every seat and commit the group transition under one boundary, or roll back all changes.</Feedback></div>}

export function BookingLifecycleLab(){const[state,setState]=useState<"AVAILABLE"|"HELD"|"PAID"|"BOOKED"|"EXPIRED">("AVAILABLE");const[payOk,setPayOk]=useState(true);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={state==="EXPIRED"?"alert-dot":"live-dot"}/>BOOKING LIFECYCLE LAB</div><span>{state}</span></div><div className="runtime-actions"><Button disabled={state!=="AVAILABLE"} onClick={()=>setState("HELD")}>HOLD</Button><Button disabled={state!=="HELD"} active={payOk} onClick={()=>payOk?setState("PAID"):setState("HELD")}>{payOk?"PAY":"PAY FAILS"}</Button><Button disabled={state!=="PAID"} onClick={()=>setState("BOOKED")}>CONFIRM</Button><Button disabled={state!=="HELD"} onClick={()=>setState("EXPIRED")}>ADVANCE CLOCK</Button><Button onClick={()=>setPayOk(!payOk)}>TOGGLE PAYMENT</Button><Button onClick={()=>setState("AVAILABLE")}>RESET</Button></div><Feedback ok={state!=="EXPIRED"} title={state}>{state==="HELD"&&!payOk?"Payment failure preserves the unexpired hold for a documented retry window.":"Clock and payment gateway are injected, keeping timeout and failure tests deterministic."}</Feedback></div>}

type Strategy="NEAREST"|"DIRECTION"|"LOAD";
export function ElevatorSchedulerLab(){const[strategy,setStrategy]=useState<Strategy>("NEAREST");const[floor,setFloor]=useState(9);const cars=[{id:"E1",floor:2,dir:"UP",load:4},{id:"E2",floor:8,dir:"UP",load:7},{id:"E3",floor:14,dir:"DOWN",load:1}];const scored=[...cars].sort((a,b)=>strategy==="NEAREST"?Math.abs(a.floor-floor)-Math.abs(b.floor-floor):strategy==="LOAD"?a.load-b.load:(a.dir==="UP"&&a.floor<=floor?-10:0)-(b.dir==="UP"&&b.floor<=floor?-10:0));return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>ELEVATOR SCHEDULER LAB</div><span>HALL CALL ↑ F{floor}</span></div><div className="runtime-actions">{(["NEAREST","DIRECTION","LOAD"] as const).map(x=><Button key={x} active={strategy===x} onClick={()=>setStrategy(x)}>{x}</Button>)}<Button onClick={()=>setFloor(floor===15?1:floor+1)}>FLOOR +1</Button></div><div className="elevator-cars">{cars.map(c=><div className={c.id===scored[0].id?"selected":""} key={c.id}><b>{c.id}</b><span>F{c.floor} · {c.dir}</span><small>load {c.load}/8</small></div>)}</div><Feedback ok title={`DISPATCH ${scored[0].id}`}>HallRequest carries floor + direction; a CarRequest carries elevatorId + destination.</Feedback></div>}

export function ElevatorMovementSimulator(){const[floor,setFloor]=useState(3);const[door,setDoor]=useState<"CLOSED"|"OPEN">("CLOSED");const[up,setUp]=useState([7,11]);const tick=()=>{if(door==="OPEN")setDoor("CLOSED");else if(up.length&&floor<up[0])setFloor(floor+1);else if(up[0]===floor){setDoor("OPEN");setUp(up.slice(1))}};return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>ELEVATOR MOVEMENT SIMULATOR</div><span>DETERMINISTIC TICK</span></div><div className="elevator-shaft"><div style={{bottom:`${(floor-1)/14*88}%`}}><b>E1 · F{floor}</b><span>{door} · {up.length?"MOVING UP":"IDLE"}</span></div>{[1,3,5,7,9,11,13,15].map(x=><i key={x}>F{x}</i>)}</div><div className="runtime-actions"><Button onClick={tick}>TICK</Button><Button onClick={()=>setUp([...up,15].sort((a,b)=>a-b))}>CAR REQUEST F15</Button><Button onClick={()=>{setFloor(3);setDoor("CLOSED");setUp([7,11])}}>RESET</Button></div><p className="lab-caption">Ascending stops use an ordered set; descending stops use reverse order. A single-owner event loop avoids shared-memory races.</p></div>}

export function OrthogonalStateLab(){const[motion,setMotion]=useState<"IDLE"|"MOVING_UP"|"MOVING_DOWN"|"OUT_OF_SERVICE">("IDLE");const[door,setDoor]=useState<"OPEN"|"CLOSED"|"OPENING"|"CLOSING">("CLOSED");const valid=!(motion.startsWith("MOVING")&&door!=="CLOSED");return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={valid?"live-dot":"alert-dot"}/>ORTHOGONAL STATE LAB</div><span>MOTION × DOOR</span></div><div className="runtime-actions">{(["IDLE","MOVING_UP","MOVING_DOWN","OUT_OF_SERVICE"] as const).map(x=><Button key={x} active={motion===x} onClick={()=>setMotion(x)}>{x}</Button>)}{(["OPEN","CLOSED","OPENING","CLOSING"] as const).map(x=><Button key={x} active={door===x} onClick={()=>setDoor(x)}>{x}</Button>)}</div><div className="metric-strip"><div><span>MOTION</span><b>{motion}</b></div><div><span>DOOR</span><b>{door}</b></div><div><span>COMBINATION</span><b>{valid?"VALID":"FORBIDDEN"}</b></div></div><Feedback ok={valid} title={valid?"ORTHOGONAL STATES":"DOOR MUST BE CLOSED WHILE MOVING"}>Separate state machines avoid one exploding enum while invariants constrain illegal combinations.</Feedback></div>}

const pipeline=["REQUEST","PREFERENCE","RENDER","CHANNEL","PROVIDER","SEND","RESULT"];
export function NotificationPipelineLab(){const[step,setStep]=useState(0);const[allowed,setAllowed]=useState(true);const stopped=!allowed&&step>=1;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={stopped?"alert-dot":"live-dot"}/>NOTIFICATION PIPELINE LAB</div><span>{step}/7</span></div><div className="architecture-flow">{pipeline.map((x,i)=><div className={i<step?"done":i===step?"active":""} key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><div className="runtime-actions"><Button active={allowed} onClick={()=>{setAllowed(!allowed);setStep(0)}}>{allowed?"RECIPIENT ALLOWS":"PREFERENCE OFF"}</Button><Button disabled={step===7||stopped} onClick={()=>setStep(v=>v+1)}>ADVANCE</Button><Button onClick={()=>setStep(0)}>RESET</Button></div><Feedback ok={!stopped} title={stopped?"SKIPPED_BY_PREFERENCE":step===7?"SENT":"PIPELINE READY"}>Preferences are evaluated before rendering sensitive message content.</Feedback></div>}

export function MultiChannelDeliveryLab(){const[selected,setSelected]=useState<string[]>(["EMAIL","SMS","PUSH"]);const[pushAllowed,setPushAllowed]=useState(false);const toggle=(x:string)=>setSelected(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/>MULTI-CHANNEL DELIVERY LAB</div><span>ORDER-42</span></div><div className="runtime-actions">{["EMAIL","SMS","PUSH"].map(x=><Button key={x} active={selected.includes(x)} onClick={()=>toggle(x)}>{x}</Button>)}<Button active={pushAllowed} onClick={()=>setPushAllowed(!pushAllowed)}>PUSH PREFERENCE</Button></div><div className="channel-results">{["EMAIL","SMS","PUSH"].map(x=><div key={x}><b>{x}</b><span>{!selected.includes(x)?"NOT_REQUESTED":x==="PUSH"&&!pushAllowed?"SKIPPED_BY_PREFERENCE":"SENT"}</span><small>{x==="EMAIL"?"SendGrid":x==="SMS"?"Twilio":"SNS"}</small></div>)}</div><p className="lab-caption">Channel is user intent; provider is replaceable infrastructure. Results are explicit—not a lossy boolean.</p></div>}

export function ProviderFallbackLab(){const[failure,setFailure]=useState<"TRANSIENT"|"PERMANENT"|"NONE">("TRANSIENT");const[attempt,setAttempt]=useState(0);const result=useMemo(()=>failure==="NONE"?"SENT · TWILIO":failure==="PERMANENT"?"FAILED · INVALID_NUMBER":attempt===0?"FAILED_TRANSIENT · RETRYABLE":attempt===1?"SENT · SNS FALLBACK":"DUPLICATE_SUPPRESSED",[failure,attempt]);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={result.startsWith("SENT")?"live-dot":"alert-dot"}/>PROVIDER FAILURE / FALLBACK LAB</div><span>notificationId N-42 · attempt {attempt}</span></div><div className="runtime-actions">{(["TRANSIENT","PERMANENT","NONE"] as const).map(x=><Button key={x} active={failure===x} onClick={()=>{setFailure(x);setAttempt(0)}}>{x}</Button>)}<Button onClick={()=>setAttempt(v=>v+1)}>SEND / RETRY</Button></div><div className="provider-chain"><div><b>SMS CHANNEL</b><span>rendered body hidden</span></div><i>→</i><div><b>TWILIO ADAPTER</b><span>{failure}</span></div><i>→</i><div><b>SNS ADAPTER</b><span>{failure==="TRANSIENT"?"FALLBACK":"NOT USED"}</span></div></div><Feedback ok={result.startsWith("SENT")||result==="DUPLICATE_SUPPRESSED"} title={result}>Retry transient failures only. The notificationId + attempt key prevents duplicate delivery; logs keep metadata, never sensitive bodies.</Feedback></div>}
