"use client";

import { useState } from "react";
import { ArrowRight, Rotate } from "@/components/ui/icons";

const incidents = [
  {name:"Slow payment provider", answer:"trace", logs:"payment.capture.completed · provider=stripe · duration_ms=4810", metrics:"payment_latency p50 82ms · p99 4.9s", trace:[120,260,4810,90,45], note:"The trace localizes the wait to CapturePayment; percentiles reveal that only the tail is slow."},
  {name:"Database error", answer:"logs", logs:"order.persist.failed · error_code=connection_reset · trace_id=abc123", metrics:"checkout_failure_total +1 · db_errors +1", trace:[110,230,640,75,0], note:"The structured failure event gives the actionable cause; metrics show frequency and the trace shows its position."},
  {name:"Invalid inventory response", answer:"logs", logs:"inventory.response.invalid · sku=SKU-7 · missing=reservation_id", metrics:"inventory_contract_failures +1", trace:[95,310,0,0,0], note:"A structured contract-validation event explains what was malformed without dumping private payloads."},
  {name:"Notification timeout", answer:"trace", logs:"notification.send.timeout · channel=email · deadline_ms=2000", metrics:"notification_timeout_total +1", trace:[100,240,720,65,2000], note:"The trace proves checkout completed its critical stages and isolates the slow non-critical notification."},
] as const;
const stages=["Validate","Reserve","Pay","Persist","Notify"];
export function ObservabilityIncidentLab(){const[i,setI]=useState(0);const[view,setView]=useState("metrics");const item=incidents[i];return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> OBSERVABILITY INCIDENT LAB</div><span>CHECKOUT / 3% FAILURE</span></div><div className="incident-controls">{incidents.map((x,n)=><button key={x.name} type="button" aria-pressed={i===n} onClick={()=>{setI(n);setView("metrics")}}>{x.name}</button>)}</div><div className="signal-tabs" role="tablist" aria-label="Telemetry signal">{["logs","metrics","trace"].map(x=><button role="tab" aria-selected={view===x} key={x} onClick={()=>setView(x)}>{x.toUpperCase()}</button>)}</div><div className="incident-signal" role="tabpanel" aria-live="polite">{view==="trace"?<div className="span-timeline">{stages.map((s,n)=><div key={s}><span>{s}</span><i style={{width:`${Math.max(3,item.trace[n]/50)}%`}}/><b>{item.trace[n]}ms</b></div>)}</div>:<code>{item[view as "logs"|"metrics"]}</code>}</div><div className={`lab-feedback ${view===item.answer?"success":"error"}`}><b>{view===item.answer?"FASTEST FIRST SIGNAL":"USEFUL, BUT NOT THE FASTEST START"}</b><p>{item.note}</p></div></div>}

const traceEvents=[
  {service:"Checkout",event:"request.started",trace:"abc123"},{service:"Inventory",event:"reserve.completed",trace:"z9"},{service:"Payment",event:"capture.started",trace:"abc123"},{service:"Notify",event:"email.sent",trace:"k2"},{service:"Inventory",event:"reserve.completed",trace:"abc123"},{service:"Payment",event:"capture.timeout",trace:"abc123"},
];
export function TraceReconstructionLab(){const[filtered,setFiltered]=useState(false);const rows=filtered?traceEvents.filter(x=>x.trace==="abc123"):traceEvents;return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className={filtered?"live-dot":"alert-dot"}/> TRACE RECONSTRUCTION LAB</div><span>{rows.length} EVENTS</span></div><div className="trace-filter"><code>trace_id = abc123</code><button className="lab-button" type="button" aria-pressed={filtered} onClick={()=>setFiltered(!filtered)}>{filtered?<Rotate/>:<ArrowRight/>}{filtered?"SHOW NOISE":"APPLY FILTER"}</button></div><div className="event-table" aria-live="polite">{rows.map((x,n)=><div key={`${x.trace}-${n}`}><span>{x.service}</span><b>{x.event}</b><code>{x.trace}</code></div>)}</div><p className="lab-caption">Correlation reconstructs one request across services. It does not replace careful event names, safe context, metrics, or spans.</p></div>}

const testCases=[
  {name:"₹1000 premium cart",kind:"happy path",covers:"premium discount",useful:true},{name:"₹0 cart",kind:"boundary",covers:"minimum total",useful:true},{name:"₹5000 cart",kind:"boundary",covers:"threshold equality",useful:true},{name:"duplicate coupon",kind:"invalid",covers:"coupon uniqueness",useful:true},{name:"₹1001 premium cart",kind:"duplicate",covers:"same branch as happy path",useful:false},{name:"expired coupon",kind:"time",covers:"expiry with controlled Clock",useful:true},
];
export function TestSuiteDesigner(){const[selected,setSelected]=useState<number[]>([0]);const toggle=(n:number)=>setSelected(s=>s.includes(n)?s.filter(x=>x!==n):[...s,n]);const useful=selected.filter(n=>testCases[n].useful).length;return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className={useful>=5?"live-dot":"alert-dot"}/> TEST SUITE DESIGNER</div><span>{useful}/5 BEHAVIORS</span></div><div className="test-matrix">{testCases.map((x,n)=><button type="button" aria-pressed={selected.includes(n)} onClick={()=>toggle(n)} key={x.name}><span>{x.kind}</span><b>{x.name}</b><small>{x.covers}</small></button>)}</div><div className={`lab-feedback ${useful>=5?"success":"error"}`} aria-live="polite"><b>{useful>=5?"BEHAVIOR + BOUNDARIES COVERED":"A CASE CATEGORY IS STILL MISSING"}</b><p>{selected.includes(4)?"One selected case duplicates an existing branch. Prefer a missing boundary, invalid input, or time condition.":"Select cases that can fail differently—not merely more values on the same path."}</p></div></div>}

const contracts=["put then get returns value","missing key returns empty","delete removes value","overwrite replaces value"] as const;
export function ContractTestLab(){const[impl,setImpl]=useState(0);const implementations=[{name:"MemoryCache",pass:[1,1,1,1]},{name:"RedisCache",pass:[1,1,1,1]},{name:"BrokenFake",pass:[1,1,0,0]}];const item=implementations[impl];return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className={item.pass.every(Boolean)?"live-dot":"alert-dot"}/> CONTRACT TEST LAB</div><span>SHARED SUITE</span></div><div className="contract-selector">{implementations.map((x,n)=><button type="button" aria-pressed={impl===n} onClick={()=>setImpl(n)} key={x.name}>{x.name}</button>)}</div><div className="contract-results" aria-live="polite">{contracts.map((x,n)=><div key={x}><b className={item.pass[n]?"pass":"fail"}>{item.pass[n]?"PASS":"FAIL"}</b><span>{x}</span></div>)}</div><p className="lab-caption">One behavioral suite protects every substitute. A mock can verify a call; only a real or fake implementation can demonstrate these semantics.</p></div>}

const strategySteps=[
  {name:"SEVEN BRANCHES",branches:7,blast:7,count:0,isolation:1,copy:"PricingService owns every algorithm and every reason to change."},
  {name:"IDENTIFY VARIATION",branches:7,blast:6,count:0,isolation:2,copy:"The varying axis is pricing—not ride orchestration."},
  {name:"EXTRACT CONTRACT",branches:1,blast:3,count:1,isolation:5,copy:"PricingStrategy gives the context one stable operation."},
  {name:"IMPLEMENT STRATEGIES",branches:1,blast:2,count:7,isolation:8,copy:"Standard, Surge, Airport, and Corporate algorithms evolve independently."},
  {name:"INJECT + SELECT",branches:0,blast:1,count:7,isolation:10,copy:"Selection moves outside the context; each strategy is isolated in tests."},
] as const;
export function BranchStrategyLab(){const[step,setStep]=useState(0);const x=strategySteps[step];return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className={step===4?"live-dot":"alert-dot"}/> BRANCH-TO-STRATEGY REFACTOR</div><span>{step+1}/5 · {x.name}</span></div><div className="strategy-diagram"><div><b>RidePricingService</b><small>{step<2?"if standard · else premium · else shared · ...":"price(ride, strategy)"}</small></div><i>→</i><div><b>{step<2?"BRANCH HOTSPOT":"PricingStrategy"}</b><small>{step<3?"variation is emerging":"Standard · Surge · Corporate"}</small></div></div><div className="metric-strip">{[["BRANCHES",x.branches],["BLAST RADIUS",x.blast],["STRATEGIES",x.count],["TEST ISOLATION",x.isolation]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className={`lab-feedback ${step===4?"success":"error"}`}><b>{x.name}</b><p>{x.copy}</p></div><button className="lab-button cycle-button" type="button" onClick={()=>setStep((step+1)%5)}>{step===4?<Rotate/>:<ArrowRight/>}{step===4?"RESTORE BRANCHES":"APPLY NEXT STEP"}</button></div>}

const rides=[{type:"STANDARD",strategy:"StandardPricing",price:"₹240"},{type:"SURGE",strategy:"SurgePricing(1.8×)",price:"₹432"},{type:"CORPORATE",strategy:"CorporatePricing",price:"₹180"}] as const;
export function StrategySelectionLab(){const[ride,setRide]=useState(0);const[selection,setSelection]=useState("context");const x=rides[ride];const correct=selection==="registry";return <div className="verification-lab lab-panel"><div className="lab-toolbar"><div><span className={correct?"live-dot":"alert-dot"}/> STRATEGY SELECTION LAB</div><span>IMPLEMENTATION ≠ SELECTION</span></div><div className="strategy-selectors">{rides.map((x,n)=><button type="button" aria-pressed={ride===n} onClick={()=>setRide(n)} key={x.type}>{x.type}</button>)}</div><div className="selection-flow"><span>{x.type}</span><i>→</i><button type="button" aria-pressed={selection==="context"} onClick={()=>setSelection("context")}>branch inside context</button><button type="button" aria-pressed={selection==="registry"} onClick={()=>setSelection("registry")}>registry / configuration</button><i>→</i><b>{x.strategy}</b><strong>{x.price}</strong></div><div className={`lab-feedback ${correct?"success":"error"}`} aria-live="polite"><b>{correct?"SELECTION IS A SEPARATE POLICY":"THE CONTEXT STILL OWNS THE BRANCH"}</b><p>{correct?"Something still chooses the algorithm. Keeping that concern outside pricing prepares us to discuss creation in Chapter 18.":"The algorithms moved, but adding a ride type still edits the context. Move selection to a composition boundary."}</p></div></div>}
