"use client";

import { useState } from "react";

const importSteps=["OPEN","VALIDATE","PARSE","NORMALIZE","PERSIST","REPORT","CLEANUP"] as const;
const invariantSteps=new Set(["OPEN","PERSIST","REPORT","CLEANUP"]);
export function WorkflowTemplateLab(){
  const[shared,setShared]=useState(false);const[format,setFormat]=useState<"CSV"|"JSON"|"XML">("CSV");const[overrides,setOverrides]=useState<string[]>(["PARSE"]);
  const toggle=(step:string)=>setOverrides(x=>x.includes(step)?x.filter(v=>v!==step):[...x,step]);
  return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={shared?"live-dot":"alert-dot"}/> DUPLICATED WORKFLOW → TEMPLATE METHOD</div><button type="button" className="mode-button" aria-pressed={shared} onClick={()=>setShared(!shared)}>{shared?"SHARED SKELETON":"3 WORKFLOW COPIES"}</button></div><div className="workflow-formats">{(["CSV","JSON","XML"] as const).map(x=><button type="button" aria-pressed={format===x} onClick={()=>setFormat(x)} key={x}>{x}</button>)}</div>{shared?<div className="workflow-pipeline" aria-live="polite">{importSteps.map(step=><button type="button" aria-pressed={overrides.includes(step)} className={invariantSteps.has(step)?"fixed":"variable"} onClick={()=>!invariantSteps.has(step)&&toggle(step)} key={step}><small>{invariantSteps.has(step)?"INVARIANT":"HOOK"}</small>{step}{step==="PARSE"&&` ${format}`}</button>)}</div>:<div className="workflow-copies">{(["CSV","JSON","XML"] as const).map(kind=><div key={kind}><b>{kind}Importer</b>{importSteps.slice(0,-1).map(step=><span className={step==="PARSE"?"variable":"duplicate"} key={step}>{step==="PARSE"?`${step} ${kind}`:step}</span>)}</div>)}</div>}<div className="metric-strip">{[["DUPLICATED STEPS",shared?0:15],["VARIANT STEPS",3],["ORCHESTRATION COPIES",shared?1:3],["BASE GUARANTEES",shared?Math.max(0,7-overrides.length):0]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="lab-caption">Toggle the shared skeleton, select a format, then mark variable hooks. Overriding invariant steps would weaken the base algorithm&apos;s guarantees.</p></div>
}

type Handler={name:string;cost:number};const allHandlers:Handler[]=[{name:"Auth",cost:1},{name:"RateLimit",cost:1},{name:"Fraud",cost:5},{name:"Inventory",cost:3},{name:"Approval",cost:4},{name:"Audit",cost:1}];
export function ChainFlowLab(){
  const[chain,setChain]=useState(allHandlers.slice(0,5));const[rejector,setRejector]=useState("Fraud");
  const move=(index:number,delta:number)=>{const next=[...chain],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setChain(next)};
  const toggle=(handler:Handler)=>setChain(x=>x.some(v=>v.name===handler.name)?x.filter(v=>v.name!==handler.name):[...x,handler]);const stop=chain.findIndex(x=>x.name===rejector);const visited=chain.slice(0,stop<0?chain.length:stop+1);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> CHAIN ORDER / REQUEST FLOW</div><span>{chain.length} HANDLERS</span></div><div className="handler-palette">{allHandlers.map(h=><button type="button" aria-pressed={chain.some(x=>x.name===h.name)} onClick={()=>toggle(h)} key={h.name}>{h.name}</button>)}</div><div className="handler-chain" aria-live="polite">{chain.map((handler,index)=><div className={handler.name===rejector?"rejector":""} key={handler.name}><b>{handler.name}</b><small>COST {handler.cost}</small><span><button type="button" aria-label={`Move ${handler.name} earlier`} onClick={()=>move(index,-1)} disabled={index===0}>←</button><button type="button" aria-label={`Move ${handler.name} later`} onClick={()=>move(index,1)} disabled={index===chain.length-1}>→</button><button type="button" aria-pressed={handler.name===rejector} onClick={()=>setRejector(handler.name)}>REJECT</button></span></div>)}</div><div className="metric-strip">{[["HANDLERS VISITED",visited.length],["STOPPED BY",chain.some(x=>x.name===rejector)?rejector:"NONE"],["TOTAL COST",visited.reduce((n,x)=>n+x.cost,0)],["RESULT",stop>=0?"REJECTED":"PASSED"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="lab-caption">Reorder with the arrow buttons, add/remove stages, and choose a rejecting handler. Cheap security checks should usually precede expensive work.</p></div>
}

const dependencies=["Stripe","Postgres","SendGrid","Clock"];
export function DependencyWiringLab(){const[injected,setInjected]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={injected?"live-dot":"alert-dot"}/> DEPENDENCY WIRING</div><button type="button" className="mode-button" aria-pressed={injected} onClick={()=>setInjected(!injected)}>{injected?"INJECT":"SELF-CONSTRUCT"}</button></div><div className={`dependency-wiring ${injected?"injected":""}`}><b>{injected?"main() / composition root":"CheckoutService"}</b><i>{injected?"constructs + supplies":"new inside"}</i><div>{dependencies.map(x=><span key={x}>{x}</span>)}</div>{injected&&<strong>CheckoutService(repo, payment, email, clock)</strong>}</div><div className="metric-strip">{[["VISIBLE DEPENDENCIES",injected?4:0],["ACTUAL DEPENDENCIES",4],["TEST SUBSTITUTION",injected?"EASY":"HARD"],["LIFETIME CONTROL",injected?"HIGH":"LOW"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}

const graphOrder=["Config","Logger","DB Pool","HTTP Client","Repository","Payment Adapter","CheckoutService","Controller"];
export function ContainerGraphLab(){const[count,setCount]=useState(0);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={count===graphOrder.length?"live-dot":"alert-dot"}/> CONTAINER GRAPH / CONSTRUCTION ORDER</div><span>{count}/{graphOrder.length} BUILT</span></div><div className="construction-graph">{graphOrder.map((x,i)=><div className={i<count?"built":"pending"} key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b></div>)}</div><div className="cycle-actions"><button type="button" onClick={()=>setCount(Math.min(graphOrder.length,count+1))} disabled={count===graphOrder.length}>CONSTRUCT NEXT</button><button type="button" onClick={()=>setCount(0)}>RESET</button></div><div className="lab-feedback success" aria-live="polite"><b>{count===graphOrder.length?"OBJECT GRAPH READY":`NEXT: ${graphOrder[count]}`}</b><p>Dependencies must exist before their consumers. Containers automate this topological order; manual DI makes the same order visible in code.</p></div></div>}

type Scope="APPLICATION"|"REQUEST"|"OPERATION";const scopeTargets:Record<string,Scope>={AppLogger:"APPLICATION",DBPool:"APPLICATION",CheckoutService:"APPLICATION",RequestContext:"REQUEST",CurrentUser:"REQUEST",Transaction:"OPERATION"};
export function ScopeMismatchLab(){const[assignments,setAssignments]=useState<Record<string,Scope>>({AppLogger:"APPLICATION",DBPool:"REQUEST",CheckoutService:"APPLICATION",RequestContext:"APPLICATION",Transaction:"REQUEST",CurrentUser:"REQUEST"});const[focus,setFocus]=useState("RequestContext");const correct=Object.entries(scopeTargets).filter(([k,v])=>assignments[k]===v).length;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={correct===6?"live-dot":"alert-dot"}/> LIFETIME / SCOPE MISMATCH</div><span>{correct}/6 CORRECT</span></div><div className="scope-assignment">{Object.keys(scopeTargets).map(name=><div key={name}><button type="button" className={focus===name?"selected":""} onClick={()=>setFocus(name)}>{name}</button><span>{assignments[name]}</span></div>)}</div><div className="scope-controls">{(["APPLICATION","REQUEST","OPERATION"] as Scope[]).map(scope=><button type="button" aria-pressed={assignments[focus]===scope} onClick={()=>setAssignments({...assignments,[focus]:scope})} key={scope}>{scope}</button>)}</div><div className={`lab-feedback ${assignments.RequestContext==="APPLICATION"?"error":"success"}`} aria-live="polite"><b>{assignments.RequestContext==="APPLICATION"?"CAPTIVE DEPENDENCY":"LIFETIMES ALIGN"}</b><p>An application-scoped CheckoutService must not retain a request-scoped RequestContext. Pass request data to the operation or align scopes.</p></div></div>}

const cycleNodes=["OrderService","PaymentService","OrderRepository","PaymentGateway"];
export function CircularDependencyLab(){const[edges,setEdges]=useState<[string,string][]>([["OrderService","PaymentService"],["PaymentService","OrderService"]]);const[refactor,setRefactor]=useState("NONE");const cycle=edges.some(([a,b])=>edges.some(([x,y])=>x===b&&y===a));const add=()=>{const candidates:[[string,string],[string,string]]=[["OrderService","OrderRepository"],["PaymentService","PaymentGateway"]];const found=candidates.find(([a,b])=>!edges.some(([x,y])=>x===a&&y===b));if(found)setEdges([...edges,found])};return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={cycle&&refactor==="NONE"?"alert-dot":"live-dot"}/> CIRCULAR DEPENDENCY</div><span>{edges.length} EDGES</span></div><div className="cycle-graph">{cycleNodes.map(x=><b key={x}>{x}</b>)}<div>{edges.map(([a,b])=><span key={`${a}-${b}`}>{a} → {b}</span>)}</div></div><div className="cycle-actions"><button type="button" onClick={add}>ADD VALID EDGE</button>{["EVENT","ORCHESTRATOR","SMALLER PORT"].map(x=><button type="button" aria-pressed={refactor===x} onClick={()=>setRefactor(x)} key={x}>{x}</button>)}</div><div className={`lab-feedback ${cycle&&refactor==="NONE"?"error":"success"}`}><b>{cycle&&refactor==="NONE"?"CONSTRUCTION IMPOSSIBLE / DESIGN SMELL":`${refactor} BREAKS THE RESPONSIBILITY CYCLE`}</b><p>Setter injection can hide the cycle but does not repair ownership. Move orchestration, publish a fact, or extract the smaller dependency.</p></div></div>}

type Classification="ENTITY"|"VALUE"|"DEPENDS";const candidates:Record<string,Classification>={User:"ENTITY",Money:"VALUE",Address:"DEPENDS",Seat:"DEPENDS",Booking:"ENTITY",Coordinates:"VALUE",Product:"DEPENDS",PhoneNumber:"VALUE",Show:"ENTITY"};
export function EntityValueLab(){const[answers,setAnswers]=useState<Record<string,Classification>>({});const[focus,setFocus]=useState("Seat");const score=Object.entries(candidates).filter(([k,v])=>answers[k]===v).length;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={score===9?"live-dot":"alert-dot"}/> ENTITY VS VALUE</div><span>{score}/9 REASONED</span></div><div className="concept-cards">{Object.keys(candidates).map(x=><button type="button" aria-pressed={focus===x} onClick={()=>setFocus(x)} key={x}><b>{x}</b><small>{answers[x]??"UNCLASSIFIED"}</small></button>)}</div><div className="classification-actions">{(["ENTITY","VALUE","DEPENDS"] as Classification[]).map(x=><button type="button" aria-pressed={answers[focus]===x} onClick={()=>setAnswers({...answers,[focus]:x})} key={x}>{x}</button>)}</div><div className="lab-feedback success" aria-live="polite"><b>{focus}: {answers[focus]??"ASK THE IDENTITY TEST"}</b><p>{candidates[focus]==="DEPENDS"?"Context changes the answer. Ask whether identity and history matter in this model.":candidates[focus]==="ENTITY"?"Identity persists even when attributes change.":"Equivalent values are interchangeable; validate them at construction."}</p></div></div>}

const rules=["No double-booked seat","At least one seat","Total is non-negative","Confirmation needs payment","Expired hold cannot confirm"] as const;const owners=["Booking","Show","SeatReservation","Payment","BookingService","Database"];
export function InvariantOwnershipLab(){const[assignments,setAssignments]=useState<Record<string,string>>({});const[focus,setFocus]=useState<(typeof rules)[number]>(rules[0]);const recommended:Record<string,string>={"No double-booked seat":"Show","At least one seat":"Booking","Total is non-negative":"Booking","Confirmation needs payment":"Booking","Expired hold cannot confirm":"SeatReservation"};const score=rules.filter(x=>assignments[x]===recommended[x]).length;return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={score===5?"live-dot":"alert-dot"}/> INVARIANT OWNERSHIP</div><span>{score}/5 DEFENSIBLE</span></div><div className="invariant-rules">{rules.map(x=><button type="button" aria-pressed={focus===x} onClick={()=>setFocus(x)} key={x}><b>{x}</b><small>{assignments[x]??"NO OWNER"}</small></button>)}</div><div className="owner-actions">{owners.map(x=><button type="button" aria-pressed={assignments[focus]===x} onClick={()=>setAssignments({...assignments,[focus]:x})} key={x}>{x}</button>)}</div><div className={`lab-feedback ${assignments[focus]===recommended[focus]?"success":"error"}`}><b>{assignments[focus]===recommended[focus]?"STATE + RESPONSIBILITY MEET HERE":"RECONSIDER THE OWNER"}</b><p>Recommended: {recommended[focus]}. Database constraints can reinforce invariants, but the model should still express the rule and its domain meaning.</p></div></div>}

type DomainKind="ENTITY"|"VALUE"|"SERVICE"|"EXTERNAL";const workbenchItems=["User","Movie","Theater","Screen","Seat","Show","SeatReservation","Booking","Payment","Money","TimeRange"];
export function DomainWorkbench(){const[kinds,setKinds]=useState<Record<string,DomainKind>>({});const[focus,setFocus]=useState("Booking");const[relations,setRelations]=useState<string[]>([]);const addRelation=()=>{const options=["Show owns seat availability","Booking contains seat references","Booking uses Money","Payment confirms Booking"];const next=options.find(x=>!relations.includes(x));if(next)setRelations([...relations,next])};return <div className="learning-lab lab-panel domain-workbench"><div className="lab-toolbar"><div><span className="live-dot"/> MOVIE BOOKING MODELING WORKBENCH</div><span>{Object.keys(kinds).length}/11 CLASSIFIED</span></div><div className="workbench-layout"><div className="workbench-concepts">{workbenchItems.map(x=><button type="button" aria-pressed={focus===x} onClick={()=>setFocus(x)} key={x}><b>{x}</b><small>{kinds[x]??"CANDIDATE"}</small></button>)}</div><div className="workbench-inspector"><span>SELECTED CONCEPT</span><h3>{focus}</h3>{(["ENTITY","VALUE","SERVICE","EXTERNAL"] as DomainKind[]).map(x=><button type="button" aria-pressed={kinds[focus]===x} onClick={()=>setKinds({...kinds,[focus]:x})} key={x}>{x}</button>)}<button type="button" onClick={addRelation}>CONNECT NEXT RELATIONSHIP</button></div><div className="workbench-model"><b>MODEL RELATIONSHIPS</b>{relations.map(x=><span key={x}>{x}</span>)}{!relations.length&&<p>Classify concepts, then add semantic relationships—not database foreign keys.</p>}</div></div><div className="lab-feedback success"><b>MULTIPLE MODELS CAN BE VALID</b><p>Defend each choice using identity, value equality, responsibility, invariants, ownership, and the current use cases.</p></div></div>}

const giantConcepts=["Movie","Theater","Screens","Shows","Seats","Bookings","Payments","Users"];
export function AggregateBoundaryLab(){const[refined,setRefined]=useState(false);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className={refined?"live-dot":"alert-dot"}/> AGGREGATE BOUNDARY LAB</div><button type="button" className="mode-button" aria-pressed={refined} onClick={()=>setRefined(!refined)}>{refined?"CONSISTENCY BOUNDARIES":"GIANT AGGREGATE"}</button></div>{refined?<div className="aggregate-groups"><div><b>SHOW AVAILABILITY</b><span>Show · Seats · Holds</span></div><div><b>BOOKING</b><span>Items · Money · Status</span></div><div><b>PAYMENT</b><span>Attempt · Receipt</span></div><div><b>USER</b><span>Identity · Profile</span></div></div>:<div className="giant-aggregate"><b>Movie aggregate root?</b>{giantConcepts.map(x=><span key={x}>{x}</span>)}</div>}<div className="metric-strip">{[["ROOTS",refined?4:1],["CONSISTENCY SCOPE",refined?"FOCUSED":"GLOBAL"],["LOAD / LOCK COST",refined?"LOWER":"EXTREME"],["CROSS-BOUNDARY",refined?"ID + EVENT":"DIRECT MUTATION"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div><p className="lab-caption">Group only concepts whose invariants must change consistently. Exact boundaries remain context-dependent.</p></div>}

const pressures=["TEMPORARY HOLD","5-MINUTE EXPIRY","GROUP BOOKING","COUPON","PARTIAL CANCELLATION","MULTIPLE PAYMENT PROVIDERS","VIP SEATS"];
export function ModelEvolutionLab(){const[enabled,setEnabled]=useState<string[]>([]);const toggle=(x:string)=>setEnabled(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);const additions=[enabled.some(x=>x.includes("HOLD")||x.includes("EXPIRY"))&&"SeatReservation + ExpiryPolicy",enabled.includes("COUPON")&&"DiscountPolicy",enabled.includes("PARTIAL CANCELLATION")&&"BookingItem cancellation state",enabled.includes("MULTIPLE PAYMENT PROVIDERS")&&"PaymentProcessor port + Adapter/Strategy",enabled.includes("VIP SEATS")&&"SeatCategory / PricingPolicy"].filter(Boolean);return <div className="learning-lab lab-panel"><div className="lab-toolbar"><div><span className="live-dot"/> REQUIREMENT PRESSURE / MODEL EVOLUTION</div><span>{enabled.length} PRESSURES</span></div><div className="pressure-toggles">{pressures.map(x=><button type="button" aria-pressed={enabled.includes(x)} onClick={()=>toggle(x)} key={x}>{x}</button>)}</div><div className="model-evolution"><div><small>STEP ZERO</small><b>Booking</b><code>seatIds[] · amount · status</code></div><i>requirements reveal rules →</i><div><small>JUSTIFIED MODEL</small>{additions.length?additions.map(x=><b key={String(x)}>{x}</b>):<p>Keep the model simple until pressure arrives.</p>}</div></div><div className="metric-strip">{[["REQUIREMENTS",enabled.length+1],["MODEL CONCEPTS",1+additions.length],["HYPOTHETICAL TYPES",0],["REFINEMENT","INCREMENTAL"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</div></div>}
