import type { Metadata } from "next";
import { MultiLanguageCode } from "@/components/code/multi-language-code";
import { ClassificationChallenge } from "@/components/labs/design-labs";
import { BehaviorContractVisual, CapabilityLab, ContractTestLab, PreconditionsLab } from "@/components/labs/lsp-labs";
import { ChapterNav, CommonMistakes, ConceptPressure, InterviewCheckpoint, LanguageReality, LessonHero, LessonPager, RapidRevision, TradeoffPanel } from "@/components/lesson/primitives";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { lspExamples } from "@/content/code-examples";
export const metadata:Metadata={title:"Liskov Substitution Principle",description:"Learn behavioral substitutability through storage contracts, shared contract tests, and capability-based redesign."};
const toc=[["01","The lie","#start"],["02","Contracts","#contract"],["03","Contract test","#testing"],["04","Violation signals","#signals"],["05","Capabilities","#capabilities"],["06","Languages","#implementation"],["07","Connections","#connections"],["08","Challenge","#challenge"],["09","Interview","#interview"]] as const;
const questions=[
 {q:"What does LSP actually mean?",a:"Every implementation used through an abstraction must preserve the behavioral expectations its callers were promised—not merely match method signatures."},
 {q:"Is matching the interface signature enough?",a:"No. Shape is type compatibility. Valid inputs, outputs, errors, side effects, invariants, and state history determine behavioral compatibility."},
 {q:"What is behavioral substitutability?",a:"A caller written to the abstraction continues to work correctly, without implementation-specific checks, when any conforming implementation is supplied."},
 {q:"Can Go violate LSP without inheritance?",a:"Yes. A type can implicitly satisfy an interface yet ignore Save, mutate unrelated state, or change error semantics. LSP applies wherever callers trust a shared contract."},
 {q:"What are stronger preconditions?",a:"Extra input or setup requirements imposed only by a subtype, such as accepting withdrawals only above 1000 when the base promises every positive amount."},
 {q:"What are weaker postconditions?",a:"Returning less than the abstraction guarantees—for example acknowledging save before durable persistence without exposing that semantic difference."},
 {q:"Why can UnsupportedOperationException be a smell?",a:"It often means the implementation cannot provide a capability the broad interface claims every substitute has. Legacy APIs may still use it, so treat it as a diagnostic signal."},
 {q:"How are error semantics part of a contract?",a:"Callers choose control flow based on whether normal failure returns a result, throws, retries, or is idempotent. Changing that observable behavior can break them."},
 {q:"What is a contract test?",a:"One reusable suite expressing abstraction-level behavior and run unchanged against every production implementation, fake, and adapter."},
 {q:"Why is instanceof often suspicious?",a:"It reveals that a caller cannot trust the abstraction uniformly. The interface may be lying or too broad, though boundary adapters can sometimes justify a type check."},
 {q:"How does LSP support OCP?",a:"OCP lets us add implementations; LSP ensures those additions are safe for existing callers. OCP without LSP is fragile extensibility."},
 {q:"Polymorphism versus substitutability?",a:"Polymorphism gives the same call shape. LSP requires the same trustworthy behavioral meaning."},
 {q:"Can a subtype add functionality?",a:"Yes, as long as base callers retain every promised behavior. Extra capability should not alter the base contract unexpectedly."},
 {q:"When is the base abstraction the problem?",a:"When some legitimate implementations cannot honestly support its methods or guarantees. Split it into capabilities or model distinct concepts."},
] as const;
const challenge=[
 {label:"S3Storage",answer:"Readable + Writable + Deletable",hint:"It can honestly promise all three operations when errors are explicit."},
 {label:"LocalStorage",answer:"Readable + Writable + Deletable",hint:"A local adapter can satisfy the same capabilities with the same observable semantics."},
 {label:"ReadOnlyArchiveStorage",answer:"Readable only",hint:"Do not invent save/delete no-ops to satisfy a broad shape."},
 {label:"TemporaryMemoryStorage",answer:"Depends on contract",hint:"It may be an honest substitute only if durability is not promised; otherwise name the weaker semantics."},
] ;
const signals=[["UNSUPPORTED METHOD","The implementation advertises a capability it cannot perform."],["SILENT NO-OP","The call appears successful but the promised effect never occurs."],["CALLER TYPE CHECK","The caller branches around implementation-specific behavior."],["STRONGER PRECONDITION","A valid base input is rejected by one substitute."],["WEAKER GUARANTEE","The result provides less than the abstraction promises."],["SURPRISING SIDE EFFECT","A read unexpectedly deletes or mutates unrelated state."],["DIFFERENT ERRORS","Normal failure throws where callers expect a result."],["BROKEN INVARIANT","The subtype permits a state callers believe impossible."],["NONSENSICAL METHOD","The capability does not belong to this implementation."]] as const;
export default function LspPage(){return <article className="lesson-page"><div className="page-shell"><LessonHero chapter="07" group="SOLID & Maintainability" title="Same interface." accent="Same trustworthy behavior." time="44 min lab" deck="A compiler can prove that methods exist. It cannot prove that an implementation accepts the same valid inputs, keeps the same promises, fails the same way, or avoids surprising callers." question="Can every caller use this implementation without knowing which one it received?"/></div><ChapterNav chapter="07" items={toc}/>
<section className="lesson-section page-shell" id="start"><Reveal><SectionHeading eyebrow="01 · COLD OPEN" title="What should Penguin.fly() do?" copy="Throw? Do nothing? Return false? If every Bird promises flight, Penguin is not a broken bird—it is evidence that the abstraction is lying."/></Reveal><div className="bird-intro"><div><small>BASE CONTRACT</small><b>Bird.fly()</b></div><span>→</span><div><b>Sparrow</b><code>flies</code></div><div className="broken"><b>Penguin</b><code>throw · no-op · false?</code></div></div><ConceptPressure><p>Useful intuition, but production contracts are subtler. Move to <b>Storage.save / load / delete</b>: what should ReadOnlyArchiveStorage.save() do?</p></ConceptPressure><div className="storage-lie"><div><span>Storage</span><code>save(key, data)<br/>load(key)<br/>delete(key)</code></div>{["LocalStorage","S3Storage","ReadOnlyArchiveStorage"].map((x,i)=><div className={i===2?"broken":""} key={x}><span>{x}</span><code>{i===2?"save() → UnsupportedOperationException":"all operations honored"}</code></div>)}</div><blockquote className="principle-quote">Type compatibility ≠ behavioral compatibility.<small>The assignment compiles. The design can still break every caller expectation.</small></blockquote></section>
<section className="lesson-section lesson-section--wide" id="contract"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · BEHAVIORAL CONTRACT" title="The promise lives beyond the signature." copy="A subtype must not demand more, guarantee less, break invariants, change ordinary failure semantics, or add surprising effects."/></Reveal><BehaviorContractVisual/><PreconditionsLab/><div className="contract-examples">{[["POSTCONDITION","save(order) promises persistence or explicit failure; an in-memory queue silently loses acknowledged data."],["INVARIANT","Account promises balance ≥ 0; a subtype hides negative balances."],["ERROR SEMANTICS","PaymentProcessor promises PaymentResult; one implementation throws for a normal decline."],["SIDE EFFECT","Repository.findUser() reads; one implementation also deletes expired users."],["STATE HISTORY","Order promises CONFIRMED → SHIPPED → DELIVERED; a subtype permits DELIVERED → PENDING."]].map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div></div></section>
<section className="lesson-section page-shell" id="testing"><Reveal><SectionHeading eyebrow="03 · INTERACTIVE CONTRACT TEST" title="Run the same expectations against every implementation." copy="CheckoutService should not know whether it received CardProcessor, UPIProcessor, or a test fake. The shared suite makes the behavioral promise executable."/></Reveal><ContractTestLab/><div className="contract-suite"><span>CACHE CONTRACT SUITE</span>{["set/get consistency","missing-key semantics","delete behavior","TTL expectations","error behavior"].map(x=><p key={x}><b>✓</b>{x}</p>)}<small>Run unchanged against MemoryCache · RedisCache · FakeCache</small></div><ConceptPressure label="CHAPTER 06 → 07"><p>OCP gave us extension points. Contract tests ask whether every extension can honor them. <b>OCP without LSP = fragile extensibility.</b></p></ConceptPressure></section>
<section className="lesson-section lesson-section--tint" id="signals"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · VIOLATION SIGNALS" title="Watch for callers compensating for dishonest implementations." copy="These are diagnostic clues, not mathematical proofs. Context and the written behavioral contract decide."/></Reveal><div className="signal-grid">{signals.map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div><div className="bad-fixes"><span>BAD FIXES</span>{["return null","do nothing","throw unsupported","supportsFeature()","instanceof everywhere"].map(x=><code key={x}>{x}</code>)}<p>These often hide an abstraction problem instead of fixing the contract.</p></div><pre className="naive-code"><code>{`if (storage.type === READ_ONLY) {\n  // caller must remember not to call save()\n}\nif (processor instanceof LegacyProcessor) {\n  // caller invents special failure behavior\n}`}</code></pre><ConceptPressure><p>Why does the caller know implementation-specific behavior? Often <b>the abstraction is lying or the interface is too broad.</b></p></ConceptPressure></div></section>
<section className="lesson-section page-shell" id="capabilities"><Reveal><SectionHeading eyebrow="05 · CAPABILITY-BASED REDESIGN" title="Sometimes the subtype is honest and the interface is wrong." copy="Read-only archives are useful. They simply should not claim write and delete capabilities. Split the contract so callers request only what they need."/></Reveal><CapabilityLab/><div className="rectangle-note"><span>SECONDARY EXERCISE · RECTANGLE / SQUARE</span><p>A mutable Rectangle promises independently settable width and height. Square must couple them, so setWidth(5); setHeight(10) cannot preserve the expected area of 50. The issue is not geometry—it is the mutable contract. Prefer Shape.area() or separate immutable value types.</p></div><ConceptPressure label="CHAPTER 08 TEASER"><p>ReadableStorage, WritableStorage, and DeletableStorage hint at Interface Segregation. Ask: <b>is the subtype broken, or is the interface too broad?</b></p></ConceptPressure></section>
<section className="lesson-section lesson-section--wide" id="implementation"><div className="page-shell"><Reveal><SectionHeading eyebrow="06 · MULTI-LANGUAGE IMPLEMENTATION" title="Every language can express a truthful shape—and still lie about behavior." copy="The redesign exposes capabilities honestly. Shared contract tests remain necessary because compilers cannot prove the semantic promise."/></Reveal><MultiLanguageCode examples={lspExamples}/><div className="language-grid"><LanguageReality language="C++">Virtual dispatch, override, and const correctness protect parts of the shape. They cannot guarantee input ranges, durability, error guarantees, side effects, or state history.</LanguageReality><LanguageReality language="Go">Go has no class inheritance, yet LSP still applies. Implicit interface satisfaction proves method shape, not whether Save silently ignores data or Load mutates state.</LanguageReality><LanguageReality language="Java">UnsupportedOperationException is often a sign that an interface advertises too much. Capability interfaces and shared contract tests make supported behavior explicit.</LanguageReality><LanguageReality language="TypeScript">Structural typing accepts any compatible object shape. It cannot verify that save persists, that failures reject consistently, or that a fake matches production semantics.</LanguageReality></div><TradeoffPanel good={["Multiple implementations serve one caller","A plugin boundary must remain trustworthy","Fakes and adapters should match production semantics"]} cost={["Behavioral contracts need documentation","Shared suites require maintenance","Capability splits add names and composition"]} avoid={["Types represent genuinely different concepts","The base promise is vague or unknowable","A fake deliberately models a different contract"]}/></div></section>
<section className="lesson-section page-shell" id="connections"><Reveal><SectionHeading eyebrow="07 · CONNECT THE PRINCIPLES" title="Same call shape is not the same meaning." copy="Chapter 03, Chapter 06, and LSP answer three different questions about one abstraction."/></Reveal><div className="principle-links"><div><span>POLYMORPHISM · 03</span><b>Can different implementations receive the same call?</b><p>same call shape</p></div><div><span>OCP · 06</span><b>Can we add an implementation without rewriting the core?</b><p>safe extension mechanism</p></div><div><span>LSP · 07</span><b>Can the caller trust every implementation?</b><p>same behavioral meaning</p></div></div><div className="fragile-formula"><span>OCP</span><b>without</b><span>LSP</span><strong>= FRAGILE EXTENSIBILITY</strong></div><ConceptPressure label="LSP WITHOUT INHERITANCE"><p>The same reasoning applies to interfaces, protocols, plugins, callbacks, services, repositories, mocks, fakes, and adapters—anywhere a caller relies on shared behavior.</p></ConceptPressure></section>
<section className="lesson-section lesson-section--tint" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="08 · CLOUD STORAGE CHALLENGE" title="Choose honest capabilities—and question durability." copy="Multiple answers can be reasonable if their contracts are explicit. Temporary memory is writable, but is it a substitute when CloudStorage promises durable upload?"/></Reveal><ClassificationChallenge title="ASSIGN THE HONEST CONTRACT" items={challenge} categories={["Readable only","Readable + Writable","Readable + Writable + Deletable","Depends on contract"]}/><div className="challenge-pressure"><span>INTERFACE DESIGN TEASER</span><p>Bird with fly() and swim() repeats the same problem. Flyer and Swimmer let Sparrow, Penguin, and Duck advertise only real capabilities without fake methods.</p></div></div></section>
<section className="lesson-section page-shell" id="interview"><Reveal><SectionHeading eyebrow="09 · INTERVIEW CHECKPOINT" title="Describe what the caller can safely assume." copy="A strong answer covers inputs, guarantees, invariants, errors, effects, and state—not only parent and child classes."/></Reveal><InterviewCheckpoint questions={questions}/><h2 className="subsection-title">Common misconceptions</h2><CommonMistakes items={["LSP only applies to inheritance.","Compiler acceptance proves LSP.","Every subclass is automatically substitutable.","Same return type means same behavior.","Rectangle/Square is the entire principle.","Subtypes cannot add behavior.","Throwing unsupported always solves incompatibility.","Interfaces guarantee behavioral correctness."]}/><div className="answer-card"><span>60-SECOND INTERVIEW ANSWER</span><blockquote>The Liskov Substitution Principle says every implementation used through an abstraction must preserve the behavioral contract its callers were promised. That means it should accept the valid inputs of the abstraction, keep its output guarantees and invariants, preserve expected error semantics and side effects, and remain safe across state transitions. Matching a signature is not enough—even in Go or TypeScript without class inheritance. I use shared contract tests and split overly broad interfaces into honest capabilities.</blockquote></div><RapidRevision items={[["Same caller?","every implementation should work without special cases"],["Stricter inputs?","do not reject a valid base request"],["Weaker outputs?","preserve promised guarantees"],["Different errors?","failure form is observable behavior"],["Surprising effects?","protect unrelated state"],["Broken invariants?","preserve truths and legal history"],["Type checks?","caller compensation signals a lie"],["Interface too broad?","split capabilities when methods do not belong"]]}/><LessonPager previous={{number:"06",title:"Open/Closed Principle",href:"/learn/open-closed-principle"}} next={{number:"08",title:"Interface Segregation + Dependency Inversion",href:"/learn/interface-segregation-dependency-inversion",copy:"Design focused interfaces and point dependencies toward stable policy."}}/></section></article>}
