import type { Metadata } from "next";
import { MultiLanguageCode } from "@/components/code/multi-language-code";
import { ClassificationChallenge } from "@/components/labs/design-labs";
import { BranchGrowthLab, ExtensionChangeLab, PrematureAbstractionLab, RegistryLab } from "@/components/labs/ocp-labs";
import { ChapterNav, CommonMistakes, ConceptPressure, InterviewCheckpoint, LanguageReality, LessonHero, LessonPager, RapidRevision, TradeoffPanel } from "@/components/lesson/primitives";
import { Reveal } from "@/components/ui/reveal";
import { SectionHeading } from "@/components/ui/section-heading";
import { ocpExamples } from "@/content/code-examples";
export const metadata:Metadata={title:"Open/Closed Principle",description:"Derive OCP from change pressure with an interactive pricing engine, extension registry, and blast-radius simulator."};
const toc=[["01","Branch growth","#start"],["02","Axis of change","#axis"],["03","Refactor","#refactor"],["04","Mechanisms","#mechanisms"],["05","Change test","#change"],["06","Languages","#implementation"],["07","Wrong OCP","#wrong"],["08","Challenge","#challenge"],["09","Interview","#interview"]] as const;
const questions=[
 {q:"What does OCP really mean?",a:"Find an observed axis of variation and place a stable boundary around it so routine new variants enter through an extension point instead of repeatedly rewriting core behavior."},
 {q:"Does closed for modification mean never changing old code?",a:"No. Bugs, new invariants, and a better model still change core code. Closed means a normal new variant should use the intended extension mechanism."},
 {q:"What is an axis of change?",a:"One dimension along which requirements vary independently, such as discount policy, notification channel, storage backend, or export format."},
 {q:"Does OCP require inheritance?",a:"No. Interfaces, composition, functions, callbacks, registries, configuration, plugins, dependency injection, and data-driven rules can all create extension boundaries."},
 {q:"Can if/else still be correct?",a:"Yes. A small stable enum, parser, state decoder, or tiny command router may be clearer than polymorphism. Repeated volatile edits are the pressure—not the syntax itself."},
 {q:"How do you identify a useful extension point?",a:"Observe recurring variants, ask what changes and what stays stable, then design the smallest contract that lets the stable part delegate the volatile decision."},
 {q:"How can configuration satisfy OCP?",a:"A stable engine can interpret validated data or register named implementations, allowing new combinations without changing its algorithm. Configuration still needs a controlled schema and validation."},
 {q:"How is OCP related to polymorphism?",a:"Polymorphism is one mechanism for dispatching varying behavior behind one call shape. OCP is the broader change-boundary goal."},
 {q:"How is OCP related to SRP?",a:"SRP identifies coherent reasons to change; OCP can place extension points around the volatile responsibility while keeping stable orchestration untouched."},
 {q:"What if we predict the wrong future change?",a:"The abstraction becomes friction. Refactor it when evidence changes; abstractions are hypotheses, not permanent architecture."},
 {q:"When is OCP overengineering?",a:"When variation is hypothetical, the change is cheaper than the abstraction, or indirection makes a small stable decision harder to understand."},
 {q:"Can a stable switch be better than polymorphism?",a:"Yes. For a closed, finite, centrally owned mapping, a switch may make exhaustiveness and control flow clearer."},
] as const;
const challenge=[
 {label:"Email delivery",answer:"NotificationChannel",hint:"Delivery protocol varies independently from retries."},
 {label:"SMS delivery",answer:"NotificationChannel",hint:"Add another channel implementation behind the same send contract."},
 {label:"Exponential backoff",answer:"RetryPolicy",hint:"Retry timing is a separate variation dimension."},
 {label:"No retry",answer:"RetryPolicy",hint:"A no-retry policy is still an explicit operational choice."},
 {label:"Message template",answer:"MessageContent",hint:"Content rendering should not be forced into channel or retry behavior."},
] ;
export default function OcpPage(){return <article className="lesson-page"><div className="page-shell"><LessonHero chapter="06" group="SOLID & Maintainability" title="Extend behavior." accent="Keep the core stable." time="42 min lab" deck="OCP is not a slogan about never editing files. It is a way to find real variation, protect stable decisions, and add the next case through an intentional boundary." question="Why does every new variant force us to reopen the same code?"/></div><ChapterNav chapter="06" items={toc}/>
<section className="lesson-section page-shell" id="start"><Reveal><SectionHeading eyebrow="01 · COLD OPEN" title="Three discount branches were fine. Then the roadmap arrived." copy="Regular, premium, and employee pricing fit in one readable function. Festival, coupon, loyalty, corporate, partner, flash-sale, and regional rules turn that function into a collision point."/></Reveal><pre className="naive-code"><code>{`if (customerType === "regular") applyRegular();\nelse if (customerType === "premium") applyPremium();\nelse if (customerType === "employee") applyEmployee();`}</code></pre><ConceptPressure><p>The first conditional was not a mistake. The signal appears when <b>every new pricing rule reopens the same central decision, expands its combinations, and reruns unrelated regression tests.</b></p></ConceptPressure><BranchGrowthLab/></section>
<section className="lesson-section lesson-section--wide" id="axis"><div className="page-shell"><Reveal><SectionHeading eyebrow="02 · DERIVE THE IDEA" title="What varies? What stays stable?" copy="OCP begins by separating one volatile dimension from the behavior that can remain unchanged. The extension point belongs on the observed seam."/></Reveal><div className="axis-model"><div><span>STABLE CORE</span><h3>PricingService</h3><p>Accept a total, select or receive a policy, apply it, and return Money.</p></div><b>+</b><div><span>EXTENSION POINT</span><h3>DiscountPolicy</h3><p>One honest contract for the independently changing pricing calculation.</p></div></div><blockquote className="principle-quote">Open for extension. Closed for routine modification.<small>“Closed” means the normal next variant should use the boundary—not that this file can never change.</small></blockquote><div className="axis-grid">{["payment method","discount policy","shipping method","notification channel","serialization format","authentication provider","tax policy","export format"].map(x=><span key={x}>{x}</span>)}</div><ConceptPressure label="MENTAL MODEL"><p>Chapter 03 showed how different objects answer the same call. Chapter 05 found coherent responsibility boundaries. Now ask whether one of those contracts is a <b>safe, evidence-based extension point.</b></p></ConceptPressure></div></section>
<section className="lesson-section page-shell" id="refactor"><Reveal><SectionHeading eyebrow="03 · REFACTOR THE PRICING ENGINE" title="Move variation behind a small contract." copy="PricingService keeps orchestration. RegularDiscount, PremiumDiscount, FestivalDiscount, CouponDiscount, and CorporateDiscount own their rules. PartnerDiscount becomes one addition."/></Reveal><div className="plugin-visual"><div><small>STABLE CORE</small><b>PricingService</b></div><span>↓</span><div><small>EXTENSION CONTRACT</small><b>DiscountPolicy</b></div><span>↓</span><div className="plugin-nodes">{["Regular","Premium","Festival","Coupon","Corporate"].map(x=><i key={x}>{x}</i>)}</div></div><RegistryLab/><ConceptPressure label="NOT STRATEGY—YET"><p>Polymorphic, strategy-like behavior is one mechanism that helps satisfy OCP. Chapter 17 will teach Strategy as a pattern. <b>OCP is the change goal; Strategy is not its definition.</b></p></ConceptPressure></section>
<section className="lesson-section lesson-section--tint" id="mechanisms"><div className="page-shell"><Reveal><SectionHeading eyebrow="04 · OCP WITHOUT INHERITANCE" title="Extension is a boundary, not a subclass ritual." copy="Pick the mechanism that matches runtime needs, ownership, deployment, and the cost of indirection."/></Reveal><div className="mechanism-grid">{[["INTERFACE","Runtime implementations with a meaningful shared contract."],["COMPOSITION","Assemble independent policies without an is-a claim."],["FUNCTION / CALLBACK","A small behavior needs no object identity."],["REGISTRY","Resolve named handlers, serializers, commands, or drivers."],["CONFIGURATION","Data varies while the interpreter remains stable."],["PLUGIN","Deploy extensions separately behind a versioned contract."],["DEPENDENCY INJECTION","Supply policy from the composition boundary."],["DATA-DRIVEN RULES","Business combinations are validated data, not code branches."]].map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div><div className="real-plugin-row">{["database drivers","payment gateways","middleware","logging sinks","serializers","storage backends"].map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="lesson-section page-shell" id="change"><Reveal><SectionHeading eyebrow="05 · CHANGE + TESTABILITY" title="Compare the same requirement in two designs." copy="An extension-oriented model limits existing logic edits and lets each policy prove itself independently. It does not magically guarantee a correct contract or good tests."/></Reveal><ExtensionChangeLab/><div className="testing-compare"><div><span>POLICY TEST</span><code>{`expect(new FestivalDiscount().apply(money(100)))\n  .toEqual(money(85));`}</code><b>One variant, no service fixture</b></div><div><span>CORE TEST</span><code>{`const fake = total => money(42);\nexpect(new PricingService().price(total, fake))\n  .toEqual(money(42));`}</code><b>Fake proves delegation</b></div><div><span>CONTRACT TEST</span><code>{`for (const policy of policies) {\n  expect(policy.apply(total)).toBeMoney();\n}`}</code><b>Shared expectations still matter</b></div></div></section>
<section className="lesson-section lesson-section--wide" id="implementation"><div className="page-shell"><Reveal><SectionHeading eyebrow="06 · MULTI-LANGUAGE IMPLEMENTATION" title="Let the language choose the lightest honest extension." copy="All four versions isolate discount variation, but they do not mimic Java line by line."/></Reveal><MultiLanguageCode examples={ocpExamples}/><div className="language-grid"><LanguageReality language="C++">Virtual dispatch is useful for runtime plugins, but templates, std::variant, function objects, or std::function can keep value semantics and avoid a hierarchy.</LanguageReality><LanguageReality language="Go">Small consumer-owned interfaces and first-class functions are natural extension points. Composition usually communicates intent better than imitating classes.</LanguageReality><LanguageReality language="Java">Interfaces plus constructor injection fit genuine policy substitution. Avoid an interface for every class or a factory chain without observed variation.</LanguageReality><LanguageReality language="TypeScript">Structural contracts and callable types keep extensions lightweight. Runtime registration still needs validation because external values do not carry static guarantees.</LanguageReality></div></div></section>
<section className="lesson-section page-shell" id="wrong"><Reveal><SectionHeading eyebrow="07 · WRONG OCP" title="Extensibility is not free—and prediction can be wrong." copy="Protect against real pressure, not every imaginable future. A bad extension axis merely moves the next change into a different awkward place."/></Reveal><PrematureAbstractionLab/><div className="wrong-axis"><div><span>ABSTRACTED AXIS</span><b>CustomerType</b><p>regular · premium · employee</p></div><strong>but requirements vary by →</strong><div><span>ACTUAL AXES</span><b>Promotion · Region · Campaign · Time window</b><p>The old hierarchy cannot express combinations cleanly.</p></div></div><h2 className="subsection-title">Conditionals are not evil</h2><div className="when-grid">{[["FINITE ENUM","A closed set with exhaustive handling."],["SIMPLE PARSER","The grammar is stable and local."],["STATE DECODING","One place maps a protocol state."],["TINY ROUTER","Few commands with no plugin pressure."]].map(([a,b])=><div key={a}><span>{a}</span><p>{b}</p></div>)}</div><TradeoffPanel good={["New variants repeatedly reopen stable logic","Policies change and test independently","The extension contract is smaller than the change"]} cost={["Indirection and navigation","Contract and registration maintenance","More integration combinations"]} avoid={["Variation is purely hypothetical","The set is deliberately finite and stable","The abstraction predicts the wrong axis"]}/></section>
<section className="lesson-section lesson-section--tint" id="challenge"><div className="page-shell"><Reveal><SectionHeading eyebrow="08 · NOTIFICATION CHALLENGE" title="Separate two independent dimensions." copy="Email and SMS become Push, Slack, WhatsApp, and Webhook. Then retry behavior starts varying. Do channel and retry belong behind the same extension point?"/></Reveal><ClassificationChallenge title="CHOOSE THE VARIATION AXIS" items={challenge} categories={["NotificationChannel","RetryPolicy","MessageContent"]}/><div className="challenge-pressure"><span>DESIRED INSIGHT</span><p>Notification channel answers <b>how to deliver</b>. Retry policy answers <b>when to try again</b>. Compose them rather than creating EmailWithExponentialRetry, EmailWithNoRetry, SMSWithExponentialRetry…</p></div></div></section>
<section className="lesson-section page-shell" id="interview"><Reveal><SectionHeading eyebrow="09 · INTERVIEW CHECKPOINT" title="Defend the extension seam." copy="Name the variation, stable core, mechanism, regression boundary, and evidence that justifies the abstraction."/></Reveal><InterviewCheckpoint questions={questions}/><h2 className="subsection-title">Common misconceptions</h2><CommonMistakes items={["All conditionals are bad.","Never edit existing code.","Every feature needs an interface.","Inheritance automatically satisfies OCP.","Maximum extensibility is always good.","Design for every hypothetical future requirement.","Strategy Pattern and OCP are the same thing."]}/><div className="answer-card"><span>60-SECOND INTERVIEW ANSWER</span><blockquote>The Open/Closed Principle asks us to identify a real axis of variation and put a stable boundary around it. Stable orchestration stays closed to routine edits while new variants extend the system through a small contract, function, registry, configuration, or another suitable mechanism. Closed never means immutable forever, and OCP does not ban conditionals or require inheritance. I apply it when repeated invasive change and regression risk cost more than the abstraction.</blockquote></div><RapidRevision items={[["What varies?","name one independent change axis"],["What stays stable?","protect the reusable decision or workflow"],["Does a variant reopen core logic?","look for repeated central edits"],["Is pressure real?","use observed change, not fantasy"],["Is abstraction cheaper?","count indirection, wiring, and tests"]]}/><LessonPager previous={{number:"05",title:"Single Responsibility Principle",href:"/learn/single-responsibility-principle"}} next={{number:"07",title:"Liskov Substitution Principle",href:"/learn/liskov-substitution-principle",copy:"Make every extension preserve the behavior its caller was promised."}}/></section></article>}
